
select count(*) from (
SELECT   PU.UPC,PU.PRODID, P.PRODID,PC.AUTHID,PA.AUTHID,
         SZP.STORNUM,SZA.STORNUM,
         P.SUBCLASS, SZP.ZONEID,PA.ZONEID, ZA.ZONEID,
         ZP.ZONEID,
         ZP.ZONECD,
         ZP.ZONENM,
         PA.AUTHID, PRC.EFFFROM, PRC.EFFTHRU
FROM     APP_PRC.PRODUCT_UPC PU 
         INNER JOIN APP_PRC.PRODUCT P ON PU.PRODID = P.PRODID 
         LEFT JOIN APP_PRC.PRICE PRC ON (PU.PRODID = PRC.PRODID AND PRCTYP = 'REG') --?
         LEFT JOIN APP_PRC.STORE_ZONE SZP ON PRC.ZONEID = SZP.ZONEID 
         LEFT JOIN APP_PRC.ZONE ZP ON (SZP.ZONEID = ZP.ZONEID) 
         LEFT JOIN APP_PRC.PRODUCT_CATALOG PC ON (PU.PRODID = PC.PRODID) 
         LEFT JOIN APP_PRC.PRODUCT_AUTHORIZATION PA ON (PC.AUTHID = PA.AUTHID and ZP.ZONEID = PA.ZONEID) 
         LEFT JOIN APP_PRC.ZONE ZA ON (PA.ZONEID = ZA.ZONEID)                        --?
         LEFT JOIN APP_PRC.STORE_ZONE SZA ON (ZA.ZONEID = SZA.ZONEID AND SZA.STORNUM = SZP.STORNUM) --?
WHERE    PRC.EFFFROM <= CURRENT_DATE
AND      (PRC.EFFTHRU IS NULL
     OR  PRC.EFFTHRU >= CURRENT_DATE)
AND  szp.STORNUM = 1525
--and zp.ZONEID = 32890
ORDER BY PU.UPC, SZP.STORNUM, P.SUBCLASS)
;

select * from APP_PRC.STORE

select * from APP_PRC.STORE_ZONE