SELECT
	twshde.FACILITYID,
	twcm.CORP_CODE,
	twcm.CORP_NAME,
	twshde.CUSTOMER_NBR_STND,
	twc.NAME,
	twshde.PO_NBR,
	twshde.INVOICE_NBR,
	twshde.INVOICE_NBR_EXT,
	twshde.BILL_OF_LADING,
	twshde.BILLING_DATE,
	twshde.DELIVERY_DATE,
	twshde.ORDER_RECVE_DTE,
	twshde.OMS_SUBMIT_TIME,
	twshde.ORDER_SOURCE,
	twshde.ORDER_TYPE,
	twshde.ORDER_CONFIM_NBR,
	twshde.REQSTED_ORD_SHIP_DTE,
	twshde.PRO_NUMBER,
	twshde.TRIP_NBR1,
	twshde.STOP_NBR1,
	twshde.TRIP_NBR2,
	twshde.STOP_NBR2,
	twshde.DS_TRIP_NBR,
	twshde.DS_STOP_NBR,
	twshde.DS_SHIP_DATE,
	vaa.LU_CODE AS ASIN,
	twshde.UPC_CASE,
	twshde.UPC_UNIT,
	twshde.ITEM_NBR_HS,
	twshde.ITEM_DESCRIPTION,
	twshde.STORE_PACK,
	twshde.QTY_ORDERED,
	twshde.QTY_ADJUSTED,
	twshde.QTY_SOLD - twshde.QTY_SCRATCHED AS QTY_SHIPPED,
	twshde.OUT_REASON_CODE,
	twi.SHIPPING_CASE_WEIGHT,
	twshde.CASE_CUBE,
	twshde.CATCH_WGT,
	twshde.EXT_RANDOM_WGT,
	twshde.STAND_CARRIER_ALPHA_CODE,
	twshde.CARRIER_ID,
	twshde.TRAILER_ID,
	twshde.DRIVER_NBR,
	twshde.DOOR_SEAL_ID,
	twshde.ASSIGN_ID,
	twshde.PALLET_ID,
	twshde.PALLET_ID_XTREME,
	twshde.ORDER_ID,
	twshde.RTL_ORDER_ID,
	twshde.DC_ORDER_ID
FROM
	CRMADMIN.T_WHSE_SALES_HISTORY_DTL_EXT twshde
INNER JOIN CRMADMIN.T_WHSE_ITEM twi ON
	twshde.FACILITYID = twi.FACILITYID
	AND twshde.ITEM_NBR_HS = twi.ITEM_NBR_HS
INNER JOIN CRMADMIN.T_WHSE_CUST twc ON
	twshde.FACILITYID = twc.FACILITYID
	AND twshde.CUSTOMER_NBR_STND = twc.CUSTOMER_NBR_STND
INNER JOIN CRMADMIN.T_WHSE_CORPORATION_MDM twcm ON
	twc.CUSTOMER_NBR_STND = twcm.CUSTOMER_NBR_STND
	AND twcm.CORP_CODE = 634001
INNER JOIN CRMADMIN.V_AMZ_ASIN vaa ON
	twi.ROOT_ITEM_NBR = vaa.ROOT_ITEM_NBR
	AND twi.LV_ITEM_NBR = vaa.LV_ITEM_NBR
WHERE
--	twshde.BILLING_DATE BETWEEN '2021-04-11' AND '2021-04-17'
	twshde.BILLING_DATE BETWEEN '2021-04-12' AND '2021-04-12'