Select * from CRMADMIN.T_WHSE_SALES_HISTORY_DTL
where facilityid = '009'
  and billing_date between '2007-08-12' and '2007-09-08'
  and WHOL_SALES_CD = '011'
  and FINAL_SELL_AMT > 0;
  
  
SELECT   FACILITYID,
         INVOICE_NBR,
         BILLING_DATE,
         DELIVERY_DATE,
         ORDER_SOURCE,
         ORDER_TYPE,
         BOOKING_NBR,
         CUST_CORP_NBR,
         CUSTOMER_NBR_CORP,
         CUSTOMER_NO_FULL,
         TERRITORY_NO,
         UPC_CASE,
         UPC_UNIT,
         ITEM_NBR,
         ITEM_NBR_CD,
         ITEM_NBR_HS,
         ITEM_DESCRIPTION,
         STORE_PACK,
         SIZE,
         PURCH_STATUS,
         BILLING_STATUS,
         ITEM_DEPT,
         WHOL_SALES_CD,
         BUYER_NBR,
         INVENTORY_TOTAL,
         ON_ORDER_TOTAL,
         QTY_ORDERED,
         QTY_ADJUSTED,
         QTY_SOLD,
         QTY_SUBBED,
         QTY_SCRATCHED,
         OUT_REASON_CODE,
         FINAL_SELL_AMT,
         LAYER_EXT_COST,
         EXTENDED_SALES_AMT,
         CASE WHEN OUT_REASON_CODE IN ('004', '011') THEN 0 ELSE ((CASE WHEN ORDER_TYPE = 'GB' THEN QTY_SOLD ELSE (CASE WHEN (RECORD_ID ='6' or NO_CHRGE_ITM_CDE ='*') THEN 1 ELSE QTY_SOLD - QTY_SCRATCHED END) END) * (FINAL_SELL_AMT - CITY_EXCISE_TAX - CITY_STAMP_TAX - COUNTY_EXCISE_TAX - COUNTY_STAMP_TAX - OTHER_EXCISE_TAX_01 - OTHER_EXCISE_TAX_02 - OTHER_EXCISE_TAX_03 - OTHER_STAMP_TAX_01 - OTHER_STAMP_TAX_02 - OTHER_STAMP_TAX_03 - STATE_EXCISE_TAX - LBL_CASE_CHRGE - PRICE_ADJUSTMENT + LEAKAGE_AMT - (CASE WHEN MRKUP_SPREAD_FLG IN ('1', '2') THEN MRKUP_DLLRS_PER_SHIP_UNT ELSE 0 END) - (CASE WHEN MRKUP_SPREAD_FLG IN ('2') THEN FREIGHT_AMT ELSE 0 END) )) END
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    facilityid in ('063', '058', '059')
AND      billing_date between '2007-10-07' and '2007-11-03'
AND      ITEM_DEPT = '098'
AND      FINAL_SELL_AMT > 0;
