SELECT   *
FROM     CRMADMIN.T_CEC_PROMO
--WHERE    START_DATE > current date
where PROMOTION = 'A0414ADW11'
;

SELECT   *
FROM     CRMADMIN.T_CEC_PROMO_STRUPC
--WHERE    PROCESS_TIMESTAMP > '2014-03-17'
where PROMOTION = 'A0414ADW11'
;

SELECT   *
FROM     CRMADMIN.T_CEC_PROMO_REPT
WHERE    PROMOTION = 'A0414ADW11'
;

SELECT   *
FROM     CRMADMIN.T_CEC_STORE
WHERE    CEC_STORE in (4,5,7,12,118,303);