SELECT   R.COGIPF_REPORTNAME,
         R.COGIPF_REPORTPATH,
         R.COGIPF_PACKAGE,
         L.COGIPF_STATUS,
         L.COGIPF_USERNAME,
         Date(max(R.COGIPF_LOCALTIMESTAMP)) as Last_Executed
FROM     COGADMIN.COGIPF_RUNREPORT R 
         join COGADMIN.COGIPF_USERLOGON L on L.COGIPF_SESSIONID = R.COGIPF_SESSIONID
WHERE    R.COGIPF_LOCALTIMESTAMP > current date - 6 days
--AND      COGIPF_REPORTNAME like '%Customer Purchase Analysis - Deli - Pollys%'
GROUP BY R.COGIPF_REPORTNAME, R.COGIPF_REPORTPATH, R.COGIPF_PACKAGE, 
         L.COGIPF_STATUS, L.COGIPF_USERNAME;