--snowflake
SELECT   str.DEPT_KEY, ITEM_DEPT.DEPT_KEY,
         str.RSL_DEPT_ID, ITEM_DEPT.RSL_DEPT_ID,
         str.UPDATE_TMSP,
         str.*
FROM     EDW.RTL.STR_TRANS_DTL str inner join 
(
    SELECT
        MCL.MDSE_CLASS_KEY,
        MCT.MDSE_CATGY_KEY,
        MG.MDSE_GRP_KEY,
        D.DEPT_KEY,
        RDX.RSL_DEPT_PK AS RSL_DEPT_ID,
        RDX.STORE_NBR AS STORE_NBR,
        TO_NUMBER(TO_VARCHAR(RDX.START_DT, 'YYYYMMDD')) AS START_DATE_ID,
        TO_NUMBER(TO_VARCHAR(RDX.END_DT, 'YYYYMMDD')) AS END_DATE_ID
    FROM EDW.MDM.MDSE_CLASS AS MCL
    JOIN EDW.MDM.MDSE_CATEGORY AS MCT
    ON MCT.MDSE_CATGY_KEY = MCL.MDSE_CATGY_KEY
    JOIN EDW.MDM.MDSE_GROUP AS MG
    ON MG.MDSE_GRP_KEY = MCT.MDSE_GRP_KEY
    JOIN EDW.MDM.DEPARTMENT AS D
    ON D.DEPT_KEY = MG.DEPT_KEY
    JOIN EDW.RTL.RSL_DEPT_XREF AS RDX
    ON RDX.STORE_GRP_KEY = D.DEPT_GRP_KEY
    AND (RDX.STORE_NBR BETWEEN 2300 AND 2400 OR RDX.STORE_NBR BETWEEN 700 AND 800)
) ITEM_DEPT on ITEM_DEPT.MDSE_CLASS_KEY = str.MDSE_CLASS_KEY and ITEM_DEPT.STORE_NBR = str.STORE_NBR and STR.SALES_DATE_ID BETWEEN ITEM_DEPT.START_DATE_ID AND ITEM_DEPT.END_DATE_ID
WHERE    str.SALES_DATE_ID >= 20211108
AND      str.DEPT_KEY = 0
AND      TRIM(str.ORIGIN) = 'TLOGPROC'
;