SELECT   FACILITYID,
         INVOICE_NBR,
         ITEM_NBR_HS,
         ITEM_DESCRIPTION,
         QTY_SOLD,
         QTY_SCRATCHED,
         FUEL_CHRGE_AMT
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '003'
AND      INVOICE_NBR = 922902
AND      BILLING_DATE = '2021-11-13'
AND      ITEM_NBR_HS = '0033878';



SELECT   FACILITYID,
         INVOICE_NBR,
         ITEM_NBR_HS,
         ITEM_DESCRIPTION,
         QTY_SOLD,
         QTY_SCRATCHED,
         FUEL_CHRGE_AMT,
         LBL_CASE_CHRGE
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL_EXT
WHERE    FACILITYID = '003'
AND      INVOICE_NBR = 922902
AND      BILLING_DATE = '2021-11-13'
AND      ITEM_NBR_HS = '0033878'
;