--looksee to fix corporations in sales history
SELECT   FACILITYID , CUSTOMER_NO_FULL, BILLING_DATE, count(*)
--         FACILITYID,
--         CUSTOMER_NO_FULL,
--         CUST_CORP_NBR
from CRMADMIN.T_WHSE_SALES_HISTORY_DTL
--update     CRMADMIN.T_WHSE_SALES_HISTORY_DTL set CUST_CORP_NBR = 279
where BILLING_DATE > '2016-01-01' and FACILITYID in ('002', '008', '054') and CUST_CORP_NBR = 29
and (FACILITYID, CUSTOMER_NO_FULL) in (select FACILITYID, CUSTOMER_NO_FULL from CRMADMIN.T_WHSE_CUST where CUST_CORPORATION = 279)
group by FACILITYID , CUSTOMER_NO_FULL, BILLING_DATE 
;

--select FACILITYID, CUSTOMER_NO_FULL, CUST_CORPORATION from CRMADMIN.T_WHSE_CUST
update CRMADMIN.T_WHSE_CUST set CUST_CORPORATION = 279
WHERE    CUSTOMER_NO_FULL in ('13545202', '13681053', '13710054')
;