Select * from XMETA.DATASTAGEX_XMETAGEN_DSJOBDEFC2E76D84;

--last modified user
SELECT   CONTAINER_RID,
         XMETA_REPOS_OBJECT_ID_XMETA,
         XMETA_CREATED_BY_USER_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (XMETA_CREATION_TIMESTAMP_XMETA / 1000) SECONDS) - 8 HOURS AS XMETA_CREATION_TIMESTAMP_XMETA,
         XMETA_MODIFIED_BY_USER_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (XMETAMODIFICATIONTIMESTAMPXMET / 1000) SECONDS) - 8 HOURS AS XMETAMODIFICATIONTIMESTAMPXMET,
         NAME_XMETA,
         SHORTDESCRIPTION_XMETA,
         JOBTYPE_XMETA,
         CATEGORY_XMETA,
         DSNAMESPACE_XMETA
FROM     xmeta.DATASTAGEX_XMETAGEN_DSJOBDEFC2E76D84
;

--job listing
SELECT   CONTAINER_RID,
         XMETA_REPOS_OBJECT_ID_XMETA,
         XMETA_CREATED_BY_USER_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (XMETA_CREATION_TIMESTAMP_XMETA / 1000) SECONDS) AS XMETA_CREATION_TIMESTAMP_XMETA,
         XMETA_MODIFIED_BY_USER_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (XMETAMODIFICATIONTIMESTAMPXMET / 1000) SECONDS) AS XMETAMODIFICATIONTIMESTAMPXMET,
         NAME_XMETA,
         SHORTDESCRIPTION_XMETA,
         JOBTYPE_XMETA,
         CATEGORY_XMETA,
         DSNAMESPACE_XMETA
FROM     xmeta.DATASTAGEX_XMETAGEN_DSJOBDEFC2E76D84
--WHERE
--upper(DSNAMESPACE_XMETA) = upper('DWH_Datawarehouse')
-- upper(category_xmeta) like upper('\\Jobs\\')
;


SELECT   CONTAINER_RID,
         XMETA_REPOS_OBJECT_ID_XMETA,
         XMETA_CREATED_BY_USER_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (XMETA_CREATION_TIMESTAMP_XMETA / 1000) SECONDS) - 8 HOURS AS XMETA_CREATION_TIMESTAMP_XMETA,
         XMETA_MODIFIED_BY_USER_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (XMETAMODIFICATIONTIMESTAMPXMET / 1000) SECONDS) - 8 HOURS AS XMETAMODIFICATIONTIMESTAMPXMET,
         NAME_XMETA,
         SHORTDESCRIPTION_XMETA,
         JOBTYPE_XMETA,
         CATEGORY_XMETA,
         DSNAMESPACE_XMETA
FROM     xmeta.DATASTAGEX_XMETAGEN_DSJOBDEFC2E76D84
--WHERE    upper(DSNAMESPACE_XMETA) = upper(:')   and upper(category_xmeta) like upper('\\Jobs\\')
;


SELECT   XMETA_CREATED_BY_USER_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (XMETA_CREATION_TIMESTAMP_XMETA / 1000) SECONDS) - 8 HOURS AS XMETA_CREATION_TIMESTAMP_XMETA,
--         XMETA_CREATION_TIMESTAMP_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (XMETAMODIFICATIONTIMESTAMPXMET / 1000) SECONDS) - 8 HOURS AS XMETAMODIFICATIONTIMESTAMPXMET,
--         XMETAMODIFICATIONTIMESTAMPXMET,
         XMETA_MODIFIED_BY_USER_XMETA,
         XMETA_REPOS_OBJECT_ID_XMETA,
         CATEGORYNAME_XMETA,
         CONTAINER_RID,
         CONTEXT_XMETA,
         DELETED_XMETA,
         LEVEL_XMETA,
         MESSAGE_XMETA,
         MSGID_XMETA,
         SEQ_XMETA,
         THROWABLEINFO_XMETA,
         (TIMESTAMP('01/01/1970', '00:00:00') + (TIMESTAMP_XMETA / 1000) SECONDS) - 8 HOURS AS TIMESTAMP_XMETA
--         TIMESTAMP_XMETA
FROM     XMETA.LOGGING_XMETAGEN_LOGGINGEVENT1466CB5F
where (TIMESTAMP('01/01/1970', '00:00:00') + (XMETA_CREATION_TIMESTAMP_XMETA / 1000) SECONDS) - 8 HOURS > current date - 7 days
--where CATEGORYNAME_XMETA = 'IIS-DSTAGE-RUN' --(For Datastage jobs) 
--and SEQ_XMETA=1
;
Select CATEGORYNAME_XMETA, count(*) from XMETA.LOGGING_XMETAGEN_LOGGINGEVENT1466CB5F
group by CATEGORYNAME_XMETA 
--where CATEGORYNAME_XMETA = 'IIS-DSTAGE-RUN' --(For Datastage jobs) 
--and LOG_SEQ=1