SELECT   FACILITYID,
         INVOICE_NBR,
         BILLING_DATE,
         CUSTOMER_NO_FULL,
         ITEM_NBR_HS,
         ITEM_DESCRIPTION,
         QTY_ORDERED,
         QTY_ADJUSTED,
         QTY_SOLD,
         QTY_SUBBED,
         QTY_SCRATCHED,
         FINAL_SELL_AMT,
         MRKUP_DLLRS_PER_SHIP_UNT,
         ITEM_DEPT,
         ITEM_DEPT_HS
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '003'
and ITEM_NBR_HS = '0099908'
and TERRITORY_NO in (21, 27, 31)
--AND      INVOICE_NBR = 70208
--AND      BILLING_DATE = '2018-06-15'
AND      BILLING_DATE between '2018-06-17' and '2018-07-14'
and ITEM_DESCRIPTION = 'ICE CREAM MARKUP'