SELECT   e.eventid,
         e.eventtypeid,
         e.eventname,
         e.startdate,
         e.finishdate,
         e.salestart,
         de.dealid,
         d.productid,
         d.deallevel,
         d.dealtypeid,
         d.dealreasonid,
         d.vitemtypeid,
         d.priceformatid,
         d.dealstatusid,
         d.storesetgroupid,
         d.dealcreatetype,
         d.datefrom,
         d.dateto,
         d.dealname,
         d.dealdesc,
         d.externalref,
         d.offervalid,
         d.ud_theme,
         d.ud_emphasis,
         d.islock,
         d.overallapprovelvl,
         d.dealexpstatusid,
         d.ud_feature,
         d.ud_merchandiser,
         d.ud_pa_grp_desc,
         d.ud_status,
         d.ud_hi_prc_frmt_id,
         d.ud_hi_prmo_prc_amt,
         d.ud_hi_buy_x_qty,
         d.ud_hi_get_mult_qty,
         d.ud_hi_frctnoff_amt,
         d.ud_hi_dllr_off_amt,
         d.ud_hi_pct_off_amt,
         d.ud_lo_prc_frmt_id,
         d.ud_lo_prmo_prc_amt,
         d.ud_lo_buy_x_qty,
         d.ud_lo_get_mult_qty,
         d.ud_lo_frctnoff_amt,
         d.ud_lo_dllr_off_amt,
         d.ud_lo_pct_off_amt,
         d.ud_ad_fee,
         d.ud_dcdsd,
         id.itemid,
         i.itemid,
         i.itemclassid,
         i.productid,
         i.itemhierarchyid,
         i.copyid,
         i.zonelistid,
         i.assetlistid,
         i.sourceitemid,
         i.itemcategoryid,
         i.producthierarchyid,
         i.eventtypeid,
         i.noteid,
         i.defcopy,
         i.signageid
FROM     whmgr.events e 
         inner join whmgr.dealsevent de on e.eventid = de.eventid 
         inner join whmgr.deal d on de.dealid = d.dealid 
         inner join whmgr.itemdeal id on d.dealid = id.dealid 
         inner join whmgr.itemmaster i on id.itemid = i.itemid
WHERE    e.eventid in (14802, 14827, 14873, 14874, 14876, 14879, 14880, 13345, 13346, 13350, 13356)