Select m.STORE_ID,i.TRAN_DATE_KEY, i.PROCESS_TIMESTAMP, count(*)  from ETLADMIN.T_RTL_TRANS_MISSING_TODAY m
left outer join CRMADMIN.T_TRANSACTION_ITEM i on m.STORE_ID= i.STORE_ID and i.TRAN_DATE_KEY = current date - 1 day
group by i.TRAN_DATE_KEY , m.STORE_ID , i.PROCESS_TIMESTAMP