ALTER TABLE CRMADMIN.T_WHSE_DIV_XREF
ADD OMS_CODE_SCHEME  CHAR(1) ;


ALTER TABLE CRMADMIN.T_WHSE_DIV_XREF
ADD UPSTREAM_DC_TYP_CD  CHAR(1) ;


ALTER TABLE CRMADMIN.T_WHSE_DIV_XREF
ADD HANDHELD_STATUS_CD  CHAR(1) ;


ALTER TABLE CRMADMIN.T_WHSE_DIV_XREF
ADD INSITE_STATUS_CD  CHAR(1) ;

COMMENT ON COLUMN CRMADMIN.T_WHSE_DIV_XREF.UPSTREAM_DC_TYP_CD IS 'Upstream DC Type (U = Upstream, D = Downstream, H = Hybrid)	';

COMMENT ON COLUMN CRMADMIN.T_WHSE_DIV_XREF.HANDHELD_STATUS_CD IS 'Sharp Handheld Status (Y = yes, N = no, T = testing)';

COMMENT ON COLUMN CRMADMIN.T_WHSE_DIV_XREF.INSITE_STATUS_CD IS 'Insite Status (Y = yes, N = no, T = testing)';
