SELECT   *
FROM     CRMADMIN.V_WEB_ITEM_COMPONENT
--where FACILITYID = '001' and SHIP_ITEM_NBR_HS = '0191171'
--where FACILITYID = '001' and SHIP_ITEM_NBR_HS = '0385260'
where FACILITYID = '001' and SHIP_ITEM_NBR_HS = '00002014'
;
--WHERE    UPC_UNIT = '00000005100000011'

Select * from CRMADMIN.V_WEB_ITEM_COMPONENT where FACILITYID = '001' and ITEM_NBR_HS = '0385260';

SELECT   *
FROM     CRMADMIN.V_WEB_ITEM_RETAIL_ORDERABLE
where FACILITYID = '058' 
and UPC_UNIT = '00000002708412013'
--and ITEM_NBR_HS = '0363234'
;

--blueberries 0363234

select * from CRMADMIN.V_WEB_ITEM_COMPONENT where FACILITYID = '001' and SHIP_ITEM_NBR_HS = '0363234';

select * from CRMADMIN.T_WHSE_SHIPPER_CMPNTS where FACILITYID = '001' and SHIP_ITEM_NBR_HS = '0363234';

select * from CRMADMIN.V_WEB_ITEM_CORE where FACILITYID = '001' and ITEM_NBR_HS = '0999896';

select * from CRMADMIN.V_WEB_ITEM_RETAIL_ORDERABLE where FACILITYID = '001' and ITEM_NBR_HS = '0002014'; -- Upc=00007565681563

select * from CRMADMIN.V_WEB_ITEM_CORE where UPC_UNIT = '00000003338322228';




--raw components
select * from CRMADMIN.T_WHSE_SHIPPER_CMPNTS where (FACILITYID,
         SHIP_ITEM_NBR_HS,
         COMP_UPC_UNIT) in (
SELECT   FACILITYID,
         ITEM_NBR_HS,
         UPC_UNIT
FROM     CRMADMIN.V_WEB_ITEM_RETAIL_ORDERABLE
GROUP BY FACILITYID, ITEM_NBR_HS, UPC_UNIT
HAVING   count(*) > 1)
;


--web view
select * from CRMADMIN.V_WEB_ITEM_COMPONENT where (FACILITYID,
         ITEM_NBR_HS,
         UPC_UNIT) in (
SELECT   FACILITYID,
         ITEM_NBR_HS,
         UPC_UNIT
FROM     CRMADMIN.V_WEB_ITEM_RETAIL_ORDERABLE
GROUP BY FACILITYID, ITEM_NBR_HS, UPC_UNIT
HAVING   count(*) > 1)
;