SELECT   FACILITYID,
         CUSTOMER_NBR_STND,
         SCHED_LIKE_DC_AREA,
         DELIVERY_DATE,
         DUE_IN_DATE,
         DUE_IN_TIME, count(*) from (
SELECT   sldc.FACILITYID,
         sldc.CUSTOMER_NBR_STND,
         sldc.SCHED_LIKE_DC_AREA,
         da.DELIVERY_DATE,
         da.DUE_IN_DATE,
         da.DUE_IN_TIME
FROM     (SELECT   Distinct FACILITYID,
                   CUSTOMER_NBR_STND,
                   SCHED_LIKE_DC_AREA
          FROM     CRMADMIN.T_WHSE_ORDER_DELIVSCHED) sldc 
         LEFT OUTER JOIN (SELECT DISTINCT FACILITYID, CUSTOMER_NBR_STND, DC_AREA, DELIVERY_DATE, DUE_IN_DATE, DUE_IN_TIME FROM CRMADMIN.T_WHSE_ORDER_DELIVSCHED) da ON (sldc.SCHED_LIKE_DC_AREA = da.DC_AREA AND sldc.FACILITYID = da.FACILITYID AND sldc.CUSTOMER_NBR_STND = da.CUSTOMER_NBR_STND)
--         inner join CRMADMIN.V_WEB_CUSTOMER_FAC wcf on sldc.FACILITYID = wcf.FACILITYID and sldc.CUSTOMER_NBR_STND = wcf.CUSTOMER_NBR_STND 
)
--WHERE    sldc.FACILITYID <> '071';
group by FACILITYID,
         CUSTOMER_NBR_STND,
         SCHED_LIKE_DC_AREA,
         DELIVERY_DATE,
         DUE_IN_DATE,
         DUE_IN_TIME
having count(*) > 1
;

--new version
--select count(*) from (
SELECT   sldc.FACILITYID,
         sldc.CUSTOMER_NBR_STND,
         sldc.SCHED_LIKE_DC_AREA_ID,
         da.DUE_IN_DATE,
         da.DUE_IN_TIME,
         da.DELIVERY_DATE,
         da.DELIVERY_TIME
FROM     (SELECT   Distinct FACILITYID,
                   CUSTOMER_NBR_STND,
                   SCHED_LIKE_DC_AREA_ID
          FROM     CRMADMIN.T_WHSE_ORDER_DELIVSCHED) sldc 
         LEFT OUTER JOIN (SELECT DISTINCT FACILITYID, CUSTOMER_NBR_STND, DC_AREA_ID, DELIVERY_DATE, DELIVERY_TIME, DUE_IN_DATE, DUE_IN_TIME FROM CRMADMIN.T_WHSE_ORDER_DELIVSCHED) da ON (sldc.SCHED_LIKE_DC_AREA_ID = da.DC_AREA_ID AND sldc.FACILITYID = da.FACILITYID AND sldc.CUSTOMER_NBR_STND = da.CUSTOMER_NBR_STND) 
         inner join CRMADMIN.V_WEB_CUSTOMER_FAC wcf on sldc.FACILITYID = wcf.FACILITYID and sldc.CUSTOMER_NBR_STND = wcf.CUSTOMER_NBR_STND
--)
;

--old version
SELECT   ods.FACILITYID,
         ods.CUSTOMER_NBR_STND,
         ods.DC_AREA,
         ods.SCHED_LIKE_DC_AREA,
         ods.DUE_IN_DATE,
         ods.DUE_IN_TIME,
         ods.DELIVERY_DATE,
         ods.DELIVERY_TIME
FROM     CRMADMIN.T_WHSE_ORDER_DELIVSCHED ods 
         inner join CRMADMIN.T_WHSE_DIV_XREF dx on ods.FACILITYID = dx.SWAT_ID
         inner join CRMADMIN.V_WEB_CUSTOMER_FAC cf on ods.FACILITYID = cf.FACILITYID and ods.CUSTOMER_NBR_STND = cf.CUSTOMER_NBR_STND
WHERE    dx.ACTIVE_FLAG = 'Y'
;


SELECT DISTINCT FACILITYID, CUSTOMER_NBR_STND, SCHED_LIKE_DC_AREA.SCHED_LIKE_DC_AREA_ID, DELIVERY_DATE, DUE_IN_DATE, DUE_IN_TIME
FROM CRMADMIN.T_WHSE_ORDER_DELIVSCHED SCHED_LIKE_DC_AREA
WHERE SCHED_LIKE_DC_AREA.FACILITYID <> '071';


SELECT 
SCHED_LIKE_DC_AREA.FACILITYID,
SCHED_LIKE_DC_AREA.CUSTOMER_NBR_STND,
SCHED_LIKE_DC_AREA.SCHED_LIKE_DC_AREA,
DC_AREA.DELIVERY_DATE, 
DC_AREA.DUE_IN_DATE, 
DC_AREA.DUE_IN_TIME
FROM
(SELECT DISTINCT FACILITYID, CUSTOMER_NBR_STND, SCHED_LIKE_DC_AREA
FROM CRMADMIN.T_WHSE_ORDER_DELIVSCHED) SCHED_LIKE_DC_AREA
LEFT OUTER JOIN 
(SELECT DISTINCT FACILITYID, CUSTOMER_NBR_STND, DC_AREA, DELIVERY_DATE, DUE_IN_DATE, DUE_IN_TIME
FROM CRMADMIN.T_WHSE_ORDER_DELIVSCHED) DC_AREA 
ON (SCHED_LIKE_DC_AREA.SCHED_LIKE_DC_AREA = DC_AREA.DC_AREA
	AND SCHED_LIKE_DC_AREA.FACILITYID = DC_AREA.FACILITYID
	AND SCHED_LIKE_DC_AREA.CUSTOMER_NBR_STND = DC_AREA.CUSTOMER_NBR_STND)
WHERE SCHED_LIKE_DC_AREA.FACILITYID <> '071'
;

Select CUSTOMER_NBR_STND, count(*) from CRMADMIN.V_WEB_CUSTOMER group by CUSTOMER_NBR_STND having count(*) > 1;

Select facilityid, CUSTOMER_NBR_STND, count(*) from CRMADMIN.V_WEB_CUSTOMER_FAC group by facilityid, CUSTOMER_NBR_STND having count(*) > 1;


--957381


-- pending orders

SELECT   od.FACILITYID_REQUESTED,
         od.CUSTOMER_NBR_STND,
         od.SHIP_DATE DELIV_SCHED_DATE,
         od.ITEM_NBR_HS_REQUESTED,
         cf.MEMBERSHIP_KEY,
         SUM(od.NET_QTY) NET_QTY
FROM     CRMADMIN.T_WHSE_ORDER_DTL od 
         inner join CRMADMIN.T_WHSE_DIV_XREF dx on od.FACILITYID = dx.SWAT_ID 
         inner join CRMADMIN.V_WEB_CUSTOMER_FAC cf on od.FACILITYID = cf.FACILITYID and od.CUSTOMER_NO_FULL = cf.CUSTOMER_NO_FULL
WHERE    dx.ACTIVE_FLAG = 'Y'
AND      od.SHIP_DATE > TRUNC(SYSDATE)
AND      od.DELIV_REQUESTED_DATE >= TRUNC(SYSDATE)
AND      od.ORDER_STATUS_HS = 'Firm'
AND      od.ORDER_TYPE NOT IN ('NO')
AND      od.OMS_SERVER_TYPE <> 'SHARP'
GROUP BY od.FACILITYID_REQUESTED, od.CUSTOMER_NBR_STND, od.SHIP_DATE, 
         od.ITEM_NBR_HS_REQUESTED, cf.MEMBERSHIP_KEY