select 'V_WEB_AP_VENDOR'                	view_name, count(*) from CRMADMIN.V_WEB_AP_VENDOR union all
select 'V_WEB_BUYER'                   	 view_name, count(*) from CRMADMIN.V_WEB_BUYER union all
select 'V_WEB_CAT_MANAGER'              	view_name, count(*) from CRMADMIN.V_WEB_CAT_MANAGER union all
select 'V_WEB_CAT_MANAGER_CLASS'        	view_name, count(*) from CRMADMIN.V_WEB_CAT_MANAGER_CLASS union all
select 'V_WEB_COMPETITOR_REL'           	view_name, count(*) from CRMADMIN.V_WEB_COMPETITOR_REL union all
select 'V_WEB_CORPORATION'              	view_name, count(*) from CRMADMIN.V_WEB_CORPORATION union all
select 'V_WEB_CUSTOMER'                 	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER union all
select 'V_WEB_CUSTOMER_ATTR'            	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_ATTR union all
select 'V_WEB_CUSTOMER_COMMODITY'       	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_COMMODITY union all
select 'V_WEB_CUSTOMER_CUSTOM_DEPT'     	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_CUSTOM_DEPT union all
select 'V_WEB_CUSTOMER_DEPT_REP'        	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_DEPT_REP union all
select 'V_WEB_CUSTOMER_FAC'             	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_FAC union all
select 'V_WEB_CUSTOMER_GRP'             	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_GRP union all
select 'V_WEB_CUSTOMER_GRP_RTL_PRICE'   	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE union all
select 'V_WEB_CUSTOMER_GRP_RTL_ZONE'    	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_ZONE union all
select 'V_WEB_CUSTOMER_ITEM_DEAUTH'     	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_ITEM_DEAUTH union all
select 'V_WEB_CUSTOMER_ITEM_ORD_LIMIT'  	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_ITEM_ORD_LIMIT union all
select 'V_WEB_CUSTOMER_ITEM_PROMO'      	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_ITEM_PROMO union all
select 'V_WEB_CUSTOMER_ITEM_PROMO_GRP'  	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_ITEM_PROMO_GRP union all
select 'V_WEB_CUSTOMER_ITEM_PROMO_GRP_HDR'  view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_ITEM_PROMO_GRP_HDR union all
select 'V_WEB_CUSTOMER_MDSE_DEPT'       	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_MDSE_DEPT union all
select 'V_WEB_CUSTOMER_PRVT_BRAND'      	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_PRVT_BRAND union all
select 'V_WEB_CUSTOMER_WHSE_DEPT'       	view_name, count(*) from CRMADMIN.V_WEB_CUSTOMER_WHSE_DEPT union all
select 'V_WEB_DC_AREA'                 	 view_name, count(*) from CRMADMIN.V_WEB_DC_AREA union all
select 'V_WEB_FACILITY'                 	view_name, count(*) from CRMADMIN.V_WEB_FACILITY union all
select 'V_WEB_FACILITY_RETAIL_DEPT'     	view_name, count(*) from CRMADMIN.V_WEB_FACILITY_RETAIL_DEPT union all
select 'V_WEB_ITEM_BUYER_NOTES'         	view_name, count(*) from CRMADMIN.V_WEB_ITEM_BUYER_NOTES union all
select 'V_WEB_ITEM_COMPONENT'           	view_name, count(*) from CRMADMIN.V_WEB_ITEM_COMPONENT union all
select 'V_WEB_ITEM_CORE'                	view_name, count(*) from CRMADMIN.V_WEB_ITEM_CORE union all
select 'V_WEB_ITEM_FAMILY_CLASS'            view_name, count(*) from CRMADMIN.V_WEB_ITEM_FAMILY_CLASS union all
select 'V_WEB_ITEM_RETAIL'              	view_name, count(*) from CRMADMIN.V_WEB_ITEM_RETAIL union all
select 'V_WEB_ITEM_RETAIL_ORDERABLE'    	view_name, count(*) from CRMADMIN.V_WEB_ITEM_RETAIL_ORDERABLE union all
select 'V_WEB_MASTERBROKER'             	view_name, count(*) from CRMADMIN.V_WEB_MASTERBROKER union all
select 'V_WEB_MDSE_CAT'                 	view_name, count(*) from CRMADMIN.V_WEB_MDSE_CAT union all
select 'V_WEB_MDSE_CLS'                 	view_name, count(*) from CRMADMIN.V_WEB_MDSE_CLS union all
select 'V_WEB_MDSE_DEPT'                	view_name, count(*) from CRMADMIN.V_WEB_MDSE_DEPT union all
select 'V_WEB_MDSE_DEPT_GRP'            	view_name, count(*) from CRMADMIN.V_WEB_MDSE_DEPT_GRP union all
select 'V_WEB_MDSE_GRP'                 	view_name, count(*) from CRMADMIN.V_WEB_MDSE_GRP union all
select 'V_WEB_ORDERS_DELIVSCHED'            view_name, count(*) from CRMADMIN.V_WEB_ORDERS_DELIVSCHED union all
select 'V_WEB_ORDERS_PENDING'               view_name, count(*) from CRMADMIN.V_WEB_ORDERS_PENDING union all
select 'V_WEB_VENDOR'                   	view_name, count(*) from CRMADMIN.V_WEB_VENDOR