SELECT   FACILITYID,
         CUST_GROUP_NBR,
         UPC_UNIT,
         ITEM_NBR_HS,
         START_DATE,
         count(*) num_rows
FROM     CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE
GROUP BY FACILITYID, CUST_GROUP_NBR, UPC_UNIT, ITEM_NBR_HS, START_DATE
having count(*) > 1
;


select * from CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE where (FACILITYID,
         CUST_GROUP_NBR,
         UPC_UNIT,
         ITEM_NBR_HS,
         START_DATE) in (SELECT   FACILITYID,
         CUST_GROUP_NBR,
         UPC_UNIT,
         ITEM_NBR_HS,
         START_DATE
FROM     CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE
where FACILITYID in ('001', '058')
GROUP BY FACILITYID, CUST_GROUP_NBR, UPC_UNIT, 
ITEM_NBR_HS, 
START_DATE
having count(*) > 1)
order by FACILITYID, UPC_UNIT,CUST_GROUP_NBR, CREATE_TIMESTAMP desc
;
--FACILITYID	CUST_GROUP_NBR	UPC_UNIT	ITEM_NBR_HS	START_DATE
--058	910125	00000001111132016	0162222	2016-12-24
;
select * from CRMADMIN.T_WHSE_CUST_ITEM_RTL_PRICE where (FACILITYID,
         CUST_GROUP_NBR,
         UPC_UNIT,
         ITEM_NBR_HS,
         START_DATE) in (SELECT   FACILITYID,
         CUST_GROUP_NBR,
         UPC_UNIT,
         ITEM_NBR_HS,
         START_DATE
FROM     CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE
where FACILITYID in ('001', '058')
GROUP BY FACILITYID, CUST_GROUP_NBR, UPC_UNIT, ITEM_NBR_HS, START_DATE
having count(*) > 1)
;

Select FACILITYID, CUST_GROUP_NBR, ALTERNATE_CUST_GRP_NBR, CUSTOMER_NO, UPC_UNIT, COMP_ITEM_NBR_HS, SHIP_ITEM_NBR_HS, SRP_START_DATE, RETAIL_UNITS_PER_SRP, SRP , 'C' as SRP_TYPE_CD
from CRMADMIN.T_WHSE_SRP_UPC
--where date(PROCESS_TIMESTAMP) >= current date - 3 day
where ACTIVE_FLG = 'N'
and FACILITYID = '058'
and CUST_GROUP_NBR in ('910125','931155','950027')
and UPC_UNIT = '00000001111132016'
and COMP_ITEM_NBR_HS = '0162222'
and SRP_START_DATE = '2016-12-24'

union 

Select FACILITYID, CUST_GROUP_NBR, ALTERNATE_CUST_GRP_NBR, CUSTOMER_NO, UPC_UNIT, COMP_ITEM_NBR_HS, SHIP_ITEM_NBR_HS, SRP_START_DATE, RETAIL_UNITS_PER_SRP, SRP, 'F' as SRP_TYPE_CD
from CRMADMIN.T_WHSE_SRP_FUTURE_UPC
--where date(PROCESS_TIMESTAMP) >= current date - 3 day
where ACTIVE_FLG = 'N'
and FACILITYID = '058'
and CUST_GROUP_NBR in ('910125','931155','950027')
and UPC_UNIT = '00000001111132016'
and COMP_ITEM_NBR_HS = '0162222'
and SRP_START_DATE = '2016-12-24';


select FACILITYID,CUST_GROUP_NBR,ALTERNATE_CUST_GRP_NBR,CUSTOMER_NO,UPC_UNIT,ITEM_NBR_HS,SHIP_ITEM_NBR_HS,START_DATE,
RETAIL_UNITS_PER_SRP,SRP,ACTIVE_FLG,END_DATE,PROCESS_TIMESTAMP,SRP_TYPE_CD
from CRMADMIN.T_WHSE_CUST_ITEM_RTL_PRICE
where FACILITYID = '058'
and CUST_GROUP_NBR in ('910125','931155','950027')
and UPC_UNIT = '00000001111132016'
and ITEM_NBR_HS = '0162222'
and START_DATE = '2016-12-24'
;


Select *
--from CRMADMIN.T_WHSE_SRP_UPC
from CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE
--where date(PROCESS_TIMESTAMP) >= current date - 10 day
--and ACTIVE_FLG = 'N'
where FACILITYID = '058'
--and CUST_GROUP_NBR in ('910125','931155','950027')
and UPC_UNIT = '00000001111132016'
and ITEM_NBR_HS = '0162222'
--and SRP_START_DATE = '2016-12-24'
;

update CRMADMIN.T_WHSE_CUST_ITEM_RTL_PRICE set ACTIVE_FLG = 'N' where (FACILITYID,
         UPC_UNIT,
         case SHIP_ITEM_NBR_HS 
              when '0000000' then ITEM_NBR_HS 
              else SHIP_ITEM_NBR_HS 
         end,
         CUST_GROUP_NBR,
         START_DATE,
         CREATE_TIMESTAMP)
in (
--find oldest of the duplicates
SELECT   FACILITYID,
         UPC_UNIT,
         ITEM_NBR_HS,
         CUST_GROUP_NBR,
         START_DATE,
         CREATE_TIMESTAMP
FROM     table ( 
SELECT row_number() over (partition by x.FACILITYID, x.UPC_UNIT, x.ITEM_NBR_HS, x.CUST_GROUP_NBR, x.START_DATE order by x.CREATE_TIMESTAMP) rownumber, 	
	FACILITYID, 
	UPC_UNIT, 
	ITEM_NBR_HS, 
	CUST_GROUP_NBR, 
	START_DATE, 
	CREATE_TIMESTAMP 
FROM table( 
select FACILITYID, 
	UPC_UNIT, 
	ITEM_NBR_HS, 
	CUST_GROUP_NBR, 
	START_DATE, 
	CREATE_TIMESTAMP 
from CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE where (FACILITYID, CUST_GROUP_NBR, UPC_UNIT, ITEM_NBR_HS, START_DATE) in 
(SELECT FACILITYID, 
	CUST_GROUP_NBR, 
	UPC_UNIT, 
	ITEM_NBR_HS, 
	START_DATE 
FROM CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE where FACILITYID in ('001', '058') GROUP BY FACILITYID, CUST_GROUP_NBR, UPC_UNIT, ITEM_NBR_HS, START_DATE having count(*) > 1)) x) a
WHERE    rownumber = 1
);



         case rp.SHIP_ITEM_NBR_HS 
              when '0000000' then rp.ITEM_NBR_HS 
              else rp.SHIP_ITEM_NBR_HS 
         end ITEM_NBR_HS,
;
select count(*) from CRMADMIN.T_WHSE_CUST_ITEM_RTL_PRICE where ACTIVE_FLG = 'Z';


-----------------------------------------------------------------------
--cost
-----------------------------------------------------------------------
select * FROM     CRMADMIN.V_WEB_CUSTOMER_ITEM_COST_maint
where (FACILITYID,
         ITEM_NBR_HS,
         UPC_UNIT,
         CUSTOMER_NBR_STND,
         START_DATE)
in (
SELECT   FACILITYID,
         ITEM_NBR_HS,
         UPC_UNIT,
         CUSTOMER_NBR_STND,
         START_DATE
FROM     CRMADMIN.V_WEB_CUSTOMER_ITEM_COST_maint
GROUP BY FACILITYID, ITEM_NBR_HS, UPC_UNIT, CUSTOMER_NBR_STND, START_DATE
HAVING   count(*) > 1
)
;



FACILITYID,CUSTOMER_NBR_STND,UPC_UNIT,ITEM_NBR_HS,START_DATE
058,59,00000046000000031,0002394,2017-03-25
;
select * from crmadmin.T_WHSE_CUST_ITEM_COST 
where FACILITYID = '058' and CUSTOMER_NBR_STND = 59 and UPC_UNIT = '00000046000000031' and ITEM_NBR_HS = '0002394' and REC_START_DATE = '2017-03-25'