SELECT   FACILITYID_REQUESTED, CUSTOMER_NBR_STND , DELIV_SCHED_DATE , ITEM_NBR_HS_REQUESTED , count(*)
FROM     CRMADMIN.V_WEB_ORDERS_PENDING
group by FACILITYID_REQUESTED, CUSTOMER_NBR_STND , DELIV_SCHED_DATE , ITEM_NBR_HS_REQUESTED -- , NET_QTY
having count(*) > 1
;


SELECT   od.FACILITYID_REQUESTED, od.FACILITYID,
         od.CUSTOMER_NBR_STND,
         od.SHIP_DATE DELIV_SCHED_DATE,
         od.ITEM_NBR_HS_REQUESTED,
         cf.MEMBERSHIP_KEY,
         dx.HANDHELD_STATUS_CD,
         dx.INSITE_STATUS_CD,
         SUM(od.NET_QTY) NET_QTY
FROM     CRMADMIN.T_WHSE_ORDER_DTL od 
         inner join CRMADMIN.V_WEB_FACILITY dx on od.FACILITYID = dx.FACILITYID 
         inner join CRMADMIN.V_WEB_CUSTOMER_FAC cf on od.FACILITYID_REQUESTED = cf.FACILITYID and od.CUSTOMER_NO_FULL = cf.CUSTOMER_NO_FULL
         inner join CRMADMIN.V_WEB_ITEM_CORE ic on od.FACILITYID_REQUESTED = ic.FACILITYID and od.ITEM_NBR_HS_REQUESTED = ic.ITEM_NBR_HS 
WHERE    dx.ACTIVE_FLAG = 'Y'
AND      od.SHIP_DATE > TRUNC(SYSDATE)
AND      od.DELIV_REQUESTED_DATE >= TRUNC(SYSDATE)
AND      od.ORDER_STATUS_HS = 'Firm'
AND      od.ORDER_TYPE NOT IN ('NO')
AND      od.OMS_SERVER_TYPE <> 'SHARP'
AND      od.NET_QTY <> 0
--and od.FACILITYID_REQUESTED = '058' and od.CUSTOMER_NBR_STND = 2604 and od.SHIP_DATE = '2017-04-04' and od.ITEM_NBR_HS_REQUESTED = '0801258'
GROUP BY od.FACILITYID_REQUESTED, od.FACILITYID, od.CUSTOMER_NBR_STND, od.SHIP_DATE, 
         od.ITEM_NBR_HS_REQUESTED, cf.MEMBERSHIP_KEY,
         dx.HANDHELD_STATUS_CD,
         dx.INSITE_STATUS_CD
;