SELECT   CUST_GROUP_NBR,
         count(*)
FROM     CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE
WHERE    SRP = 0
AND      FACILITYID = '058'
AND      ACTIVE_FLG = 'Y'
and START_DATE > current date
GROUP BY CUST_GROUP_NBR
;


SELECT   *
FROM     CRMADMIN.V_WEB_CUSTOMER_GRP_RTL_PRICE
WHERE    SRP = 0
AND      FACILITYID = '058'
AND      ACTIVE_FLG = 'Y'
AND      CUST_GROUP_NBR = 900006
--and START_DATE > current date
;