SELECT   Distinct rip.RETAIL_ITEM_KEY, 
         oi.ORDERABLE_ITEM_KEY, 
         ORI.ORD_RTL_ITEM_KEY,
         value(ri.UNIT_UPC_CD, 0) as UNIT_UPC_CD,
         trim(oi.ORD_ITEM_CODE) as ORD_ITEM_CODE,
         rip.CUST_GROUP_KEY as SUG_PRICE_CUST_GROUP_KEY,
         trim(rip.RTLPRC_STRATEGY_CD) as SUG_PRICE_RTLPRC_STRATEGY_CD,
         rip.SELL_UNIT_NBR as SUG_SELL_UNIT_NBR,
         rip.EFFECTIVE_DATE as SUG_PRICE_EFFECTIVE_DATE,
         rip.EXPIRATION_DATE as SUG_PRICE_EXPIRATION_DATE,
         rip.RTL_ITEM_PRICE_AMT as SUG_PRICE_RTL_ITEM_PRICE_AMT,
         ori.MF_MASTER_FLG
FROM     PRODDB2.RETAIL_ITEM_PRICE rip,
         PRODDB2.ORDERABLE_ITEM OI,
         PRODDB2.ORD_RETAIL_ITEM ORI,
         PRODDB2.RETAIL_ITEM RI
WHERE    OI.ORDERABLE_ITEM_KEY = ORI.ORDERABLE_ITEM_KEY
AND      ORI.RETAIL_ITEM_KEY = RI.RETAIL_ITEM_KEY
AND      ORI.MF_MASTER_FLG = 'Y'
AND      OI.ITEM_COMPLETE_FLG = 'Y'
AND      RI.RETAIL_ITEM_KEY = rip.RETAIL_ITEM_KEY
AND      rip.RTLPRC_STRATEGY_CD IN ('A', 'C', 'Z')
AND      rip.RITEM_PRC_STAT_CD = 'ACTIVE'
AND      rip.RTL_ITEM_PRICE_AMT > 0
AND      ((rip.EFFECTIVE_DATE <= CURRENT_DATE
        AND rip.EXPIRATION_DATE > CURRENT_DATE)
     OR  (rip.EXPIRATION_DATE is NULL)
     OR  (rip.EFFECTIVE_DATE > CURRENT_DATE))
--AND      RIP.UPC_CD = RI.UNIT_UPC_CD
;


SELECT   Distinct RI.UNIT_UPC_CD,
         RCP.ITEM_PRICE_AMT,
         RCP.CUST_GROUP_KEY,
         RCP.SELL_UNIT_QTY,
         DATE(RCP.EFFECTIVE_TMSP) AS EFFECTIVE_TMSP,
         DATE(RCP.EXPIRATION_TMSP) AS EXPIRATION_TMSP,
         trim(OI.ORD_ITEM_CODE) as ORD_ITEM_CODE,
         ORI.MF_MASTER_FLG
FROM     PRODDB2.ORDERABLE_ITEM OI,
         PRODDB2.ORD_RETAIL_ITEM ORI,
         PRODDB2.RTL_CUSTOM_PRC RCP,
         PRODDB2.RETAIL_ITEM RI
WHERE    OI.ORDERABLE_ITEM_KEY = ORI.ORDERABLE_ITEM_KEY
AND      ORI.RETAIL_ITEM_KEY = RI.RETAIL_ITEM_KEY
AND      ORI.MF_MASTER_FLG = 'Y'
AND      OI.ITEM_COMPLETE_FLG = 'Y'
AND      RCP.UPC_CD = RI.UNIT_UPC_CD
AND      RCP.PRICE_STATUS_CD = 'ACTIVE'
AND      RCP.ITEM_PRICE_AMT > 0
AND      ((DATE(RCP.EFFECTIVE_TMSP) <= CURRENT_DATE
        AND DATE(RCP.EXPIRATION_TMSP) > CURRENT_DATE)
     OR  (RCP.EXPIRATION_TMSP is NULL)
     OR  (DATE(RCP.EFFECTIVE_TMSP) > CURRENT_DATE))
ORDER BY UNIT_UPC_CD, CUST_GROUP_KEY