Select * 
  from ETLADMIN.T_WHSE_CUSTOMER_GROUP 
 where CUSTOMER_GROUP_ID = 276
;

Select * 
  from ETLADMIN.T_WHSE_CUSTOMER_GROUP_XREF 
 where CUSTOMER_GROUP_TYPE = 'Key Customers - 2011'
   and CUSTOMER_NBR_STND in (32305, 298997, 270517, 32461, 365127, 366505, 366521)
;

delete
  from ETLADMIN.T_WHSE_CUSTOMER_GROUP_XREF 
 where CUSTOMER_GROUP_TYPE = 'Key Customers - 2011'
   and CUSTOMER_NBR_STND in (32305, 298997, 270517, 32461, 365127, 366505, 366521)
;
commit;

Select * 
  from ETLADMIN.T_WHSE_CUSTOMER_GROUP_XREF 
 where CUSTOMER_GROUP_TYPE = 'Key Customers - 2011'
   and CUSTOMER_NBR_STND in (250527);
;

Select g.CUSTOMER_GROUP_TYPE, g.CUSTOMER_GROUP_ID, g.CUSTOMER_GROUP_NAME, g.ADDRESS1, g.ADDRESS2, g.CITY, g.STATE, g.ZIP, g.TELEPHONE, g.OWNER, g.CONTACT, g.CONTACT_TELEPHONE, g.CONTACT_EXTENSION, x.FACILITYID, x.CUSTOMER_NBR_STND, c.NAME, c.STATUS_CD
  from ETLADMIN.T_WHSE_CUSTOMER_GROUP g inner join ETLADMIN.T_WHSE_CUSTOMER_GROUP_XREF x 
    on g.CUSTOMER_GROUP_TYPE = x.CUSTOMER_GROUP_TYPE
   and g.CUSTOMER_GROUP_ID = x.CUSTOMER_GROUP_ID
  inner join CRMADMIN.T_WHSE_CUST c
    on x.FACILITYID = c.FACILITYID 
   and x.CUSTOMER_NBR_STND = c.CUSTOMER_NBR_STND
 where g.CUSTOMER_GROUP_TYPE = 'Key Customers - 2011'
order by CUSTOMER_GROUP_ID
;
