/*Supplier Structure Defaults*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTFOURND';

SELECT *
FROM INTFOURND;

/*Supplier Structure Detail*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTFOURN';

SELECT *
FROM INTFOURN;

/*Supplier Commerical Contracts*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTCCOM';

SELECT *
FROM ADG.INTCCOM;

/*Supplier Service Contracts*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTCSERV';

SELECT *
FROM INTCSERV;

/*Supplier Payment Contracts*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTCREGL';

SELECT *
FROM INTCREGL;

/*Sites*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTSITE';

SELECT *
FROM INTSITE;

/*Networks*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTRESOBJ';

SELECT *
FROM INTRESOBJ;

/*Networks*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTRES';

SELECT *
FROM INTRES;

/*Networks*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTRESSTRUC';

SELECT *
FROM INTRESSTRUC;

/*Network Structure*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTSTRUCT';

SELECT *
FROM INTSTRUCT;

/*Merch Structure Detail*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTOBJ';

SELECT *
FROM INTOBJ;

/*Item EAN Codes*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTCOCA';

SELECT *
FROM INTCOCA;

/*Root Items*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTART';

SELECT *
FROM INTART;

/*Root Items UV/UL */
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTUVUL';

SELECT *
FROM INTUVUL;

/*Sellable Assortments */
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTUVUL';

SELECT *
FROM INTARTSIT;

/*Warehouse Assortments */
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTASENT';

SELECT *
FROM INTASENT;

/*Units Defaults*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTUNITESD';

SELECT *
FROM INTUNITESD;

/*Units*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTUNITES';

SELECT *
FROM INTUNITES;


/*Item Characteristic Codes*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTARTCTECH';

SELECT *
FROM INTARTCTECH;

/*Item Case Codes*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTARTCOUL';

SELECT *
FROM INTARTCOUL;

/*Item Orderable Assortment Defaults*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTARTASSD';

SELECT *
FROM INTARTASSD;

/*Item Orderable Assortment*/
SELECT COLUMN_NAME, COMMENTS
FROM ALL_COL_COMMENTS a 
WHERE TABLE_NAME LIKE 'INTARTASS';

SELECT *
FROM adg.INTARTASS;



/*plk*/
--item oa
select IASCNUF as mstrvend, IASCEXT as rootnbr, IASCEXVL as lvnbr, IASSITE as site, IASREFC as siteitem, IASNFILF as adrschn, IASCCNUM as comcont, IASDTRT as convdate, IASTRT as recstatus
from adg.INTARTASS
where IASTRT = 2;


select * from adg.NF_ITEM where ISI_ITEM_CODE = '62275915';

SELECT  ia.IASCNUF as master_vendor,
       ia.IASCEXT as root_item_nbr,
       ia.IASCEXVL as lv_nbr,
       ia.IASNFILF as adrschn,
       ia.IASCCNUM as comcont,
       ia.IASDTRT as convert_date,
       ia.IASTRT as record_status, 
       substr(ni.ISI_ITEM_CODE,1,2) as facility, 
       substr(ni.ISI_ITEM_CODE,3,6) as item_code, 
       ia.IASNERR, 
       ia.IASMESS
FROM    adg.INTARTASS ia left outer join adg.NF_ITEM ni on ia.IASREFC = ni.ISI_ITEM_CODE
WHERE   ia.IASTRT = 2;

SELECT BST_RECORD_ID_1, BST_STATUS, BST_RESPONSE, BST_RESPONSE_TIME, BST_TRANID FROM adg.NF_BICEPS_SYNC_TRAN WHERE BST_TRANID>=200000 and BST_STATUS in (2,3) ORDER BY BST_TRANID, BST_ID;


SELECT  substr(BST_RESPONSE,19,2) facility_id,
       substr(BST_RESPONSE,21,6) item_nbr,
       substr(BST_RESPONSE,37,999) err_message,
       BST_STATUS 
  FROM adg.NF_BICEPS_SYNC_TRAN 
 WHERE BST_STATUS in (2,3)
   and substr(BST_RESPONSE,19,2)  between '01' and '71'
group by substr(BST_RESPONSE,19,2),
       substr(BST_RESPONSE,21,6),
       substr(BST_RESPONSE,37,999),
       BST_STATUS
;

select * from adg.erreurprg WHERE ERRSTAT=16
order by errdcre desc, errtrid desc,  errord;


select * from adg.LIENSERV;