
	

--V_FISCAL_CALENDAR
SELECT   FD.FISCAL_DAY_ID AS "Fcl Day ID",
         FD.LY_DAY_ID AS "Fcl Day ID LY",
         FD.SALES_DT AS "Dt",
         FD.LY_SALES_DT AS "Dt LY",
         FD.WEEKDAY_NBR AS "Wk Day Nbr",
         FD.WEEKDAY_DESC AS "Wk Day Desc",
         FD.FISCAL_DAY_NBR AS "Fcl Day Nbr",
         FD.FISCAL_WEEK_ID AS "Fcl Wk ID",
         FW.LY_WEEK_ID AS "Fcl Wk ID LY",
         FW.FISCAL_WEEK_NBR AS "Fcl Wk Nbr",
         FW.START_DT AS "Wk Strt Dt",
         FW.END_DT AS "Wk End Dt",
         FW.PREVIOUS_WEEK_ID AS "Prev Fcl Wk ID",
         FW.PERIOD_WEEK_NBR AS "Wk of Per Nbr",
         FD.FISCAL_PERIOD_ID AS "Fcl Per ID",
         FP.FISCAL_PERIOD_NBR AS "Fcl Per Nbr",
         FP.START_DT AS "Fcl Per Strt Dt",
         FP.END_DT AS "Fcl Per End Dt",
         FP.PREVIOUS_PERIOD_ID AS "Prev Fcl Per ID",
         FD.FISCAL_QUARTER_ID AS "Fcl Qtr ID",
         FQ.FISCAL_QUARTER_NBR AS "Fcl Qtr Nbr",
         FQ.START_DT AS "Fcl Qtr Strt Dt",
         FQ.END_DT AS "Fcl Qtr End Dt",
         FD.FISCAL_YEAR_ID AS "Fcl Yr ID",
         FY.START_DT AS "Fcl Yr Strt Dt",
         FY.END_DT AS "Fcl Yr End Dt",
         CASE 
              WHEN (FD.FISCAL_YEAR_ID = (SELECT DISTINCT FISCAL_DAY.FISCAL_YEAR_ID FROM WH_OWNER.FISCAL_DAY WHERE (FISCAL_DAY.SALES_DT = DATE('now(0)'::"VARCHAR")))) THEN 'Y'::"VARCHAR" 
              ELSE 'N'::"VARCHAR" 
         END AS "Curr Yr Flg",
         CASE 
              WHEN (FD.SALES_DT >= DATE('now(0)'::"VARCHAR")) THEN 'Y'::"VARCHAR" 
              ELSE 'N'::"VARCHAR" 
         END AS "Ftr Dt",
         CASE 
              WHEN (FD.SALES_DT = (DATE('now(0)'::"VARCHAR") - 1)) THEN 'Y'::"VARCHAR" 
              ELSE 'N'::"VARCHAR" 
         END AS "Curr Dt Flg",
         CASE 
              WHEN (FD.FISCAL_WEEK_ID = (SELECT DISTINCT FISCAL_DAY.FISCAL_WEEK_ID FROM WH_OWNER.FISCAL_DAY WHERE (FISCAL_DAY.SALES_DT = (DATE('now(0)'::"VARCHAR") - 1)))) THEN 'Y'::"VARCHAR" 
              ELSE 'N'::"VARCHAR" 
         END AS "Curr Wk Flg",
         HCD.HOLIDAY AS "Holiday",
         HCD."Day Count Down" AS "Holiday Count Down",
         HCD."Dt LY" AS "Dt LY Holiday",
         HCD."Week Count Down",
         CASE 
              WHEN ((FW.END_DT >= (SELECT DISTINCT FW.END_DT FROM (WH_OWNER.FISCAL_DAY FD JOIN WH_OWNER.FISCAL_WEEK FW ON ((FD.FISCAL_WEEK_ID = FW.FISCAL_WEEK_ID))) WHERE ((FW.END_DT >= (DATE('now(0)'::"VARCHAR") - 7)) AND (FW.END_DT <= (DATE('now(0)'::"VARCHAR") - 1))))) AND (FW.END_DT <= (SELECT DISTINCT FW.END_DT FROM (WH_OWNER.FISCAL_DAY FD JOIN WH_OWNER.FISCAL_WEEK FW ON ((FD.FISCAL_WEEK_ID = FW.FISCAL_WEEK_ID))) WHERE (FD.SALES_DT = (DATE('now(0)'::"VARCHAR") - 1))))) THEN 'Y'::"VARCHAR" 
              ELSE 'N'::"VARCHAR" 
         END AS "LW TW Flag",
         (FD.LY_SALES_DT - 364) AS "Dt LLY"
FROM     ((((WH_OWNER.FISCAL_DAY FD 
         JOIN WH_OWNER.FISCAL_WEEK FW ON ((FD.FISCAL_WEEK_ID = FW.FISCAL_WEEK_ID))) 
         JOIN WH_OWNER.FISCAL_PERIOD FP ON ((FW.FISCAL_PERIOD_ID = FP.FISCAL_PERIOD_ID))) 
         JOIN WH_OWNER.FISCAL_QUARTER FQ ON ((FP.FISCAL_QUARTER_ID = FQ.FISCAL_QUARTER_ID))) 
         JOIN WH_OWNER.FISCAL_YEAR FY ON ((FQ.FISCAL_YEAR_ID = FY.FISCAL_YEAR_ID))) 
         LEFT JOIN WH_OWNER.I_HOLIDAY_DAILY_COUNTDOWN HCD ON ((FD.SALES_DT = HCD.DT))
WHERE    ((FY.FISCAL_YEAR_ID >= (SELECT DISTINCT (FISCAL_DAY.FISCAL_YEAR_ID - 3) FROM WH_OWNER.FISCAL_DAY WHERE (FISCAL_DAY.SALES_DT = DATE('now(0)'::"VARCHAR"))))
     AND (FY.FISCAL_YEAR_ID <= (SELECT DISTINCT FISCAL_DAY.FISCAL_YEAR_ID FROM WH_OWNER.FISCAL_DAY WHERE (FISCAL_DAY.SALES_DT = DATE('now(0)'::"VARCHAR")))))
     ;
     
    
    --V_FISCAL_CALENDAR_PDDF
((((((((((((((((
SELECT
	V_FISCAL_CALENDAR."Fcl Day ID",
	V_FISCAL_CALENDAR."Fcl Day ID LY",
	V_FISCAL_CALENDAR."Dt",
	V_FISCAL_CALENDAR."Dt LY",
	V_FISCAL_CALENDAR."Wk Day Nbr",
	V_FISCAL_CALENDAR."Wk Day Desc",
	V_FISCAL_CALENDAR."Fcl Day Nbr",
	V_FISCAL_CALENDAR."Fcl Wk ID",
	V_FISCAL_CALENDAR."Fcl Wk ID LY",
	V_FISCAL_CALENDAR."Fcl Wk Nbr",
	V_FISCAL_CALENDAR."Wk Strt Dt",
	V_FISCAL_CALENDAR."Wk End Dt",
	V_FISCAL_CALENDAR."Prev Fcl Wk ID",
	V_FISCAL_CALENDAR."Wk of Per Nbr",
	V_FISCAL_CALENDAR."Fcl Per ID",
	V_FISCAL_CALENDAR."Fcl Per Nbr",
	V_FISCAL_CALENDAR."Fcl Per Strt Dt",
	V_FISCAL_CALENDAR."Fcl Per End Dt",
	V_FISCAL_CALENDAR."Prev Fcl Per ID",
	V_FISCAL_CALENDAR."Fcl Qtr ID",
	V_FISCAL_CALENDAR."Fcl Qtr Nbr",
	V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
	V_FISCAL_CALENDAR."Fcl Qtr End Dt",
	V_FISCAL_CALENDAR."Fcl Yr ID",
	V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
	V_FISCAL_CALENDAR."Fcl Yr End Dt",
	V_FISCAL_CALENDAR."Curr Yr Flg",
	V_FISCAL_CALENDAR."Ftr Dt",
	V_FISCAL_CALENDAR."Curr Dt Flg",
	V_FISCAL_CALENDAR."Curr Wk Flg",
	V_FISCAL_CALENDAR."Holiday",
	V_FISCAL_CALENDAR."Holiday Count Down",
	V_FISCAL_CALENDAR."Dt LY Holiday",
	V_FISCAL_CALENDAR."Week Count Down",
	V_FISCAL_CALENDAR."LW TW Flag",
	V_FISCAL_CALENDAR."Dt LLY",
	('1'::NUMERIC(1,
	0))::NUMERIC(10,
	1) AS "Pddf Sort ID",
	('None'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
	WH_OWNER.V_FISCAL_CALENDAR)
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('2'::NUMERIC(1,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('This Week'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
(V_FISCAL_CALENDAR."Wk End Dt" = (
SELECT
	DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 1))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('3'::NUMERIC(1,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Last Week'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('4'::NUMERIC(1,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Current Period'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
(V_FISCAL_CALENDAR."Fcl Per ID" = (
SELECT
	DISTINCT V_FISCAL_CALENDAR."Fcl Per ID"
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('5'::NUMERIC(1,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Current Quarter'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
(V_FISCAL_CALENDAR."Fcl Qtr ID" = (
SELECT
	DISTINCT V_FISCAL_CALENDAR."Fcl Qtr ID"
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('6'::NUMERIC(1,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Current Year'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
(V_FISCAL_CALENDAR."Fcl Yr ID" = (
SELECT
	DISTINCT V_FISCAL_CALENDAR."Fcl Yr ID"
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('7'::NUMERIC(1,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 2 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 10)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('8'::NUMERIC(1,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 4 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 21)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('9'::NUMERIC(1,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 6 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 35)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 14))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 8)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 14))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 8))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('10'::NUMERIC(2,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 8 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 49)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('11'::NUMERIC(2,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 12 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 77)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('11.1'::NUMERIC(3,
1))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 13 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 84)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('12'::NUMERIC(2,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 26 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 175)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('13'::NUMERIC(2,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 52 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 357)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('14'::NUMERIC(2,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Previous 104 Weeks'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= (
SELECT
	DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 721)
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1))))))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('15'::NUMERIC(2,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('Pre COVID-19'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
((V_FISCAL_CALENDAR."Wk End Dt" >= '2020-01-04'::DATE)
	AND (V_FISCAL_CALENDAR."Wk End Dt" <= '2020-03-07'::DATE))))
UNION ALL (
SELECT
V_FISCAL_CALENDAR."Fcl Day ID",
V_FISCAL_CALENDAR."Fcl Day ID LY",
V_FISCAL_CALENDAR."Dt",
V_FISCAL_CALENDAR."Dt LY",
V_FISCAL_CALENDAR."Wk Day Nbr",
V_FISCAL_CALENDAR."Wk Day Desc",
V_FISCAL_CALENDAR."Fcl Day Nbr",
V_FISCAL_CALENDAR."Fcl Wk ID",
V_FISCAL_CALENDAR."Fcl Wk ID LY",
V_FISCAL_CALENDAR."Fcl Wk Nbr",
V_FISCAL_CALENDAR."Wk Strt Dt",
V_FISCAL_CALENDAR."Wk End Dt",
V_FISCAL_CALENDAR."Prev Fcl Wk ID",
V_FISCAL_CALENDAR."Wk of Per Nbr",
V_FISCAL_CALENDAR."Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Per Nbr",
V_FISCAL_CALENDAR."Fcl Per Strt Dt",
V_FISCAL_CALENDAR."Fcl Per End Dt",
V_FISCAL_CALENDAR."Prev Fcl Per ID",
V_FISCAL_CALENDAR."Fcl Qtr ID",
V_FISCAL_CALENDAR."Fcl Qtr Nbr",
V_FISCAL_CALENDAR."Fcl Qtr Strt Dt",
V_FISCAL_CALENDAR."Fcl Qtr End Dt",
V_FISCAL_CALENDAR."Fcl Yr ID",
V_FISCAL_CALENDAR."Fcl Yr Strt Dt",
V_FISCAL_CALENDAR."Fcl Yr End Dt",
V_FISCAL_CALENDAR."Curr Yr Flg",
V_FISCAL_CALENDAR."Ftr Dt",
V_FISCAL_CALENDAR."Curr Dt Flg",
V_FISCAL_CALENDAR."Curr Wk Flg",
V_FISCAL_CALENDAR."Holiday",
V_FISCAL_CALENDAR."Holiday Count Down",
V_FISCAL_CALENDAR."Dt LY Holiday",
V_FISCAL_CALENDAR."Week Count Down",
V_FISCAL_CALENDAR."LW TW Flag",
V_FISCAL_CALENDAR."Dt LLY",
('16'::NUMERIC(2,
0))::NUMERIC(10,
1) AS "Pddf Sort ID",
('During COVID-19'::"VARCHAR")::VARCHAR(18) AS "Pddf Desc"
FROM
WH_OWNER.V_FISCAL_CALENDAR
WHERE
(V_FISCAL_CALENDAR."Wk End Dt" >= '2020-03-14'::DATE))
;

--V_DAY_LIST
SELECT V_FISCAL_CALENDAR."Dt" FROM WH_OWNER.V_FISCAL_CALENDAR
;


--V_EXEC_DASH_STO_WK_GRP_SLS
SELECT
	((BTRIM("VARCHAR"(C.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))) AS "Comp Store Key",
	C.STORE_NBR AS "Store Nbr",
	((BTRIM("VARCHAR"(G.MDSE_GRP_KEY)) || ' - '::"VARCHAR") || BTRIM
	(CASE WHEN (I.ITEM_BRAND_CD NOTNULL) THEN 'Y'::"VARCHAR"
	ELSE 'N'::"VARCHAR"
END)) AS "Group OB Key",
	D.END_DT AS "Wk End Dt",
	SUM(A.TOTAL_SALES_AMT) AS "Sales Dollars",
	SUM(CASE WHEN (K.EVENT_TYPE = 'Promotion'::"VARCHAR") THEN A.TOTAL_SALES_AMT ELSE '0'::NUMERIC END) AS "Sales Dollars Promo",
	SUM(A.WHSE_MVMT_QTY) AS "Sales Quantity",
	SUM(CASE WHEN (K.EVENT_TYPE = 'Promotion'::"VARCHAR") THEN A.WHSE_MVMT_QTY ELSE '0'::NUMERIC END) AS "Sales Quantity Promo",
	SUM(A.EXT_MOVEMENT_WT) AS "Sales Weight",
	SUM(CASE WHEN (K.EVENT_TYPE = 'Promotion'::"VARCHAR") THEN A.EXT_MOVEMENT_WT ELSE '0'::NUMERIC END) AS "Sales Weight Promo"
FROM
	(((((((((WH_OWNER.EFIN_WK_LINE_ITEM A
JOIN WH_OWNER.MDSE_ITEM B ON
	((A.ITEM_ID = B.ITEM_ID)))
JOIN WH_OWNER.LINE C ON
	((A.SALES_LINE_ID = C.SALES_LINE_ID)))
JOIN WH_OWNER.FISCAL_WEEK D ON
	((A.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
JOIN WH_OWNER.MDSE_CLASS E ON
	((B.MDSE_CLASS_KEY = E.MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY F ON
	((E.MDSE_CATGY_KEY = F.MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP G ON
	((F.MDSE_GRP_KEY = G.MDSE_GRP_KEY)))
JOIN (
	SELECT
		DISTINCT ITEM_BRAND.ITEM_BRAND_CD
	FROM
		WH_OWNER.ITEM_BRAND) H ON
	((B.ITEM_BRAND_CD = H.ITEM_BRAND_CD)))
LEFT JOIN WH_OWNER.I_PRIVATE_LABEL_CODES I ON
	(((H.ITEM_BRAND_CD)::"VARCHAR" = I.ITEM_BRAND_CD)))
JOIN WH_OWNER.I_EVENT_CODE_LARGE K ON
	(((A.EVENT_CD)::"VARCHAR" = K.EVENT_CD)))
WHERE
	((((C.CUST_STATUS_KEY < 3)
		AND ((D.END_DT >= (
		SELECT
			DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 903)
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
			AND (D.END_DT <= (
			SELECT
				DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
					AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
		AND (C.FORMAT_TYPE_ID IN ('SUPERMKT  '::BPCHAR)))
		AND (C.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))
GROUP BY
	((BTRIM("VARCHAR"(C.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))),
	C.STORE_NBR,
	((BTRIM("VARCHAR"(G.MDSE_GRP_KEY)) || ' - '::"VARCHAR") || BTRIM
	(CASE WHEN (I.ITEM_BRAND_CD NOTNULL) THEN 'Y'::"VARCHAR"
	ELSE 'N'::"VARCHAR"
END)),
	D.END_DT
;

--V_LINE_SUPERMARKET
SELECT
	A.STORE_NBR AS "Store Nbr",
	A.SALES_LINE_ID AS "Store ID",
	A.SALES_LINE_DESC AS "Store Description",
	A.SLS_LINE_OPEN_DT AS "Open Date",
	A.SLS_LINE_CLOSE_DT AS "Close Date",
	B.FORMAT_TYPE_DESC AS "Format",
	C.MKTG_CHAIN_DESC AS "Banner",
	F.SALES_CHAIN_DESC AS "Sales Chain",
	CASE
		WHEN (((F.SALES_CHAIN_DESC = 'UMW'::BPCHAR)
		OR (F.SALES_CHAIN_DESC = 'Family Fresh'::BPCHAR))
		OR (F.SALES_CHAIN_DESC = 'Omaha'::BPCHAR)) THEN 'West'::"VARCHAR"
		ELSE
		CASE
			WHEN (F.SALES_CHAIN_DESC = 'Martins'::BPCHAR) THEN 'Martins'::"VARCHAR"
			ELSE 'Michigan'::"VARCHAR"
		END
	END AS "Division",
	A.LOYALTY_STATUS_CD AS "Loyalty Status",
	G.SALES_CHANNEL_DESC AS "Sales Channel",
	COMP_STATUS.COMP_STATUS_DESC AS "Comp Status",
	CASE
		WHEN (FL."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS FL_STORE,
	CASE
		WHEN (KIRN."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KIRN_STORE,
	CASE
		WHEN (KIRNM."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KIRN_MAJOR_REMODELS,
	CASE
		WHEN (KIRNTU."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KIRN_TOUCHUPS,
	CASE
		WHEN (KIRNP."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KIRN_POSITIONED,
	CASE
		WHEN (KIRNW."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KIRN_WEST_FOCUS,
	CASE
		WHEN (KIRNF."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KIRN_FENTON,
	CASE
		WHEN (KIRND."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KIRN_DANS,
	CASE
		WHEN (KIRNFA."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KIRN_FARGO,
	CASE
		WHEN (KIRNEX4580."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS KRIN_STORES_1580EXCLUDED,
	CASE
		WHEN (SDVG."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS SENIOR_DISCOUNT_VG,
	CASE
		WHEN (SDFFN."Store Nbr" NOTNULL) THEN 1
		ELSE 0
	END AS SENIOR_DISCOUNT_FF_NORTH,
	CASE
		WHEN (Z."Store Nbr" NOTNULL) THEN Z."Fresh West Store Group"
		ELSE (C.MKTG_CHAIN_DESC)::"VARCHAR"
	END AS "Fresh West Store Group",
	CASE
		WHEN (SG."Hot Bar Full Service" NOTNULL) THEN SG."Hot Bar Full Service"
		WHEN ('N' NOTNULL) THEN 'N'::"VARCHAR"
		ELSE NULL::"VARCHAR"
	END AS "Hot Bar Full Service",
	CASE
		WHEN (SG."Hot Bar Self Service" NOTNULL) THEN SG."Hot Bar Self Service"
		WHEN ('N' NOTNULL) THEN 'N'::"VARCHAR"
		ELSE NULL::"VARCHAR"
	END AS "Hot Bar Self Service",
	CASE
		WHEN (SG."Pastry Case" NOTNULL) THEN SG."Pastry Case"
		WHEN ('N' NOTNULL) THEN 'N'::"VARCHAR"
		ELSE NULL::"VARCHAR"
	END AS "Pastry Case",
	CASE
		WHEN (SG."Virtual Food Truck" NOTNULL) THEN SG."Virtual Food Truck"
		WHEN ('N' NOTNULL) THEN 'N'::"VARCHAR"
		ELSE NULL::"VARCHAR"
	END AS "Virtual Food Truck",
	SR."Store Rating",
	CASE
		WHEN (ADB."Store Nbr" NOTNULL) THEN ADB."Ad Break"
		ELSE 'Sunday'::"VARCHAR"
	END AS "Ad Break",
	('District '::"VARCHAR" || BTRIM(("VARCHAR"(A.DISTRICT_KEY))::VARCHAR(10))) AS "District",
	CASE
		WHEN (A.SALES_LINE_DESC ~~ LIKE_ESCAPE('%MARTIN%'::"VARCHAR",
		'\'::"VARCHAR")) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Martins Flag",
	CASE
		WHEN (FDS."Fresh Divide Stores" NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Fresh Divide Stores",
	CASE
		WHEN (BP."Store Nbr" NOTNULL) THEN BP.BANNER
		ELSE 'Other'::"VARCHAR"
	END AS "Promo Banner",
	DS.SPECIALIST AS "Dan Specialist",
	CASE
		WHEN (SBC."SN Corp Supplied by Caito" NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "SN Corp Supplied by Caito",
	CASE
		WHEN (SCS."St Cloud Stores" NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "St Cloud Stores",
	PZ."PZ Lookup",
	PZ."KVI Region",
	PZ."Primary Competitor",
	PZ."Center Store - PZ",
	PZ."Fresh - Meat, Seafood, Deli, Bakery - PZ",
	PZ."Fresh - Produce & Floral - PZ",
	PZ."POP - PZ",
	PZ."BEER - PZ",
	PZ."WINE - PZ",
	PZ."LIQUOR - PZ",
	DST."District Manager",
	A.CUST_STATUS_KEY,
	CASE
		WHEN (FBS."Store" NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "French Bread Store",
	CASE
		WHEN (CS2Y."2 Yr Comp" NOTNULL) THEN CS2Y."2 Yr Comp"
		WHEN ('N' NOTNULL) THEN 'N'::"VARCHAR"
		ELSE NULL::"VARCHAR"
	END AS "2 Yr Comp",
	CASE
		WHEN (GS."Store Nbr" NOTNULL) THEN GS.SPECIALIST
		ELSE 'UNASSIGNED'::"VARCHAR"
	END AS "George Specialist",
	CASE
		WHEN (SC."Store Nbr" NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Closed Store Flg",
	SCMS."Store Clusters (M&S)" AS "Store Clusters",
	SS."STATE"
FROM
	((((((((((((((((((((((((((((((((((WH_OWNER.LINE A
LEFT JOIN WH_OWNER.SALES_LINE_FORMAT B ON
	((A.FORMAT_TYPE_ID = B.FORMAT_TYPE_ID)))
LEFT JOIN WH_OWNER.MKTG_CHAIN C ON
	((A.MKTG_CHAIN_ID = C.MKTG_CHAIN_ID)))
LEFT JOIN WH_OWNER."CHAIN" F ON
	((A.SALES_CHAIN_ID = F.SALES_CHAIN_ID)))
LEFT JOIN WH_OWNER.CHANNEL G ON
	((F.SALES_CHANNEL_ID = G.SALES_CHANNEL_ID)))
LEFT JOIN WH_OWNER.COMP_STATUS COMP_STATUS ON
	((A.CUST_STATUS_KEY = COMP_STATUS.COMP_STATUS_KEY)))
LEFT JOIN WH_OWNER.I_FRESH_WEST_STORE_GROUP Z ON
	((A.STORE_NBR = Z."Store Nbr")))
LEFT JOIN WH_OWNER.I_STORE_GROUPS_DELI SG ON
	((A.STORE_NBR = SG."Store Nbr")))
LEFT JOIN WH_OWNER.I_STORE_RATING SR ON
	((A.STORE_NBR = INT4(SR."Str Nbr"))))
LEFT JOIN WH_OWNER.I_STORE_AD_BREAK ADB ON
	((A.STORE_NBR = ADB."Store Nbr")))
LEFT JOIN WH_OWNER.I_FRESH_DIVIDE_STORE FDS ON
	((A.STORE_NBR = INT4(FDS."Fresh Divide Stores"))))
LEFT JOIN WH_OWNER.I_BANNER_PROMO BP ON
	((A.STORE_NBR = BP."Store Nbr")))
LEFT JOIN WH_OWNER.I_DAN_SPECIALISTS DS ON
	((A.STORE_NBR = DS."Store Nbr")))
LEFT JOIN WH_OWNER.I_SN_CORP_SUPPLY_BY_CAITO SBC ON
	((A.STORE_NBR = SBC."SN Corp Supplied by Caito")))
LEFT JOIN WH_OWNER.I_ST_CLOUD_STORE SCS ON
	((A.STORE_NBR = SCS."St Cloud Stores")))
LEFT JOIN WH_OWNER.I_FAST_LANE_STORES FL ON
	((A.STORE_NBR = FL."Store Nbr")))
LEFT JOIN WH_OWNER.I_KIRN_STORES KIRN ON
	((A.STORE_NBR = KIRN."Store Nbr")))
LEFT JOIN WH_OWNER.I_KIRN_MAJOR_REMODELS KIRNM ON
	((A.STORE_NBR = KIRNM."Store Nbr")))
LEFT JOIN WH_OWNER.I_FRENCH_BREAD_STORES FBS ON
	((A.STORE_NBR = FBS."Store")))
LEFT JOIN WH_OWNER.I_KIRN_TOUCHUPS KIRNTU ON
	((A.STORE_NBR = KIRNTU."Store Nbr")))
LEFT JOIN WH_OWNER.I_KIRN_POSITIONED KIRNP ON
	((A.STORE_NBR = KIRNP."Store Nbr")))
LEFT JOIN WH_OWNER.I_KIRN_WEST_FOCUS KIRNW ON
	((A.STORE_NBR = KIRNW."Store Nbr")))
LEFT JOIN WH_OWNER.I_KIRN_FENTON KIRNF ON
	((A.STORE_NBR = KIRNF."Store Nbr")))
LEFT JOIN WH_OWNER.I_KIRN_DANS KIRND ON
	((A.STORE_NBR = KIRND."Store Nbr")))
LEFT JOIN WH_OWNER.I_KIRN_FARGO KIRNFA ON
	((A.STORE_NBR = KIRNFA."Store Nbr")))
LEFT JOIN WH_OWNER.I_KRIN_STORES_1580EXCLUDED KIRNEX4580 ON
	((A.STORE_NBR = KIRNEX4580."Store Nbr")))
LEFT JOIN WH_OWNER.I_SENIOR_DISCOUNT_VG SDVG ON
	((A.STORE_NBR = SDVG."Store Nbr")))
LEFT JOIN WH_OWNER.I_SENIOR_DISCOUNT_FF_NORTH SDFFN ON
	((A.STORE_NBR = SDFFN."Store Nbr")))
LEFT JOIN WH_OWNER.I_STORE_PRICE_ZONES PZ ON
	((A.STORE_NBR = PZ."Store ID")))
LEFT JOIN WH_OWNER.I_DISTRICT_SELL_THRU DST ON
	((A.DISTRICT_KEY = INT4(DST.DISTRICT))))
LEFT JOIN WH_OWNER.I_2YEAR_COMP_STORES CS2Y ON
	((A.STORE_NBR = CS2Y."Store Nbr")))
LEFT JOIN WH_OWNER.I_GEORGE_SPECIALISTS GS ON
	((A.STORE_NBR = GS."Store Nbr")))
LEFT JOIN WH_OWNER.I_STORE_CLOSED SC ON
	((A.STORE_NBR = SC."Store Nbr")))
LEFT JOIN WH_OWNER.I_STORE_CLUSTERS_MEAT_SEAFOOD SCMS ON
	((A.STORE_NBR = SCMS."Store Nbr")))
LEFT JOIN WH_OWNER.I_SUPERMARKET_STATE SS ON
	((A.STORE_NBR = SS."Store Nbr")))
WHERE
	(B.FORMAT_TYPE_DESC = 'Supermarket'::BPCHAR)
;

--V_CORPORATION
SELECT
	A.CORPORATION_ID AS "Corporation ID",
	A.CORPORATION_NAME AS "Corporation",
	A.CITY_NAME AS "City",
	A.STATE_CD AS "State",
	"SUBSTRING"(A.ZIP_CD,
	1,
	5) AS "Zip Code",
	CASE
		WHEN (N."Corporation ID" NOTNULL) THEN 'National Account'::"VARCHAR"
		ELSE 'Base Core'::"VARCHAR"
	END AS "Account Type",
	CASE
		WHEN (A.CORPORATION_NAME ~~ LIKE_ESCAPE('%SPARTANNASH%'::"VARCHAR",
		'\'::"VARCHAR")) THEN 'Corporate Store'::"VARCHAR"
		ELSE
		CASE
			WHEN (A.CORPORATION_NAME ~~ LIKE_ESCAPE('%MARTINS SUPER MARKET%'::"VARCHAR",
			'\'::"VARCHAR")) THEN 'Corporate Store'::"VARCHAR"
			ELSE
			CASE
				WHEN (N."Corporation ID" NOTNULL) THEN 'National Account'::"VARCHAR"
				ELSE 'Independent Store'::"VARCHAR"
			END
		END
	END AS "Store Type",
	CASE
		WHEN (KA."Corporation ID" NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Key Account",
	CASE
		WHEN (A.CORPORATION_NAME ~~ LIKE_ESCAPE('%MARTINS SUPER MARKET%'::"VARCHAR",
		'\'::"VARCHAR")) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Martin's Flg"
FROM
	((WH_OWNER.DC_CORPORATION A
LEFT JOIN WH_OWNER.I_NATIONAL_ACCTS N ON
	((A.CORPORATION_ID = N."Corporation ID")))
LEFT JOIN WH_OWNER.I_KEY_ACCOUNT KA ON
	((A.CORPORATION_ID = KA."Corporation ID")))
	;

--V_DC
SELECT
	A.FACILITY_ID AS "Facility ID",
	A.FACILITY_NAME AS "Facility Description",
	A.BUSINESS_UNIT AS "Business Unit",
	B.REGION_NAME AS "Region Description",
	CASE
		WHEN (((A.FACILITY_ID = 3)
		OR (A.FACILITY_ID = 8))
		OR (A.FACILITY_ID = 40)) THEN 'FARGO / ST. CLOUD / OMAHA'::BPCHAR
		ELSE A.FACILITY_NAME
	END AS "Facility Description (Produce & Floral)",
	D.DIVISION AS "Division"
FROM
	((WH_OWNER.DC_FACILITY A
LEFT JOIN WH_OWNER.DC_REGION B ON
	((A.REGION_ID = B.REGION_ID)))
LEFT JOIN WH_OWNER.I_DC_DIVISION D ON
	((A.FACILITY_ID = INT2(D."Facility ID"))))
	;
	

--V_DC_ITEM
SELECT
	A.FACILITY_ID AS "Facility ID",
	A.ITEM_NBR AS "DC Item",
	((BTRIM(("VARCHAR"(A.ITEM_NBR))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM(("VARCHAR"(A.FACILITY_ID))::VARCHAR(255))) AS "DC Item Key",
	A.UNIT_UPC_NBR AS "Item",
	A.BRAND_DESC AS "Brand",
	((BTRIM((A.ROOT_ITEM_DESC)::"VARCHAR") || ' - '::"VARCHAR") || BTRIM(("VARCHAR"(A.ITEM_NBR))::VARCHAR(255))) AS "Item Description",
	A.ITEM_SIZE_DESC AS "Size",
	A.CASE_PACK_QTY AS "Case Pack Quantity",
	A.MASTER_PACK_QTY AS "Master Pack Quantity",
	A.RETAIL_PACK_QTY AS "Retail Pack Quantity",
	A.VENDOR_NBR AS "Vendor ID",
	I.VENDOR_NAME AS "Vendor",
	I.MSTR_VENDOR_NAME AS "Master Vendor",
	I.VENDOR_STATUS_CD AS "Vendor Status",
	A.ITEM_RANK_CD AS "Item Rank Code",
	A.CATALOG_PRICE_AMT AS "Catalog Price",
	BTRIM(((BTRIM((D.FIRST_NM)::"VARCHAR") || ' '::"VARCHAR") || BTRIM((D.LAST_NM)::"VARCHAR"))) AS "Category Manager",
	B.MDSE_CLASS_NAME AS "Class",
	B.MDSE_CLASS_KEY AS "Class ID",
	E.MDSE_CATGY_NAME AS "Category",
	E.MDSE_CATGY_KEY AS "Category ID",
	F.MDSE_GRP_KEY AS "Group ID",
	F.MDSE_GRP_NAME AS "Group",
	G.DEPT_NAME AS "Department",
	G.DEPT_KEY AS "Department ID",
	H.DEPT_GRP_NAME AS "Department Group",
	H.DEPT_GRP_KEY AS "Department Group ID",
	A.PURCH_STATUS_CD AS "Purchase Status",
	A.LAST_SHIPPED_DATE AS "Last Shipped Date",
	A.CASE_UPC_NBR AS "Item Case",
	A.ITEM_SIZE_UOM_CD AS "Size UOM",
	DD.DIRECTOR AS "Director",
	CASE
		WHEN (K.BRAND_DESC NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Private Label Flg",
	CASE
		WHEN (S.UPC NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Supply Flg",
	CASE
		WHEN (COM."Commodity" NOTNULL) THEN COM."Commodity"
		WHEN ('Unassigned' NOTNULL) THEN 'Unassigned'::BPCHAR
		ELSE NULL::BPCHAR
	END AS "Commodity",
	TB."Promo / Revenue" AS "Tobacco Promo/Revenue",
	TB."CLASS" AS "Tobacco Class",
	A.BILLING_STATUS_CD AS "Billing Status",
	PIB."BUYER NUMBER" AS "Buyer Number",
	PIB."BUYER NAME" AS "Buyer Name",
	CASE
		WHEN (CBD.UPC NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "CBD Flg",
	CASE
		WHEN (ZZ.FACILITY_ID NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "I/O or Seasonal",
	CASE
		WHEN (X.ITEM_NBR NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "dh CPA List",
	A1.PROGRAM,
	DCF.FACILITY_NAME AS "Facility"
FROM
	((((((((((((((((((((WH_OWNER.DC_ITEM A
LEFT JOIN WH_OWNER.MDSE_CLASS B ON
	((A.MDSE_CLASS_KEY = B.MDSE_CLASS_KEY)))
LEFT JOIN WH_OWNER.MDSE_CLASS_MANAGER C ON
	((B.MDSE_CLASS_KEY = C.MDSE_CLASS_KEY)))
LEFT JOIN WH_OWNER.CATEGORY_MANAGER D ON
	((C.CATGY_MANAGER_KEY = D.CATGY_MANAGER_KEY)))
LEFT JOIN WH_OWNER.MDSE_CATEGORY E ON
	((B.MDSE_CATGY_KEY = E.MDSE_CATGY_KEY)))
LEFT JOIN WH_OWNER.MDSE_GROUP F ON
	((E.MDSE_GRP_KEY = F.MDSE_GRP_KEY)))
LEFT JOIN WH_OWNER.DEPARTMENT G ON
	((F.DEPT_KEY = G.DEPT_KEY)))
LEFT JOIN WH_OWNER.DEPARTMENT_GROUP H ON
	((H.DEPT_GRP_KEY = G.DEPT_GRP_KEY)))
LEFT JOIN WH_OWNER.DC_VENDOR I ON
	(((A.FACILITY_ID = I.FACILITY_ID)
		AND (A.VENDOR_NBR = I.VENDOR_NBR))))
LEFT JOIN WH_OWNER.I_DIRECTOR_DEPT DD ON
	((G.DEPT_NAME = DD.DEPARTMENT)))
JOIN WH_OWNER.V_ITEM_DC_SLS_LST_3FY J ON
	(((A.ITEM_NBR = J."DC Item")
		AND (A.FACILITY_ID = J."Facility ID"))))
LEFT JOIN WH_OWNER.I_PRIVATE_LABEL_CODES_WHS K ON
	(((A.BRAND_DESC)::"VARCHAR" = K.BRAND_DESC)))
LEFT JOIN WH_OWNER.V_COMMODITY COM ON
	(((A.FACILITY_ID = COM."Facility ID")
		AND (A.ITEM_NBR = COM."DC Item"))))
LEFT JOIN WH_OWNER.I_SUPPLY_UPC S ON
	((A.UNIT_UPC_NBR = "NUMERIC"(S.UPC))))
LEFT JOIN WH_OWNER.I_TOBACCO_PR_CLASS TB ON
	((A.UNIT_UPC_NBR = "NUMERIC"(TB.UPC))))
LEFT JOIN WH_OWNER.I_PRODUCE_ITEM_BUYER PIB ON
	(((A.ITEM_NBR = PIB."ITEM ID")
		AND (A.FACILITY_ID = PIB."FACILITY ID"))))
LEFT JOIN WH_OWNER.I_CBD_UPC CBD ON
	((A.UNIT_UPC_NBR = "NUMERIC"(CBD.UPC))))
LEFT JOIN WH_OWNER.I_DC_PROGRAMS A1 ON
	(((A.ITEM_NBR = A1."Order Code")
		AND (A.FACILITY_ID = A1."Facility ID"))))
LEFT JOIN (
	SELECT
		DC_ITEM.FACILITY_ID,
		DC_ITEM.ITEM_NBR
	FROM
		WH_OWNER.DC_ITEM
	WHERE
		((DC_ITEM.LOG_VAR_ITEM_DESC ~~ LIKE_ESCAPE('%/O%'::"VARCHAR",
		'\'::"VARCHAR"))
			OR (DC_ITEM.LOG_VAR_ITEM_DESC ~~ LIKE_ESCAPE('BTS-%'::"VARCHAR",
			'\'::"VARCHAR"))
				OR (DC_ITEM.LOG_VAR_ITEM_DESC ~~ LIKE_ESCAPE('H-%'::"VARCHAR",
				'\'::"VARCHAR"))
					OR (DC_ITEM.LOG_VAR_ITEM_DESC ~~ LIKE_ESCAPE('V-%'::"VARCHAR",
					'\'::"VARCHAR"))
						OR (DC_ITEM.LOG_VAR_ITEM_DESC ~~ LIKE_ESCAPE('SS-%'::"VARCHAR",
						'\'::"VARCHAR"))
							OR (DC_ITEM.LOG_VAR_ITEM_DESC ~~ LIKE_ESCAPE('E-%'::"VARCHAR",
							'\'::"VARCHAR"))
								OR (DC_ITEM.LOG_VAR_ITEM_DESC ~~ LIKE_ESCAPE('C-%'::"VARCHAR",
								'\'::"VARCHAR")))) ZZ ON
	(((A.FACILITY_ID = ZZ.FACILITY_ID)
		AND (A.ITEM_NBR = ZZ.ITEM_NBR))))
LEFT JOIN (
	SELECT
		DISTINCT A.FACILITY_ID,
		A.ITEM_NBR
	FROM
		(WH_OWNER.DC_ITEM A
	JOIN WH_OWNER.I_VOID_TARGET_UPC B ON
		((A.UNIT_UPC_NBR = "NUMERIC"(B.UPC))))) X ON
	(((A.ITEM_NBR = X.ITEM_NBR)
		AND (A.FACILITY_ID = X.FACILITY_ID))))
LEFT JOIN WH_OWNER.DC_FACILITY DCF ON
	((A.FACILITY_ID = DCF.FACILITY_ID)))
	;
	
--V_EXEC_DASH_WHS_CORP_GRP_WK_SLS
SELECT
	CORP.CORPORATION_ID AS "Corporation Key",
	A13.FACILITY_ID AS "Facility ID",
	((BTRIM(("VARCHAR"(GRP.MDSE_GRP_KEY))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM
	(CASE WHEN (K."Item" NOTNULL) THEN 'Y'::"VARCHAR"
	ELSE 'N'::"VARCHAR"
END)) AS "Group OB Key",
	A111.END_DT AS "Wk End Dt",
	SUM(A11.TOTAL_SALES_AMT) AS "Shipped Sales",
	SUM(A11.SHIPPED_QTY) AS "Shipped Cases",
	SUM(A11.EXT_MOVEMENT_WT) AS "Shipped Weight"
FROM
	(((((((((WH_OWNER.DC_SALES_HST A11
JOIN WH_OWNER.DC_CUSTOMER A12 ON
	(((A11.CUSTOMER_NBR = A12.CUSTOMER_NBR)
		AND (A11.FACILITY_ID = A12.FACILITY_ID))))
JOIN WH_OWNER.DC_ITEM A13 ON
	(((A11.FACILITY_ID = A13.FACILITY_ID)
		AND (A11.ITEM_NBR = A13.ITEM_NBR))))
LEFT JOIN WH_OWNER.V_PRIVATE_LABEL_UPC K ON
	((A13.UNIT_UPC_NBR = "NUMERIC"(K."Item"))))
JOIN WH_OWNER.MDSE_CLASS "CLASS" ON
	((A13.MDSE_CLASS_KEY = "CLASS".MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY "CATEGORY" ON
	(("CLASS".MDSE_CATGY_KEY = "CATEGORY".MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP GRP ON
	(("CATEGORY".MDSE_GRP_KEY = GRP.MDSE_GRP_KEY)))
JOIN WH_OWNER.FISCAL_DAY A18 ON
	((A11.TRANSACTION_DATE = A18.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK A111 ON
	((A18.FISCAL_WEEK_ID = A111.FISCAL_WEEK_ID)))
JOIN WH_OWNER.DC_CORPORATION CORP ON
	((A12.CORPORATION_ID = CORP.CORPORATION_ID)))
WHERE
	((A111.END_DT < DATE('now(0)'::"VARCHAR"))
		AND ((A111.END_DT >= (
		SELECT
			DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 903)
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
			AND (A111.END_DT <= (
			SELECT
				DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
					AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
GROUP BY
	CORP.CORPORATION_ID,
	A13.FACILITY_ID,
	((BTRIM(("VARCHAR"(GRP.MDSE_GRP_KEY))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM
	(CASE WHEN (K."Item" NOTNULL) THEN 'Y'::"VARCHAR"
	ELSE 'N'::"VARCHAR"
END)),
	A111.END_DT
	;
	

--V_FRESH_WEEKLY_RECAP_WHSE
((
SELECT
	(((BTRIM(("VARCHAR"(A13.ITEM_NBR))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM(("VARCHAR"(A13.FACILITY_ID))::VARCHAR(255))))::VARCHAR(513) AS "DC Item Key",
	A11.FACILITY_ID AS "Facility ID",
	A12.CORPORATION_ID AS "Corporation ID",
	A18.SALES_DT AS "Sales Dt",
	(SUM(A11.OUT_OF_STOCK_QTY))::NUMERIC(38,
	0) AS "Out of Stock Quantity",
	(SUM(A11.TOTAL_SALES_AMT))::NUMERIC(38,
	2) AS "Shipped Sales",
	(SUM(A11.ORDERED_QTY))::NUMERIC(38,
	0) AS "Ordered Cases",
	(SUM(A11.SHIPPED_QTY))::NUMERIC(38,
	0) AS "Shipped Cases",
	(SUM(A11.EXT_MOVEMENT_WT))::NUMERIC(38,
	2) AS "Shipped Weight"
FROM
	(((((((WH_OWNER.DC_SALES_HST A11
LEFT JOIN WH_OWNER.DC_CUSTOMER A12 ON
	(((A11.CUSTOMER_NBR = A12.CUSTOMER_NBR)
		AND (A11.FACILITY_ID = A12.FACILITY_ID))))
JOIN WH_OWNER.DC_ITEM A13 ON
	(((A11.FACILITY_ID = A13.FACILITY_ID)
		AND (A11.ITEM_NBR = A13.ITEM_NBR))))
JOIN WH_OWNER.MDSE_CLASS "CLASS" ON
	((A13.MDSE_CLASS_KEY = "CLASS".MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY "CATEGORY" ON
	(("CLASS".MDSE_CATGY_KEY = "CATEGORY".MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP GRP ON
	(("CATEGORY".MDSE_GRP_KEY = GRP.MDSE_GRP_KEY)))
JOIN WH_OWNER.FISCAL_DAY A18 ON
	((A11.TRANSACTION_DATE = A18.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK A111 ON
	((A18.FISCAL_WEEK_ID = A111.FISCAL_WEEK_ID)))
WHERE
	(((GRP.DEPT_KEY IN (20, 110, 30, 120, 70, 80))
		AND ((A111.END_DT = (
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 1))))
			OR (A111.END_DT = (
			SELECT
				DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 7))))))
		AND (A18.SALES_DT < DATE('now(0)'::"VARCHAR")))
GROUP BY
	((BTRIM(("VARCHAR"(A13.ITEM_NBR))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM(("VARCHAR"(A13.FACILITY_ID))::VARCHAR(255))),
	A11.FACILITY_ID,
	A12.CORPORATION_ID,
	A18.SALES_DT)
UNION ALL (
SELECT
(((BTRIM(("VARCHAR"(A13.ITEM_NBR))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM(("VARCHAR"(A13.FACILITY_ID))::VARCHAR(255))))::VARCHAR(513) AS "DC Item Key",
A11.FACILITY_ID AS "Facility ID",
A12.CORPORATION_ID AS "Corporation ID",
A11.TRANSACTION_DATE AS "Sales Dt",
(SUM(A11.OUT_OF_STOCK_QTY))::NUMERIC(38,
0) AS "Out of Stock Quantity",
(SUM(A11.TOTAL_SALES_AMT))::NUMERIC(38,
2) AS "Shipped Sales",
(SUM(A11.ORDERED_QTY))::NUMERIC(38,
0) AS "Ordered Cases",
(SUM(A11.SHIPPED_QTY))::NUMERIC(38,
0) AS "Shipped Cases",
(SUM(A11.EXT_MOVEMENT_WT))::NUMERIC(38,
2) AS "Shipped Weight"
FROM
(((((((WH_OWNER.DC_SALES_HST A11
LEFT JOIN WH_OWNER.DC_CUSTOMER A12 ON
(((A11.CUSTOMER_NBR = A12.CUSTOMER_NBR)
	AND (A11.FACILITY_ID = A12.FACILITY_ID))))
JOIN WH_OWNER.DC_ITEM A13 ON
(((A11.FACILITY_ID = A13.FACILITY_ID)
	AND (A11.ITEM_NBR = A13.ITEM_NBR))))
JOIN WH_OWNER.MDSE_CLASS "CLASS" ON
((A13.MDSE_CLASS_KEY = "CLASS".MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY "CATEGORY" ON
(("CLASS".MDSE_CATGY_KEY = "CATEGORY".MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP GRP ON
(("CATEGORY".MDSE_GRP_KEY = GRP.MDSE_GRP_KEY)))
JOIN WH_OWNER.FISCAL_DAY A18 ON
((A11.TRANSACTION_DATE = A18.LY_SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK A111 ON
((A18.FISCAL_WEEK_ID = A111.FISCAL_WEEK_ID)))
WHERE
((GRP.DEPT_KEY IN (20, 110, 30, 120, 70, 80))
	AND ((A111.END_DT = (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 1))))
		OR (A111.END_DT = (
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 7))))))
GROUP BY
((BTRIM(("VARCHAR"(A13.ITEM_NBR))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM(("VARCHAR"(A13.FACILITY_ID))::VARCHAR(255))),
A11.FACILITY_ID,
A12.CORPORATION_ID,
A11.TRANSACTION_DATE))
UNION ALL (
SELECT
(((BTRIM(("VARCHAR"(A13.ITEM_NBR))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM(("VARCHAR"(A13.FACILITY_ID))::VARCHAR(255))))::VARCHAR(513) AS "DC Item Key",
A11.FACILITY_ID AS "Facility ID",
A12.CORPORATION_ID AS "Corporation ID",
A11.TRANSACTION_DATE AS "Sales Dt",
(SUM(A11.OUT_OF_STOCK_QTY))::NUMERIC(38,
0) AS "Out of Stock Quantity",
(SUM(A11.TOTAL_SALES_AMT))::NUMERIC(38,
2) AS "Shipped Sales",
(SUM(A11.ORDERED_QTY))::NUMERIC(38,
0) AS "Ordered Cases",
(SUM(A11.SHIPPED_QTY))::NUMERIC(38,
0) AS "Shipped Cases",
(SUM(A11.EXT_MOVEMENT_WT))::NUMERIC(38,
2) AS "Shipped Weight"
FROM
(((((((WH_OWNER.DC_SALES_HST A11
LEFT JOIN WH_OWNER.DC_CUSTOMER A12 ON
(((A11.CUSTOMER_NBR = A12.CUSTOMER_NBR)
	AND (A11.FACILITY_ID = A12.FACILITY_ID))))
JOIN WH_OWNER.DC_ITEM A13 ON
(((A11.FACILITY_ID = A13.FACILITY_ID)
	AND (A11.ITEM_NBR = A13.ITEM_NBR))))
JOIN WH_OWNER.MDSE_CLASS "CLASS" ON
((A13.MDSE_CLASS_KEY = "CLASS".MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY "CATEGORY" ON
(("CLASS".MDSE_CATGY_KEY = "CATEGORY".MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP GRP ON
(("CATEGORY".MDSE_GRP_KEY = GRP.MDSE_GRP_KEY)))
JOIN (
SELECT
	A.FISCAL_WEEK_ID,
	A.SALES_DT,
	A.LY_SALES_DT,
	B.LY_SALES_DT AS LLY_SALES_DT
FROM
	(WH_OWNER.FISCAL_DAY A
JOIN WH_OWNER.FISCAL_DAY B ON
	((B.SALES_DT = A.LY_SALES_DT)))) FD ON
((A11.TRANSACTION_DATE = FD.LLY_SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK A111 ON
((FD.FISCAL_WEEK_ID = A111.FISCAL_WEEK_ID)))
WHERE
((GRP.DEPT_KEY IN (20, 110, 30, 120, 70, 80))
	AND ((A111.END_DT = (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 1))))
		OR (A111.END_DT = (
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 7))))))
GROUP BY
((BTRIM(("VARCHAR"(A13.ITEM_NBR))::VARCHAR(255)) || ' - '::"VARCHAR") || BTRIM(("VARCHAR"(A13.FACILITY_ID))::VARCHAR(255))),
A11.FACILITY_ID,
A12.CORPORATION_ID,
A11.TRANSACTION_DATE)
;

--V_COMP_STORE_EXECUTIVE
SELECT
	DISTINCT ((BTRIM("VARCHAR"(TY.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(TY.SALES_DT))) AS "Comp Store Key",
	CASE
		WHEN (TY.COMP_STATUS_KEY = 1) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Comp Store",
	CASE
		WHEN (NEXT_YEAR.COMP_STATUS_KEY = 1) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "Comp Store NY"
FROM
	((WH_OWNER.I_DT_TY_LY C
JOIN (
	SELECT
		A11.SALES_DT,
		L.STORE_NBR,
		A11.SALES_LINE_ID,
		MAX(A11.COMP_STATUS_KEY) AS COMP_STATUS_KEY
	FROM
		(WH_OWNER.COMP_DAY_LN_TNDR A11
	JOIN WH_OWNER.LINE L ON
		((L.SALES_LINE_ID = A11.SALES_LINE_ID)))
	WHERE
		(A11.SALES_DT > (DATE('now(0)'::"VARCHAR") - 903))
	GROUP BY
		A11.SALES_DT,
		L.STORE_NBR,
		A11.SALES_LINE_ID) TY ON
	((TY.SALES_DT = C.LY_SALES_DT)))
LEFT JOIN (
	SELECT
		A11.SALES_DT,
		L.STORE_NBR,
		A11.SALES_LINE_ID,
		MAX(A11.COMP_STATUS_KEY) AS COMP_STATUS_KEY
	FROM
		(WH_OWNER.COMP_DAY_LN_TNDR A11
	JOIN WH_OWNER.LINE L ON
		((L.SALES_LINE_ID = A11.SALES_LINE_ID)))
	WHERE
		(A11.SALES_DT > (DATE('now(0)'::"VARCHAR") - 1500))
	GROUP BY
		A11.SALES_DT,
		L.STORE_NBR,
		A11.SALES_LINE_ID) NEXT_YEAR ON
	(((C.SALES_DT = NEXT_YEAR.SALES_DT)
		AND (TY.STORE_NBR = NEXT_YEAR.STORE_NBR))))
	;


--V_EVENT_CODE
SELECT
	A.EVENT_CD AS "Event Code",
	A.EVENT_CD_DESC AS "Event Description",
	B.EVENT_CD_LARGE AS "Event Large",
	CASE
		WHEN ((A.EVENT_CD = 'ADS'::"VARCHAR")
		OR (A.EVENT_CD = 'ADW'::"VARCHAR")) THEN 'Ad Mkdn'::"VARCHAR"
		ELSE
		CASE
			WHEN ((((A.EVENT_CD = 'TPRN'::"VARCHAR")
			OR (A.EVENT_CD = 'TPRW'::"VARCHAR"))
			OR ((A.EVENT_CD = 'TPRL'::"VARCHAR")
			OR (A.EVENT_CD = 'WVBV'::"VARCHAR")))
			OR ((A.EVENT_CD = 'RPED'::"VARCHAR")
			OR (A.EVENT_CD = 'PFRZ'::"VARCHAR"))) THEN 'TPR Mkdn'::"VARCHAR"
			ELSE
			CASE
				WHEN (A.EVENT_CD = 'ISMD'::"VARCHAR") THEN 'In-Store Mkdn'::"VARCHAR"
				ELSE
				CASE
					WHEN ((((A.EVENT_CD = 'DISC'::"VARCHAR")
					OR (A.EVENT_CD = 'MARK'::"VARCHAR"))
					OR ((A.EVENT_CD = 'RST'::"VARCHAR")
					OR (A.EVENT_CD = 'UNKN'::"VARCHAR")))
					OR (((A.EVENT_CD = 'REG'::"VARCHAR")
					OR (A.EVENT_CD = 'WINE'::"VARCHAR"))
					OR ((A.EVENT_CD = 'BIG '::"VARCHAR")
					OR (A.EVENT_CD = 'INST'::"VARCHAR")))) THEN 'Other Mkdn'::"VARCHAR"
					ELSE
					CASE
						WHEN (A.EVENT_CD = 'LOY '::"VARCHAR") THEN 'Loyalty Mkdn'::"VARCHAR"
						ELSE NULL::"VARCHAR"
					END
				END
			END
		END
	END AS "Markdown Category"
FROM
	(WH_OWNER.EVENT_CODE A
JOIN WH_OWNER.I_EVENT_CODE_LARGE B ON
	((A.EVENT_CD = B.EVENT_CD)))
;

--V_EXEC_DASH_STO_WK_GRP_EBT_SLS
SELECT
	((BTRIM("VARCHAR"(C.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))) AS "Comp Store Key",
	C.STORE_NBR AS "Store Nbr",
	((BTRIM("VARCHAR"(G.MDSE_GRP_KEY)) || ' - '::"VARCHAR") || BTRIM
	(CASE WHEN (I.ITEM_BRAND_CD NOTNULL) THEN 'Y'::"VARCHAR"
	ELSE 'N'::"VARCHAR"
END)) AS "Group OB Key",
	D.END_DT AS "Wk End Dt",
	SUM(A.TOTAL_SALES_AMT) AS "Sales Dollars (EBT)"
FROM
	(((((((((((WH_OWNER.RSAL_DY_LN_ITM_TRN A
JOIN (
	SELECT
		A.SALES_DT,
		B.SALES_LINE_ID,
		A.REGISTER_ID,
		A.TRANS_NBR
	FROM
		(WH_OWNER.I_EBT_TRANSACTIONS A
	JOIN WH_OWNER.LINE B ON
		((A.STORE_NBR = B.STORE_NBR)))) A1 ON
	(((((A1.SALES_DT = A.SALES_DT)
		AND ((A1.SALES_LINE_ID)::"VARCHAR" = A.SALES_LINE_ID))
		AND (A1.REGISTER_ID = INT4(A.REGISTER_ID)))
		AND (A1.TRANS_NBR = A.TRANS_NBR))))
JOIN WH_OWNER.MDSE_ITEM B ON
	((A.ITEM_ID = B.ITEM_ID)))
JOIN WH_OWNER.LINE C ON
	((A.SALES_LINE_ID = (C.SALES_LINE_ID)::"VARCHAR")))
JOIN WH_OWNER.FISCAL_DAY C1 ON
	((A.SALES_DT = C1.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK D ON
	((C1.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
JOIN WH_OWNER.MDSE_CLASS E ON
	((B.MDSE_CLASS_KEY = E.MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY F ON
	((E.MDSE_CATGY_KEY = F.MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP G ON
	((F.MDSE_GRP_KEY = G.MDSE_GRP_KEY)))
JOIN (
	SELECT
		DISTINCT ITEM_BRAND.ITEM_BRAND_CD
	FROM
		WH_OWNER.ITEM_BRAND) H ON
	((B.ITEM_BRAND_CD = H.ITEM_BRAND_CD)))
LEFT JOIN WH_OWNER.I_PRIVATE_LABEL_CODES I ON
	(((H.ITEM_BRAND_CD)::"VARCHAR" = I.ITEM_BRAND_CD)))
JOIN WH_OWNER.I_EVENT_CODE_LARGE K ON
	((A.EVENT_CD = K.EVENT_CD)))
WHERE
	((((C.CUST_STATUS_KEY < 3)
		AND ((D.END_DT >= (
		SELECT
			DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 903)
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
			AND (D.END_DT <= (
			SELECT
				DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
					AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
		AND (C.FORMAT_TYPE_ID IN ('SUPERMKT  '::BPCHAR)))
		AND (C.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))
GROUP BY
	((BTRIM("VARCHAR"(C.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))),
	C.STORE_NBR,
	((BTRIM("VARCHAR"(G.MDSE_GRP_KEY)) || ' - '::"VARCHAR") || BTRIM
	(CASE WHEN (I.ITEM_BRAND_CD NOTNULL) THEN 'Y'::"VARCHAR"
	ELSE 'N'::"VARCHAR"
END)),
	D.END_DT
;

--V_EXEC_DASH_STO_WK_GRP_ECOM_SLS
SELECT
	((BTRIM("VARCHAR"(C.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))) AS "Comp Store Key",
	C.STORE_NBR AS "Store Nbr",
	((BTRIM("VARCHAR"(G.MDSE_GRP_KEY)) || ' - '::"VARCHAR") || BTRIM
	(CASE WHEN (I.ITEM_BRAND_CD NOTNULL) THEN 'Y'::"VARCHAR"
	ELSE 'N'::"VARCHAR"
END)) AS "Group OB Key",
	D.END_DT AS "Wk End Dt",
	SUM(A.TOTAL_SALES_AMT) AS "Sales Dollars (eComm)",
	SUM(CASE WHEN (K.EVENT_TYPE = 'Promotion'::"VARCHAR") THEN A.TOTAL_SALES_AMT ELSE '0'::NUMERIC END) AS "Sales Dollars Promo (eComm)",
	SUM(A.TOTAL_SALES_QTY) AS "Sales Quantity (eComm)",
	SUM(CASE WHEN (K.EVENT_TYPE = 'Promotion'::"VARCHAR") THEN A.TOTAL_SALES_QTY ELSE '0'::NUMERIC END) AS "Sales Quantity Promo (eComm)",
	SUM(A.TOTAL_SALES_WGT) AS "Sales Weight (eComm)",
	SUM(CASE WHEN (K.EVENT_TYPE = 'Promotion'::"VARCHAR") THEN A.TOTAL_SALES_WGT ELSE '0'::NUMERIC END) AS "Sales Weight Promo (eComm)"
FROM
	((((((((((WH_OWNER.RSAL_DY_LN_ITM_TRN A
JOIN WH_OWNER.MDSE_ITEM B ON
	((A.ITEM_ID = B.ITEM_ID)))
JOIN WH_OWNER.LINE C ON
	((A.SALES_LINE_ID = (C.SALES_LINE_ID)::"VARCHAR")))
JOIN WH_OWNER.FISCAL_DAY C1 ON
	((A.SALES_DT = C1.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK D ON
	((C1.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
JOIN WH_OWNER.MDSE_CLASS E ON
	((B.MDSE_CLASS_KEY = E.MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY F ON
	((E.MDSE_CATGY_KEY = F.MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP G ON
	((F.MDSE_GRP_KEY = G.MDSE_GRP_KEY)))
JOIN (
	SELECT
		DISTINCT ITEM_BRAND.ITEM_BRAND_CD
	FROM
		WH_OWNER.ITEM_BRAND) H ON
	((B.ITEM_BRAND_CD = H.ITEM_BRAND_CD)))
LEFT JOIN WH_OWNER.I_PRIVATE_LABEL_CODES I ON
	(((H.ITEM_BRAND_CD)::"VARCHAR" = I.ITEM_BRAND_CD)))
JOIN WH_OWNER.I_EVENT_CODE_LARGE K ON
	((A.EVENT_CD = K.EVENT_CD)))
WHERE
	(((((A.REGISTER_ID = '045'::"VARCHAR")
		AND (C.CUST_STATUS_KEY < 3))
		AND ((D.END_DT >= (
		SELECT
			DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 903)
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
			AND (D.END_DT <= (
			SELECT
				DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
					AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
		AND (C.FORMAT_TYPE_ID IN ('SUPERMKT  '::BPCHAR)))
		AND (C.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))
GROUP BY
	((BTRIM("VARCHAR"(C.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))),
	C.STORE_NBR,
	((BTRIM("VARCHAR"(G.MDSE_GRP_KEY)) || ' - '::"VARCHAR") || BTRIM
	(CASE WHEN (I.ITEM_BRAND_CD NOTNULL) THEN 'Y'::"VARCHAR"
	ELSE 'N'::"VARCHAR"
END)),
	D.END_DT
;

--V_EXEC_DASH_STO_WK_GRP_ECOM_TRN
SELECT
	((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))) AS "Comp Store Key",
	B.STORE_NBR AS "Store Nbr",
	D.END_DT AS "Wk End Dt",
	COUNT(DISTINCT ((((((((BTRIM("VARCHAR"(C.SALES_DT)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(A.LOYALTY_CARD_NBR))) || ' - '::"VARCHAR") || BTRIM((B.SALES_LINE_ID)::"VARCHAR")) || ' - '::"VARCHAR") || BTRIM(A.REGISTER_ID)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(A.TRANS_NBR)))) AS "Transactions (FL)"
FROM
	((((((((WH_OWNER.RSAL_DY_LN_ITM_TRN A
JOIN WH_OWNER.LINE B ON
	((A.SALES_LINE_ID = (B.SALES_LINE_ID)::"VARCHAR")))
JOIN WH_OWNER.FISCAL_DAY C ON
	((A.SALES_DT = C.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK D ON
	((C.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
JOIN WH_OWNER.MDSE_ITEM E ON
	((A.ITEM_ID = E.ITEM_ID)))
JOIN WH_OWNER.MDSE_CLASS F ON
	((E.MDSE_CLASS_KEY = F.MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY G ON
	((F.MDSE_CATGY_KEY = G.MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP H ON
	((H.MDSE_GRP_KEY = G.MDSE_GRP_KEY)))
JOIN WH_OWNER.MKTG_CHAIN L ON
	((B.MKTG_CHAIN_ID = L.MKTG_CHAIN_ID)))
WHERE
	((((D.END_DT >= (
	SELECT
		DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 903)
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
		AND (D.END_DT <= (
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= DATE('now(0)'::"VARCHAR"))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") + 6))))))
		AND (B.FORMAT_TYPE_ID = 'SUPERMKT'::BPCHAR))
		AND (A.REGISTER_ID = '045'::"VARCHAR"))
GROUP BY
	((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))),
	B.STORE_NBR,
	D.END_DT
;

--V_EXEC_DASH_STO_WK_TTL_TRN
SELECT
	((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))) AS "Comp Store Key",
	B.STORE_NBR AS "Store Nbr",
	D.END_DT AS "Wk End Dt",
	H.DEPT_KEY AS "Department Key",
	COUNT(DISTINCT ((((((((BTRIM("VARCHAR"(C.SALES_DT)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(A.LOYALTY_CARD_NBR))) || ' - '::"VARCHAR") || BTRIM((B.SALES_LINE_ID)::"VARCHAR")) || ' - '::"VARCHAR") || BTRIM(A.REGISTER_ID)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(A.TRANS_NBR)))) AS "Transactions"
FROM
	((((((((WH_OWNER.RSAL_DY_LN_ITM_TRN A
JOIN WH_OWNER.LINE B ON
	((A.SALES_LINE_ID = (B.SALES_LINE_ID)::"VARCHAR")))
JOIN WH_OWNER.FISCAL_DAY C ON
	((A.SALES_DT = C.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK D ON
	((C.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
JOIN WH_OWNER.MDSE_ITEM E ON
	((A.ITEM_ID = E.ITEM_ID)))
JOIN WH_OWNER.MDSE_CLASS F ON
	((E.MDSE_CLASS_KEY = F.MDSE_CLASS_KEY)))
JOIN WH_OWNER.MDSE_CATEGORY G ON
	((F.MDSE_CATGY_KEY = G.MDSE_CATGY_KEY)))
JOIN WH_OWNER.MDSE_GROUP H ON
	((H.MDSE_GRP_KEY = G.MDSE_GRP_KEY)))
JOIN WH_OWNER.MKTG_CHAIN L ON
	((B.MKTG_CHAIN_ID = L.MKTG_CHAIN_ID)))
WHERE
	((((D.END_DT >= (
	SELECT
		DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 903)
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
		AND (D.END_DT <= (
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= DATE('now(0)'::"VARCHAR"))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") + 6))))))
		AND (B.FORMAT_TYPE_ID = 'SUPERMKT'::BPCHAR))
		AND (H.DEPT_KEY IN (110, 80, 70, 120, 30, 20, 250, 40, 10, 50, 60, 13, 90, 15, 41, 12, 11)))
GROUP BY
	((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(D.END_DT))),
	B.STORE_NBR,
	D.END_DT,
	H.DEPT_KEY
;

--V_EXEC_DASH_TTL_WK_ECOM_HH
SELECT
	A."Household ID",
	A."Wk End Dt",
	A."Store Nbr",
	CASE
		WHEN (((
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))) - A."First Purchase Date") <= 7) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "New Household"
FROM
	(
	SELECT
		A17.HOUSEHOLD_KEY AS "Household ID",
		A16.END_DT AS "Wk End Dt",
		A15.STORE_NBR AS "Store Nbr",
		MIN(A17.FIRST_PURCH_DATE) AS "First Purchase Date"
	FROM
		((((((WH_OWNER.RSAL_DY_LN_ITM_TRN A11
	JOIN WH_OWNER.MDSE_ITEM A12 ON
		((A11.ITEM_ID = A12.ITEM_ID)))
	JOIN WH_OWNER.MDSE_CLASS A13 ON
		((A12.MDSE_CLASS_KEY = A13.MDSE_CLASS_KEY)))
	JOIN WH_OWNER.FISCAL_DAY A14 ON
		((A11.SALES_DT = A14.SALES_DT)))
	JOIN WH_OWNER.LINE A15 ON
		((A11.SALES_LINE_ID = (A15.SALES_LINE_ID)::"VARCHAR")))
	JOIN WH_OWNER.FISCAL_WEEK A16 ON
		((A14.FISCAL_WEEK_ID = A16.FISCAL_WEEK_ID)))
	JOIN WH_OWNER.LOYALTY_CARD A17 ON
		((A11.LOYALTY_CARD_NBR = A17.LOYALTY_CARD_NBR)))
	WHERE
		(((((((A15.CUST_STATUS_KEY < 3)
			AND (A15.FORMAT_TYPE_ID <> 'WHSE'::BPCHAR))
			AND (A11.REGISTER_ID = '045'::"VARCHAR"))
			AND ((A16.END_DT >= (
			SELECT
				DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 903)
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
					AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
				AND (A16.END_DT <= (
				SELECT
					DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
				FROM
					WH_OWNER.V_FISCAL_CALENDAR
				WHERE
					((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
						AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
			AND (A15.FORMAT_TYPE_ID IN ('SUPERMKT  '::BPCHAR)))
			AND (A15.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))
			AND (A17.HOUSEHOLD_KEY > 0))
	GROUP BY
		A17.HOUSEHOLD_KEY,
		A16.END_DT,
		A15.STORE_NBR) A
	;

--V_EXEC_DASH_TTL_WK_HH
SELECT
	A."Household ID",
	A."Wk End Dt",
	A."Store Nbr",
	CASE
		WHEN (((
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))) - A."First Purchase Date") <= 7) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "New Household"
FROM
	(
	SELECT
		A17.HOUSEHOLD_KEY AS "Household ID",
		A16.END_DT AS "Wk End Dt",
		A15.STORE_NBR AS "Store Nbr",
		MIN(A17.FIRST_PURCH_DATE) AS "First Purchase Date"
	FROM
		((((((WH_OWNER.RSAL_DY_LN_ITM_TRN A11
	JOIN WH_OWNER.MDSE_ITEM A12 ON
		((A11.ITEM_ID = A12.ITEM_ID)))
	JOIN WH_OWNER.MDSE_CLASS A13 ON
		((A12.MDSE_CLASS_KEY = A13.MDSE_CLASS_KEY)))
	JOIN WH_OWNER.FISCAL_DAY A14 ON
		((A11.SALES_DT = A14.SALES_DT)))
	JOIN WH_OWNER.LINE A15 ON
		((A11.SALES_LINE_ID = (A15.SALES_LINE_ID)::"VARCHAR")))
	JOIN WH_OWNER.FISCAL_WEEK A16 ON
		((A14.FISCAL_WEEK_ID = A16.FISCAL_WEEK_ID)))
	JOIN WH_OWNER.LOYALTY_CARD A17 ON
		((A11.LOYALTY_CARD_NBR = A17.LOYALTY_CARD_NBR)))
	WHERE
		((((((A15.CUST_STATUS_KEY < 3)
			AND (A15.FORMAT_TYPE_ID <> 'WHSE'::BPCHAR))
			AND ((A16.END_DT >= (
			SELECT
				DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 903)
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
					AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
				AND (A16.END_DT <= (
				SELECT
					DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
				FROM
					WH_OWNER.V_FISCAL_CALENDAR
				WHERE
					((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
						AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
			AND (A15.FORMAT_TYPE_ID IN ('SUPERMKT  '::BPCHAR)))
			AND (A15.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))
			AND (A17.HOUSEHOLD_KEY > 0))
	GROUP BY
		A17.HOUSEHOLD_KEY,
		A16.END_DT,
		A15.STORE_NBR) A
		;
		
	
--V_FL_STORE
SELECT
	((BTRIM("VARCHAR"(A."Store Nbr")) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(A."Wk End Dt"))) AS "FL Store Key",
	CASE
		WHEN (B."Store Nbr" NOTNULL) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS "FL Store"
FROM
	((
	SELECT
		C.STORE_NBR AS "Store Nbr",
		D.END_DT AS "Wk End Dt"
	FROM
		(WH_OWNER.LINE C
	CROSS JOIN WH_OWNER.FISCAL_WEEK D)
	WHERE
		((((C.CUST_STATUS_KEY < 3)
			AND ((D.END_DT >= (
			SELECT
				DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 721)
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
					AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
				AND (D.END_DT <= (
				SELECT
					DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
				FROM
					WH_OWNER.V_FISCAL_CALENDAR
				WHERE
					((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
						AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))))
			AND (C.FORMAT_TYPE_ID IN ('SUPERMKT  '::BPCHAR)))
			AND (C.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))) A
LEFT JOIN ((
	SELECT
		DISTINCT D.END_DT AS "Wk End Dt",
		B.STORE_NBR AS "Store Nbr"
	FROM
		(((WH_OWNER.RSAL_DY_LN_ITM_TRN A
	JOIN WH_OWNER.LINE B ON
		((A.SALES_LINE_ID = (B.SALES_LINE_ID)::"VARCHAR")))
	JOIN WH_OWNER.FISCAL_DAY C ON
		((A.SALES_DT = C.SALES_DT)))
	JOIN WH_OWNER.FISCAL_WEEK D ON
		((C.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
	WHERE
		(((D.END_DT >= (
		SELECT
			DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 721)
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
			AND (D.END_DT <= (
			SELECT
				DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
			FROM
				WH_OWNER.V_FISCAL_CALENDAR
			WHERE
				((V_FISCAL_CALENDAR."Wk End Dt" >= DATE('now(0)'::"VARCHAR"))
					AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") + 6))))))
			AND (A.REGISTER_ID = '045'::"VARCHAR")))
UNION (
SELECT
	DISTINCT (D.END_DT - 364) AS "Wk End Dt",
	B.STORE_NBR AS "Store Nbr"
FROM
	(((WH_OWNER.RSAL_DY_LN_ITM_TRN A
JOIN WH_OWNER.LINE B ON
	((A.SALES_LINE_ID = (B.SALES_LINE_ID)::"VARCHAR")))
JOIN WH_OWNER.FISCAL_DAY C ON
	((A.SALES_DT = C.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK D ON
	((C.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
WHERE
	(((D.END_DT >= (
	SELECT
		DISTINCT (V_FISCAL_CALENDAR."Wk End Dt" - 721)
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
		AND (D.END_DT <= (
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			((V_FISCAL_CALENDAR."Wk End Dt" >= DATE('now(0)'::"VARCHAR"))
				AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") + 6))))))
		AND (A.REGISTER_ID = '045'::"VARCHAR")))) B ON
	(((A."Store Nbr" = B."Store Nbr")
		AND (A."Wk End Dt" = B."Wk End Dt"))))
		;
		
	--V_EXEC_DASH_MKT_SHR
SELECT
	CASE
		WHEN (A."Pri Rem" NOTNULL) THEN A."Pri Rem"
		WHEN (B."Pri Rem" NOTNULL) THEN B."Pri Rem"
		ELSE NULL::"VARCHAR"
	END AS "Pri Rem",
	CASE
		WHEN (A."Market" NOTNULL) THEN A."Market"
		WHEN (B."Market" NOTNULL) THEN B."Market"
		ELSE NULL::"VARCHAR"
	END AS "Market",
	CASE
		WHEN (A."Wk End Dt" NOTNULL) THEN A."Wk End Dt"
		WHEN (B."Wk End Dt" NOTNULL) THEN B."Wk End Dt"
		ELSE NULL::DATE
	END AS "Wk End Dt",
	CASE
		WHEN (A."Sales" NOTNULL) THEN A."Sales"
		WHEN (0 NOTNULL) THEN '0'::NUMERIC
		ELSE NULL::"NUMERIC"
	END AS "Sales",
	CASE
		WHEN (A."Units" NOTNULL) THEN A."Units"
		WHEN (0 NOTNULL) THEN '0'::NUMERIC
		ELSE NULL::"NUMERIC"
	END AS "Units",
	CASE
		WHEN (B."Sales a" NOTNULL) THEN B."Sales a"
		WHEN (0 NOTNULL) THEN '0'::NUMERIC
		ELSE NULL::"NUMERIC"
	END AS "Sales a",
	CASE
		WHEN (B."Units" NOTNULL) THEN B."Units"
		WHEN (0 NOTNULL) THEN '0'::NUMERIC
		ELSE NULL::"NUMERIC"
	END AS "Units a",
	CASE
		WHEN (B."Any Promo Sales" NOTNULL) THEN B."Any Promo Sales"
		WHEN (0 NOTNULL) THEN '0'::NUMERIC
		ELSE NULL::"NUMERIC"
	END AS "Any Promo Sales",
	CASE
		WHEN (B."Any Promo Units" NOTNULL) THEN B."Any Promo Units"
		WHEN (0 NOTNULL) THEN '0'::NUMERIC
		ELSE NULL::"NUMERIC"
	END AS "Any Promo Units"
FROM
	((
	SELECT
		CASE
			WHEN (I_EXEC_DASH_MKT_SHR."Market" ~~ LIKE_ESCAPE('%_REM'::"VARCHAR",
			'\'::"VARCHAR")) THEN 'REM'::"VARCHAR"
			ELSE 'PRI'::"VARCHAR"
		END AS "Pri Rem",
		CASE
			WHEN (I_EXEC_DASH_MKT_SHR."Market" ~~ LIKE_ESCAPE('%West%'::"VARCHAR",
			'\'::"VARCHAR")) THEN 'West'::"VARCHAR"
			ELSE
			CASE
				WHEN (I_EXEC_DASH_MKT_SHR."Market" ~~ LIKE_ESCAPE('%Michigan%'::"VARCHAR",
				'\'::"VARCHAR")) THEN 'Michigan'::"VARCHAR"
				ELSE 'Martins'::"VARCHAR"
			END
		END AS "Market",
		I_EXEC_DASH_MKT_SHR."Week" AS "Wk End Dt",
		I_EXEC_DASH_MKT_SHR."Sales",
		I_EXEC_DASH_MKT_SHR."Units"
	FROM
		WH_OWNER.I_EXEC_DASH_MKT_SHR) A
FULL JOIN (
	SELECT
		CASE
			WHEN (I_EXEC_DASH_PROMO_PCT."Market" ~~ LIKE_ESCAPE('%Rem%'::"VARCHAR",
			'\'::"VARCHAR")) THEN 'REM'::"VARCHAR"
			ELSE 'PRI'::"VARCHAR"
		END AS "Pri Rem",
		CASE
			WHEN (I_EXEC_DASH_PROMO_PCT."Market" ~~ LIKE_ESCAPE('%West%'::"VARCHAR",
			'\'::"VARCHAR")) THEN 'West'::"VARCHAR"
			ELSE
			CASE
				WHEN (I_EXEC_DASH_PROMO_PCT."Market" ~~ LIKE_ESCAPE('%Michigan%'::"VARCHAR",
				'\'::"VARCHAR")) THEN 'Michigan'::"VARCHAR"
				ELSE 'Martins'::"VARCHAR"
			END
		END AS "Market",
		I_EXEC_DASH_PROMO_PCT."Week" AS "Wk End Dt",
		I_EXEC_DASH_PROMO_PCT."Sales" AS "Sales a",
		I_EXEC_DASH_PROMO_PCT."Units",
		I_EXEC_DASH_PROMO_PCT."Any Promo Sales",
		I_EXEC_DASH_PROMO_PCT."Any Promo Units"
	FROM
		WH_OWNER.I_EXEC_DASH_PROMO_PCT) B ON
	((((A."Pri Rem" = B."Pri Rem")
		AND (A."Market" = B."Market"))
		AND (A."Wk End Dt" = B."Wk End Dt"))))
		;
		
--V_FISCAL_PERIOD
SELECT
	FISCAL_PERIOD.FISCAL_PERIOD_ID,
	FISCAL_PERIOD.FISCAL_QUARTER_ID,
	FISCAL_PERIOD.FISCAL_PERIOD_NBR,
	FISCAL_PERIOD.START_DT,
	FISCAL_PERIOD.END_DT,
	FISCAL_PERIOD.PREVIOUS_PERIOD_ID
FROM
	WH_OWNER.FISCAL_PERIOD
	;
	

--V_PROD_DEPT
SELECT
	DISTINCT D.DEPT_KEY,
	D.DEPT_NAME,
	CASE
		WHEN (((((D.DEPT_KEY = 60)
		OR (D.DEPT_KEY = 10))
		OR ((D.DEPT_KEY = 12)
		OR (D.DEPT_KEY = 13)))
		OR (((D.DEPT_KEY = 41)
		OR (D.DEPT_KEY = 11))
		OR ((D.DEPT_KEY = 40)
		OR (D.DEPT_KEY = 50))))
		OR ((D.DEPT_KEY = 90)
		OR (D.DEPT_KEY = 15))) THEN 'CENTER STORE'::"VARCHAR"
		WHEN ((((D.DEPT_KEY = 80)
		OR (D.DEPT_KEY = 110))
		OR ((D.DEPT_KEY = 30)
		OR (D.DEPT_KEY = 20)))
		OR ((D.DEPT_KEY = 120)
		OR (D.DEPT_KEY = 70))) THEN 'FRESH'::"VARCHAR"
		ELSE 'MISC'::"VARCHAR"
	END AS DEPT_GROUP,
	CASE
		WHEN (((((D.DEPT_KEY = 70)
		OR (D.DEPT_KEY = 60))
		OR ((D.DEPT_KEY = 80)
		OR (D.DEPT_KEY = 90)))
		OR (((D.DEPT_KEY = 40)
		OR (D.DEPT_KEY = 10))
		OR ((D.DEPT_KEY = 11)
		OR (D.DEPT_KEY = 41))))
		OR (((D.DEPT_KEY = 20)
		OR (D.DEPT_KEY = 30))
		OR ((D.DEPT_KEY = 120)
		OR (D.DEPT_KEY = 110)))) THEN 'Y'::"VARCHAR"
		ELSE 'N'::"VARCHAR"
	END AS OB_DEPT,
	G.DEPT_GRP_NAME
FROM
	(WH_OWNER.DEPARTMENT D
JOIN WH_OWNER.DEPARTMENT_GROUP G ON
	((D.DEPT_GRP_KEY = G.DEPT_GRP_KEY)))
	;
	
--V_STORE_SPECIALIST
SELECT
	A."Store",
	A.SPECIALIST AS "Specialist",
	A.DEPARTMENT AS "Department"
FROM
	WH_OWNER.I_STORE_SPECIALIST A
;


--V_ITEM_DC_SLS_LST_3FY
SELECT
	A11.ITEM_NBR AS "DC Item",
	A11.FACILITY_ID AS "Facility ID",
	SUM(A11.TOTAL_SALES_AMT) AS "Shipped Sales"
FROM
	((WH_OWNER.DC_SALES_HST A11
JOIN WH_OWNER.FISCAL_DAY A18 ON
	((A11.TRANSACTION_DATE = A18.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK A111 ON
	((A18.FISCAL_WEEK_ID = A111.FISCAL_WEEK_ID)))
WHERE
	((A18.FISCAL_YEAR_ID >= (
	SELECT
		DISTINCT (FISCAL_DAY.FISCAL_YEAR_ID - 2)
	FROM
		WH_OWNER.FISCAL_DAY
	WHERE
		(FISCAL_DAY.SALES_DT = DATE('now(0)'::"VARCHAR"))))
		AND (A18.FISCAL_YEAR_ID <= (
		SELECT
			DISTINCT FISCAL_DAY.FISCAL_YEAR_ID
		FROM
			WH_OWNER.FISCAL_DAY
		WHERE
			(FISCAL_DAY.SALES_DT = DATE('now(0)'::"VARCHAR")))))
GROUP BY
	A11.ITEM_NBR,
	A11.FACILITY_ID;
	

--V_COMMODITY
SELECT
	A."Facility ID",
	A."DC Item",
	A."Commodity"
FROM
	(
	SELECT
		A."Facility ID",
		A."DC Item",
		A."Commodity",
		A."Max Date",
		ROW_NUMBER() OVER (PARTITION BY A."Facility ID",
		A."DC Item"
	ORDER BY
		A."Max Date" DESC ) AS "Rank"
	FROM
		(
		SELECT
			A.FACILITY_ID AS "Facility ID",
			A.ITEM_NBR AS "DC Item",
			B.COMMODITY_DESC AS "Commodity",
			MAX(A.TRANSACTION_DATE) AS "Max Date"
		FROM
			(WH_OWNER.DC_SALES_HST A
		JOIN WH_OWNER.COMMODITY B ON
			((A.COMMODITY_CODE = B.COMMODITY_CODE)))
		GROUP BY
			A.FACILITY_ID,
			A.ITEM_NBR,
			B.COMMODITY_DESC) A) A
WHERE
	(A."Rank" = 1);