Select 'old' row_type, count(*) num_rows, sum(EXT_WHSE_SALES_AMT) from SBX_BIZ.MARKETING.EFIN_WK_LINE_ITEM where FISCAL_WEEK_ID = 202215 --and SALES_LINE_ID = 'SRTL2304'
union all
Select 'new' row_type, count(*) num_rows, sum(EXT_WHSE_SALES_AMT) from SBX_BIZ.MARKETING.EFIN_WK_LINE_ITEM_TEST where FISCAL_WEEK_ID = 202215 --and SALES_LINE_ID = 'SRTL2304'
;



create or replace view SBX_BIZ.MARKETING.EFIN_WK_LINE_ITEM_TEST
AS
SELECT   DT.FISCAL_WEEK FISCAL_WEEK_ID, EFIN.WEEK_ENDING_DT,
         EFIN.SALES_LINE_ID,
         SUBSTRING(TRIM(RI.PRODUCT_UPC),1,13) AS ITEM_ID,
         EFIN.EXT_WHSE_SALES_AMT,
         0 as EXT_PA_AMT,
         0 as EXT_CASH_DISC_AMT,
         EFIN.EXT_PROFIT_AMT,
         0 as EXT_CREDIT_AMT,
         0 as DIRECT_SALES_AMT,
         0 as EXT_COSTPLUS_AMT,
         EFIN.EXT_NET_COST_AMT,
         EFIN.EXT_COST_ALLW_AMT,
         EFIN.EXT_GROSS_PRC_AMT,
         0 as EXT_CASE_COST_AMT,
         0 as EXT_NET_PRICE_AMT,
         EFIN.WHSE_MVMT_QTY,
         EFIN.EXT_MOVEMENT_WT,
         EFIN.TOTAL_SALES_AMT,
         EFIN.DISCOUNT_TYPE_CD,
         EFIN.DISCOUNT_AMT,
         EFIN.ALLOCATED_DISC_AMT,
         EFIN.PROMOTION_ID,
         EFIN.EVENT_CD,
         EFIN.EXT_BILLBACK_AMT
FROM     SBX_BIZ.MARKETING.EFIN_WK_LINE_ITEM_MV EFIN 
         JOIN EDW.MDM.DATE_DIM DT ON EFIN.WEEK_ENDING_DT = DT.FULL_DATE
         JOIN EDW.RTL.RETAIL_ITEM RI ON EFIN.RETAIL_ITEM_ID = RI.RETAIL_ITEM_PK
--where dt.FISCAL_WEEK = 202214
;


select last_day(current_date(), week) from dual