((
SELECT
	(((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(C.SALES_DT))))::VARCHAR(215) AS "Comp Store Key",
	B.STORE_NBR AS "Store Nbr",
	A.SALES_DT AS "Wk End Dt",
	(SUM(A.SALES_AMT))::NUMERIC(38,
	2) AS "Sales Dollars EBT"
FROM
	(((WH_OWNER.COMP_DAY_LN_TNDR A
JOIN WH_OWNER.LINE B ON
	((A.SALES_LINE_ID = B.SALES_LINE_ID)))
JOIN WH_OWNER.FISCAL_DAY C ON
	((A.SALES_DT = C.SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK D ON
	((C.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
WHERE
	((((((D.END_DT >= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
			AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
		AND (D.END_DT <= (
		SELECT
			DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
		FROM
			WH_OWNER.V_FISCAL_CALENDAR
		WHERE
			(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 1)))))
		AND ((((INT4((A.TENDER_ID)::"VARCHAR") = 31)
			OR (INT4((A.TENDER_ID)::"VARCHAR") = 32))
			OR ((INT4((A.TENDER_ID)::"VARCHAR") = 41)
				OR (INT4((A.TENDER_ID)::"VARCHAR") = 64)))
			OR ((INT4((A.TENDER_ID)::"VARCHAR") = 43)
				OR (INT4((A.TENDER_ID)::"VARCHAR") = 45))))
		AND (B.FORMAT_TYPE_ID = 'SUPERMKT  '::BPCHAR))
		AND (B.CUST_STATUS_KEY < 3))
		AND (B.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))
GROUP BY
	((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(C.SALES_DT))),
	B.STORE_NBR,
	A.SALES_DT)


UNION ALL (


SELECT
(((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(C.SALES_DT))))::VARCHAR(215) AS "Comp Store Key",
B.STORE_NBR AS "Store Nbr",
A.SALES_DT AS "Wk End Dt",
(SUM(A.SALES_AMT))::NUMERIC(38,
2) AS "Sales Dollars EBT"
FROM
(((WH_OWNER.COMP_DAY_LN_TNDR A
JOIN WH_OWNER.LINE B ON
((A.SALES_LINE_ID = B.SALES_LINE_ID)))
JOIN WH_OWNER.FISCAL_DAY C ON
((A.SALES_DT = C.LY_SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK D ON
((C.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
WHERE
((((((D.END_DT >= (
SELECT
	DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (D.END_DT <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 1)))))
	AND ((((INT4((A.TENDER_ID)::"VARCHAR") = 31)
		OR (INT4((A.TENDER_ID)::"VARCHAR") = 32))
		OR ((INT4((A.TENDER_ID)::"VARCHAR") = 41)
			OR (INT4((A.TENDER_ID)::"VARCHAR") = 64)))
		OR ((INT4((A.TENDER_ID)::"VARCHAR") = 43)
			OR (INT4((A.TENDER_ID)::"VARCHAR") = 45))))
	AND (B.FORMAT_TYPE_ID = 'SUPERMKT  '::BPCHAR))
	AND (B.CUST_STATUS_KEY < 3))
	AND (B.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))
GROUP BY
((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(C.SALES_DT))),
B.STORE_NBR,
A.SALES_DT))


UNION ALL (


SELECT
(((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(C.SALES_DT))))::VARCHAR(215) AS "Comp Store Key",
B.STORE_NBR AS "Store Nbr",
A.SALES_DT AS "Wk End Dt",
(SUM(A.SALES_AMT))::NUMERIC(38,
2) AS "Sales Dollars EBT"
FROM
(((WH_OWNER.COMP_DAY_LN_TNDR A
JOIN WH_OWNER.LINE B ON
((A.SALES_LINE_ID = B.SALES_LINE_ID)))
JOIN (
SELECT
	A.FISCAL_WEEK_ID,
	A.SALES_DT,
	A.LY_SALES_DT,
	B.LY_SALES_DT AS LLY_SALES_DT
FROM
	(WH_OWNER.FISCAL_DAY A
JOIN WH_OWNER.FISCAL_DAY B ON
	((B.SALES_DT = A.LY_SALES_DT)))) C ON
((A.SALES_DT = C.LLY_SALES_DT)))
JOIN WH_OWNER.FISCAL_WEEK D ON
((C.FISCAL_WEEK_ID = D.FISCAL_WEEK_ID)))
WHERE
((((((D.END_DT >= (
SELECT
	DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
FROM
	WH_OWNER.V_FISCAL_CALENDAR
WHERE
	((V_FISCAL_CALENDAR."Wk End Dt" >= (DATE('now(0)'::"VARCHAR") - 7))
		AND (V_FISCAL_CALENDAR."Wk End Dt" <= (DATE('now(0)'::"VARCHAR") - 1)))))
	AND (D.END_DT <= (
	SELECT
		DISTINCT V_FISCAL_CALENDAR."Wk End Dt"
	FROM
		WH_OWNER.V_FISCAL_CALENDAR
	WHERE
		(V_FISCAL_CALENDAR."Dt" = (DATE('now(0)'::"VARCHAR") - 1)))))
	AND ((((INT4((A.TENDER_ID)::"VARCHAR") = 31)
		OR (INT4((A.TENDER_ID)::"VARCHAR") = 32))
		OR ((INT4((A.TENDER_ID)::"VARCHAR") = 41)
			OR (INT4((A.TENDER_ID)::"VARCHAR") = 64)))
		OR ((INT4((A.TENDER_ID)::"VARCHAR") = 43)
			OR (INT4((A.TENDER_ID)::"VARCHAR") = 45))))
	AND (B.FORMAT_TYPE_ID = 'SUPERMKT  '::BPCHAR))
	AND (B.CUST_STATUS_KEY < 3))
	AND (B.LOYALTY_STATUS_CD <> 'DUMMY'::BPCHAR))
GROUP BY
((BTRIM("VARCHAR"(B.STORE_NBR)) || ' - '::"VARCHAR") || BTRIM("VARCHAR"(C.SALES_DT))),
B.STORE_NBR,
A.SALES_DT);