Select FACILITYID, INVOICE_NBR , BILLING_DATE , ORDER_SOURCE , ORDER_TYPE , CUSTOMER_NO_FULL , UPC_CASE , UPC_UNIT , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , ITEM_DEPT , QTY_ORDERED , QTY_ADJUSTED , QTY_SOLD , FINAL_SELL_AMT , LAYER_EXT_COST , EXTENDED_SALES_AMT 
  from CRMADMIN.T_WHSE_SALES_HISTORY_DTL
 where facilityid in ('008', '054')
   and CUSTOMER_NO_FULL = '13150008'
   and billing_date between '2007-10-28' and '2007-11-03'
   and RECORD_ID = '1'