SELECT   DATE.*, CUST_ITEM.*, ORDER.*, CUST.*, ORD_ITEM.*, 
         ITEM_XREF.* 
FROM     OMSADMIN.CUSTOMER CUST, 
         OMSADMIN.CUSTOMER_ITEMS CUST_ITEM, 
         OMSADMIN.ORDER ORDER, 
         OMSADMIN.DATE DATE, 
         OMSADMIN.ORDER_ITEM ORD_ITEM, 
         OMSADMIN.CUSTOMER_ITEM_XREF ITEM_XREF 
WHERE    CUST.CUSTOMER_NO_FULL=CUST_ITEM.CUSTOMER_NO_FULL 
AND      CUST.FAC=CUST_ITEM.FAC 
AND      CUST_ITEM.FAC=ORDER.FAC 
AND      CUST_ITEM.CUSTOMER_NO_FULL=ORDER.CUSTOMER_NO_FULL 
AND      DATE.DATE_KEY=ORDER.DESIRED_DATE 
AND      ORDER.ORDER_ID=ORD_ITEM.ORDER_ID 
AND      ITEM_XREF.FAC=CUST_ITEM.FAC 
AND      ITEM_XREF.NF_ITEM_NBR_HS=CUST_ITEM.NF_ITEM_NBR_HS