-- Sales found but allowance is different for non GR
CREATE or REPLACE TABLE SBX_IT.PATRICK_KRSNAK.BILLING_ERRORS AS
SELECT DISTINCT
'Allowance Different - SWAT' as REASON_DESC
,CD.OFFERNUMBER as OFFER_NBR
,cd.FACILITY_ID
,CD.ITEM_NBR
,CD.ITEMDESCRIPTION
,AB.INVOICE_NBR
,ab.BILLING_DT 
,cd.CUSTOMER_NO
,cd.ALLOWANCE_TYPE
,cd.ALLOWANCE_AMT as CORRECT_ALLOW_AMT
,ab.ALLOW_AMT as BILLED_ALLOW_AMT
,IFF(ab.SELLING_WEIGHT=0,ab.shipped_qty,ab.shipped_qty*ab.SELLING_WEIGHT) as SHIPPED_QTY
,(ab.SHIPPED_QTY*ab.ALLOW_AMT) - (IFF(ab.SELLING_WEIGHT=0,ab.shipped_qty,ab.shipped_qty*ab.SELLING_WEIGHT)*cd.ALLOWANCE_AMT) as DIFFERENCE
FROM
SBX_IT.PATRICK_KRSNAK.V_ACOUSTIC_BILLINGS ab
INNER JOIN SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
  ON ab.FACILITY_ID = CAST(cd.FACILITY_ID as INTEGER)
     and ab.CUSTOMER_NBR = cd.CUSTOMER_NO
     and ab.ITEM_NBR_HS = CAST(cd.ITEM_NBR as INTEGER)
     and TO_DATE(ab.BILLING_DT) between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
     and TRIM(ab.ALLOW_ID_ACOUSTIC) = cd.OFFERNUMBER
     and IFF(TRIM(ab.ALLOW_TYPE)= 'O','O','P') = IFF(cd.ALLOWANCE_TYPE = 'O','O','P')
     
WHERE
IFF(ab.SELLING_WEIGHT=0,ab.ALLOW_AMT,ab.ALLOW_AMT/ab.SELLING_WEIGHT) <> cd.ALLOWANCE_AMT
and abs(IFF(ab.SELLING_WEIGHT=0,ab.ALLOW_AMT,ab.ALLOW_AMT/ab.SELLING_WEIGHT)-cd.ALLOWANCE_AMT) >= 0.01
and ab.BILLING_DT < '2022-06-01'

UNION

-- Sales found but allowance is different
SELECT DISTINCT
'Allowance Different - GR PA' as REASON_DESC
,CD.OFFERNUMBER as OFFER_NBR
,cd.FACILITY_ID
,CD.ITEM_NBR
,CD.ITEMDESCRIPTION
,AB.INVOICE_NBR
,ab.BILLING_DT
,cd.CUSTOMER_NO
,cd.ALLOWANCE_TYPE
,cd.ALLOWANCE_AMT as CORRECT_ALLOW_AMT
,ab.ALLOW_AMT/IFF(ab.SELLING_WEIGHT=0,ab.shipped_qty,ab.SELLING_WEIGHT) as BILLED_ALLOW_AMT
,IFF(ab.SELLING_WEIGHT=0,ab.shipped_qty,ab.SELLING_WEIGHT) as SHIPPED_QTY
,ab.ALLOW_AMT - (IFF(ab.SELLING_WEIGHT=0,ab.shipped_qty,ab.SELLING_WEIGHT)*cd.ALLOWANCE_AMT) as DIFFERENCE
FROM
SBX_IT.PATRICK_KRSNAK.V_ACOUSTIC_BILLINGS ab
INNER JOIN SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
  ON ab.FACILITY_ID = CAST(cd.FACILITY_ID as INTEGER)
     and ab.CUSTOMER_NBR = cd.CUSTOMER_NO
     and ab.ITEM_NBR_HS = CAST(cd.ITEM_NBR as INTEGER)
     and TO_DATE(ab.BILLING_DT) between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
     and TRIM(ab.ALLOW_ID_ACOUSTIC) = cd.OFFERNUMBER
     and IFF(TRIM(ab.ALLOW_TYPE)= 'O','O','P') = IFF(cd.ALLOWANCE_TYPE = 'O','O','P')
WHERE
ab.FACILITY_ID = 1
and ab.ALLOW_AMT/IFF(ab.SELLING_WEIGHT=0,ab.SHIPPED_QTY,ab.SELLING_WEIGHT) <> cd.ALLOWANCE_AMT
and ab.BILLING_DT < '2022-06-01'

UNION

-- Sales found but allowance is different
SELECT DISTINCT
'Allowance Different - GR OI' as REASON_DESC
,CD.OFFERNUMBER as OFFER_NBR
,cd.FACILITY_ID
,CD.ITEM_NBR
,CD.ITEMDESCRIPTION
,cs.INVOICE_NBR
,cs.DELIVERY_DT as BILLING_DT
,cd.CUSTOMER_NO
,cd.ALLOWANCE_TYPE
,cd.ALLOWANCE_AMT as CORRECT_ALLOW_AMT
,cs.EXT_REFLECT_AMT/cs.SHIPPED_QTY as BILLED_ALLOW_AMT
,cs.SHIPPED_QTY as SHIPPED_QTY
,cs.EXT_REFLECT_AMT - (cs.SHIPPED_QTY*cd.ALLOWANCE_AMT) as DIFFERENCE
FROM
SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
INNER JOIN SBX_IT.PATRICK_KRSNAK.V_CORPORATION_SALES cs
  ON CAST(cd.FACILITY_ID as INTEGER)=cs.FACILITY_ID
     and CAST(cd.CUSTOMER_NO as INTEGER) = cs.CUSTOMER_NBR_STND
     and CAST(cd.ITEM_NBR as INTEGER) = cs.ITEM_NBR
     and cs.DELIVERY_DT between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
         
WHERE
cs.FACILITY_ID = 1
and cd.ALLOWANCE_TYPE = 'O'
and cs.EXT_REFLECT_AMT > 0
and cs.DELIVERY_DT < '2022-06-01'
and cs.EXT_REFLECT_AMT/cs.SHIPPED_QTY <> cd.ALLOWANCE_AMT

UNION

-- Sales with Acoustic deal that does not exist (likely deleted)
SELECT DISTINCT
'Deleted Allowance - SWAT' as REASON_DESC
,ab.ALLOW_ID_ACOUSTIC as OFFER_NBR
,ab.FACILITY_ID
,ab.ITEM_NBR_HS
,'N/A' ITEMDESCRIPTION
,ab.INVOICE_NBR
,ab.BILLING_DT
,ab.CUSTOMER_NBR
,ab.ALLOW_TYPE
,0 as CORRECT_ALLOW_AMT
,ab.ALLOW_AMT as BILLED_ALLOW_AMT
,ab.shipped_qty
,(ab.SHIPPED_QTY*ab.ALLOW_AMT) as DIFFERENCE
FROM
SBX_IT.PATRICK_KRSNAK.V_ACOUSTIC_BILLINGS ab
LEFT OUTER JOIN SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
  ON ab.FACILITY_ID = CAST(cd.FACILITY_ID as INTEGER)
     and ab.CUSTOMER_NBR = CAST(cd.CUSTOMER_NO as INTEGER)
     and ab.ITEM_NBR_HS = CAST(cd.ITEM_NBR as INTEGER)
     and ab.BILLING_DT between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
     and TRIM(ab.ALLOW_ID_ACOUSTIC) = cd.OFFERNUMBER
     and IFF(TRIM(ab.ALLOW_TYPE)= 'O','O','P') = IFF(TRIM(cd.ALLOWANCE_TYPE) = 'O','O','P')
 WHERE
 cd.customer_no is null
 and left(ab.ALLOW_ID_ACOUSTIC,2) = 'SN'
 and ab.BILLING_DT < '2022-06-01'

UNION

-- Sales with Acoustic deal that does not exist (likely deleted)
SELECT DISTINCT
'Deleted Allowance - GR PA' as REASON_DESC
,ab.ALLOW_ID_ACOUSTIC as OFFER_NBR
,ab.FACILITY_ID
,ab.ITEM_NBR_HS
,'N/A' ITEMDESCRIPTION
,ab.INVOICE_NBR
,ab.BILLING_DT
,ab.CUSTOMER_NBR
,ab.ALLOW_TYPE
,0 as CORRECT_ALLOW_AMT
,ab.ALLOW_AMT/ab.SHIPPED_QTY as BILLED_ALLOW_AMT
,ab.shipped_qty
,ab.ALLOW_AMT as DIFFERENCE
FROM
SBX_IT.PATRICK_KRSNAK.V_ACOUSTIC_BILLINGS ab
LEFT OUTER JOIN SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
  ON ab.FACILITY_ID = CAST(cd.FACILITY_ID as INTEGER)
     and ab.CUSTOMER_NBR = CAST(cd.CUSTOMER_NO as INTEGER)
     and ab.ITEM_NBR_HS = CAST(cd.ITEM_NBR as INTEGER)
     and ab.BILLING_DT between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
     and TRIM(ab.ALLOW_ID_ACOUSTIC) = cd.OFFERNUMBER
     and IFF(TRIM(ab.ALLOW_TYPE)= 'O','O','P') = IFF(TRIM(cd.ALLOWANCE_TYPE) = 'O','O','P')
 WHERE
 ab.FACILITY_ID = '001'
 and cd.customer_no is null
 and ab.ALLOW_TYPE <> 'O'
 and left(ab.ALLOW_ID_ACOUSTIC,2) = 'SN'
 and ab.BILLING_DT < '2022-06-01'

UNION

-- Sales with Acoustic deal that does not exist (likely deleted)
SELECT DISTINCT
'Deleted Allowance - GR OI' as REASON_DESC
,'N/A' as OFFER_NBR
,cs.FACILITY_ID
,cs.ITEM_NBR
,'N/A' ITEMDESCRIPTION
,cs.INVOICE_NBR
,cs.DELIVERY_DT as BILLING_DT
,cs.CUSTOMER_NBR_STND as CUSTOMER_NBR
,'O' as ALLOWANCE_TYPE
,0 as CORRECT_ALLOW_AMT
,cs.EXT_REFLECT_AMT/cs.SHIPPED_QTY as BILLED_ALLOW_AMT
,cs.SHIPPED_QTY
,cs.EXT_REFLECT_AMT as DIFFERENCE
FROM
SBX_IT.PATRICK_KRSNAK.V_CORPORATION_SALES cs
LEFT OUTER JOIN SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
   ON CAST(cd.FACILITY_ID as INTEGER)=cs.FACILITY_ID
     and CAST(cd.CUSTOMER_NO as INTEGER) = cs.CUSTOMER_NBR_STND
     and CAST(cd.ITEM_NBR as INTEGER) = cs.ITEM_NBR
     and cs.DELIVERY_DT between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
     and cd.ALLOWANCE_TYPE = 'O'
WHERE
    cs.FACILITY_ID = 1
    and cd.customer_no is null
    and cs.EXT_REFLECT_AMT > 0
    and cs.DELIVERY_DT >= '2022-04-17'
    and cs.DELIVERY_DT < '2022-06-01'

UNION
 
 -- Sales in which there should have been an allowance but not reflected
  SELECT DISTINCT
'Missing Allowance - SWAT' as REASON_DESC
,cd.OFFERNUMBER as OFFER_NBR
,cd.FACILITY_ID
,CD.ITEM_NBR
,CD.ITEMDESCRIPTION
,cs.INVOICE_NBR
,cs.DELIVERY_DT as BILLING_DT
,cd.CUSTOMER_NO
,cd.ALLOWANCE_TYPE
,cd.ALLOWANCE_AMT as CORRECT_ALLOW_AMT
,0 as BILLED_ALLOW_AMT
,IFF(fid.RAND_WGT_CD = 'R',cs.UNITS_LBS_WHSE_QTY, cs.SHIPPED_QTY) as SHIPPED_QTY
,(IFF(fid.RAND_WGT_CD = 'R',cs.UNITS_LBS_WHSE_QTY, cs.SHIPPED_QTY)*cd.ALLOWANCE_AMT) as DIFFERENCE
FROM
SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
INNER JOIN SBX_IT.PATRICK_KRSNAK.V_CORPORATION_SALES cs
  ON CAST(cd.FACILITY_ID as INTEGER)=cs.FACILITY_ID
     and CAST(cd.CUSTOMER_NO as INTEGER) = cs.CUSTOMER_NBR_STND
     and CAST(cd.ITEM_NBR as INTEGER) = cs.ITEM_NBR
     and cs.DELIVERY_DT between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
INNER JOIN EDW.FD.FD_ITEM_VW fid
   ON cs.FACILITY_ID = fid.facility_id
      and cs.ITEM_NBR = CAST(fid.ITEM_NBR_HS as INTEGER)
      and fid.current_flg =1
LEFT OUTER JOIN SBX_IT.PATRICK_KRSNAK.V_ACOUSTIC_BILLINGS ab
  ON ab.FACILITY_ID = CAST(cd.FACILITY_ID as INTEGER)
     and CAST(ab.CUSTOMER_NBR as INTEGER) = CAST(cd.CUSTOMER_NO as INTEGER)
     and ab.ITEM_NBR_HS = CAST(cd.ITEM_NBR as INTEGER)
     and ab.INVOICE_NBR = cs.INVOICE_NBR
     and IFF(TRIM(ab.ALLOW_TYPE)= 'O','O','P') = IFF(cd.ALLOWANCE_TYPE = 'O','O','P')
 WHERE
 ab.CUSTOMER_NBR is null
 and cs.SHIPPED_QTY <> 0
 and cs.DELIVERY_DT <'2022-06-01'
 
 UNION

 SELECT DISTINCT
'Missing Allowance - GR PA' as REASON_DESC
,cd.OFFERNUMBER as OFFER_NBR
,cd.FACILITY_ID
,CD.ITEM_NBR
,CD.ITEMDESCRIPTION
,cs.INVOICE_NBR
,cs.DELIVERY_DT as BILLING_DT
,cd.CUSTOMER_NO
,cd.ALLOWANCE_TYPE
,cd.ALLOWANCE_AMT as CORRECT_ALLOW_AMT
,0 as BILLED_ALLOW_AMT
,IFF(fid.RAND_WGT_CD = 'R',cs.UNITS_LBS_WHSE_QTY, cs.SHIPPED_QTY) as SHIPPED_QTY
,(IFF(fid.RAND_WGT_CD = 'R',cs.UNITS_LBS_WHSE_QTY, cs.SHIPPED_QTY)*cd.ALLOWANCE_AMT) as DIFFERENCE
FROM
SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
INNER JOIN SBX_IT.PATRICK_KRSNAK.V_CORPORATION_SALES cs
  ON CAST(cd.FACILITY_ID as INTEGER)=cs.FACILITY_ID
     and CAST(cd.CUSTOMER_NO as INTEGER) = cs.CUSTOMER_NBR_STND
     and CAST(cd.ITEM_NBR as INTEGER) = cs.ITEM_NBR
     and cs.DELIVERY_DT between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
INNER JOIN EDW.FD.FD_ITEM_VW fid
   ON cs.FACILITY_ID = fid.facility_id
      and cs.ITEM_NBR = CAST(fid.ITEM_NBR_HS as INTEGER)
      and fid.current_flg =1
LEFT OUTER JOIN SBX_IT.PATRICK_KRSNAK.V_ACOUSTIC_BILLINGS ab
  ON ab.FACILITY_ID = CAST(cd.FACILITY_ID as INTEGER)
     and CAST(ab.CUSTOMER_NBR as INTEGER) = CAST(cd.CUSTOMER_NO as INTEGER)
     and ab.ITEM_NBR_HS = CAST(cd.ITEM_NBR as INTEGER)
     and ab.INVOICE_NBR = cs.INVOICE_NBR
     and IFF(TRIM(ab.ALLOW_TYPE)= 'O','O','P') = IFF(cd.ALLOWANCE_TYPE = 'O','O','P')
 WHERE
 cs.FACILITY_ID = 1
 and ab.CUSTOMER_NBR is null
 and cs.SHIPPED_QTY <> 0
 and cs.DELIVERY_DT <'2022-06-01'
 and cd.ALLOWANCE_TYPE <> 'O'

 UNION

 SELECT DISTINCT
'Missing Allowance - GR OI' as REASON_DESC
,cd.OFFERNUMBER as OFFER_NBR
,cd.FACILITY_ID
,CD.ITEM_NBR
,CD.ITEMDESCRIPTION
,cs.INVOICE_NBR
,cs.DELIVERY_DT as BILLIING_DT
,cd.CUSTOMER_NO
,cd.ALLOWANCE_TYPE
,cd.ALLOWANCE_AMT as CORRECT_ALLOW_AMT
,0 as BILLED_ALLOW_AMT
,IFF(fid.RAND_WGT_CD = 'R',cs.UNITS_LBS_WHSE_QTY, cs.SHIPPED_QTY) as SHIPPED_QTY
,(IFF(fid.RAND_WGT_CD = 'R',cs.UNITS_LBS_WHSE_QTY, cs.SHIPPED_QTY)*cd.ALLOWANCE_AMT) as DIFFERENCE
FROM
SBX_IT.ANKITHA_RAMACHANDRAN.CUST_DEALS_DT_RNG cd
INNER JOIN SBX_IT.PATRICK_KRSNAK.V_CORPORATION_SALES cs
  ON CAST(cd.FACILITY_ID as INTEGER)=cs.FACILITY_ID
     and CAST(cd.CUSTOMER_NO as INTEGER) = cs.CUSTOMER_NBR_STND
     and CAST(cd.ITEM_NBR as INTEGER) = cs.ITEM_NBR
     and cs.DELIVERY_DT between cd.EVENT_TYPE_START_TMSP and cd.EVENT_TYPE_END_TMSP
INNER JOIN EDW.FD.FD_ITEM_VW fid
   ON cs.FACILITY_ID = fid.facility_id
      and cs.ITEM_NBR = CAST(fid.ITEM_NBR_HS as INTEGER)
      and fid.current_flg =1
 WHERE
 cs.FACILITY_ID = 1
 and cs.EXT_REFLECT_AMT = 0
 and cs.SHIPPED_QTY <> 0
 and cs.DELIVERY_DT <'2022-06-01'
 and cd.ALLOWANCE_TYPE = 'O'
 ; 
 
