SELECT   *
FROM     PATRICK_KRSNAK.V_CORPORATION_SALES
WHERE    FACILITY_ID = 8
AND      ITEM_NBR = 745687
AND      INVOICE_NBR = 1446694
AND      CUSTOMER_NBR_STND = 388715
;




SELECT   *
FROM     SBX_IT.PATRICK_KRSNAK.V_ACOUSTIC_BILLINGS
WHERE    CORP_CODE = 25450
AND      TRANSACTION_DT between '2022-04-14' and '2022-05-31'

WHERE    FACILITY_ID = 8
AND      ITEM_NBR_HS = 103390
AND      INVOICE_NBR = 1445023
AND      CUSTOMER_NBR = 25450
;


SELECT   *
FROM     SBX_IT.PATRICK_KRSNAK.V_CORPORATION_SALES
WHERE    CORP_CODE = 25450
AND      TRANSACTION_DT between '2022-04-14' and '2022-05-31'
--AND      ITEM_NBR = 9473620
--AND      CORP_CODE = 25450
;


SELECT   *
FROM     SWAT_08_SCDATA01.BH0PALCS
WHERE    AXCST = 24540
AND      AXITEM = 103390
AND      AXINV = 1445023
;

SELECT   wcf.CORP_CODE, vab.*
FROM     SBX_IT.PATRICK_KRSNAK.V_ACOUSTIC_BILLINGS vab 
         inner join EDW.FD.WEB_CUSTOMER_FAC_VW wcf on wcf.FACILITYID = vab.FACILITY_ID and wcf.CUSTOMER_NBR_STND = vab.CUSTOMER_NBR
WHERE    wcf.CORP_CODE = 25450
AND      vab.BILLING_DT between '2022-04-14' and '2022-05-31'
--and vab.ITEM_NBR_HS = 9473620 and vab.CUSTOMER_NBR = 25450
;

-- SBX_IT.PATRICK_KRSNAK.V_CORPORATION_SALES source

create or replace view V_CORPORATION_SALES(
	CORP_CODE,
	CUSTOMER_NBR_STND,
	NAME,
	ADDRESS1,
	ADDRESS2,
	CITY,
	STATE_CD,
	ZIP_CD,
	TRANSACTION_DT,
	FACILITY_ID,
	SHIP_FACILITY_ID,
	INVOICE_NBR,
	ITEM_NBR,
	ORDERED_QTY,
	SHIPPED_QTY,
	UNITS_LBS_WHSE_QTY,
	ITEM_DESCRIP,
	EXT_MOVEMENT_WT,
	EXT_WHSE_SALES_AMT,
	EXT_REFLECT_AMT,
	EXT_PROMO_ALLW_AMT
) as
SELECT   wcf.CORP_CODE,
         wcf.CUSTOMER_NBR_STND,
         wcf.NAME,
         wcf.ADDRESS1,
         wcf.ADDRESS2,
         wcf.CITY,
         wcf.STATE_CD,
         wcf.ZIP_CD,
         dsh.TRANSACTION_DT,
         dsh.FACILITY_ID,
         dsh.SHIP_FACILITY_ID,
         dsh.INVOICE_NBR,
         dsh.ITEM_NBR, 
         dsh.ORDERED_QTY,
         dsh.SHIPPED_QTY, 
         dsh.UNITS_LBS_WHSE_QTY,
         fi.ITEM_DESCRIP,
         dsh.EXT_MOVEMENT_WT,
         dsh.EXT_WHSE_SALES_AMT,
         dsh.EXT_REFLECT_AMT,
         dsh.EXT_PROMO_ALLW_AMT
FROM     EDW.FD.WEB_CUSTOMER_FAC_VW wcf 
         inner join EDW.FD.DC_SALES_HST_VW dsh on wcf.FACILITYID = dsh.FACILITY_ID and wcf.CUSTOMER_NBR_STND = dsh.CUSTOMER_NBR 
         left join EDW.FD.FD_ITEM_VW fi on fi.FACILITY_ID = dsh.FACILITY_ID and fi.ITEM_NBR_HS_NUM = dsh.ITEM_NBR and fi.CURRENT_FLG = 1;