-- EDM.PROMOS_EXP.PROMOTION_PLANNING_REPORT_VW source

create or replace view PROMOTION_PLANNING_REPORT_VW(
	FACILITY_ID,
	LOCATION_GRP_NM,
	AD_WEEK,
	WEEK_NUMBER,
	EVENT_NAME,
	EVENT_DESC,
	DEAL_DESCRIPTION,
	OFFER_NBR,
	REMOVED_DATE,
	WRS_CODE,
	WRS_FLG,
	UPC,
	ITEM_DESC,
	PACK,
	SIZE,
	UOM,
	PRICE,
	OI,
	RPA,
	ALLOWANCE,
	NET_CASE,
	SCAN,
	NET_UNIT_PRICE,
	AD_MULTIPLE,
	AD_SRP,
	PROMO_GP_PERC,
	AD_POSITION,
	DEPT_CODE,
	REG_SRP,
	FS,
	EVENT_NOTE,
	SRC_PROMO_ID,
	STORE_NOTE,
	AD_BOOKING_NBR
) as

(SELECT
  pr.FACILITY_ID,
  pr.LOCATION_GRP_NM,
  pr.AD_WEEK,
  pr.WEEK_NUMBER,
  pr.EVENT_NAME,
  pr.EVENT_DESC,
  pr.DEAL_DESCRIPTION,
  pr.OFFER_NBR,
  pr.REMOVED_DATE,
  pr.WRS_Code,
  pr.WRS_FLG,
  pr.UPC,
  pr.ITEM_DESC,
  pr.PACK,
  pr.SIZE,
  pr.UOM,
  Round(pr.PRICE,2) as PRICE,
  Round(pr.OI,2) as OI,
  Round(pr.RPA,2) as RPA,
  Round(pr.ALLOWANCE,2) as ALLOWANCE,
  Round(pr.NET_CASE,2) as NET_CASE,
  Round(pr.SCAN,2) as SCAN,
  Round(pr.NET_UNIT_PRICE,2) as NET_UNIT_PRICE,
  pr.AD_MULTIPLE,
  Round(pr.AD_SRP,2) as AD_SRP,
  Round(IFF(pr.AD_SRP = 0,0,(((pr.AD_SRP/pr.AD_MULTIPLE)-(pr.NET_UNIT_PRICE-pr.SCAN))/(pr.AD_SRP/pr.AD_MULTIPLE))*100),2) as PROMO_GP_PERC,
  CONCAT(pr.PAGE,' ', pr.AD_POS) as AD_POSITION,
  pr.DEPT_CODE,
  pr.REG_SRP,
  pr.FS,
  pr.EVENT_NOTE
  ,pr.SRC_PROMO_ID
  ,pr.STORE_NOTE
  ,pr.AD_BOOKING_NBR
FROM (
SELECT DISTINCT
    PROMO.FACILITY_ID,
    PROMO.EVT_NM  as EVENT_NAME,
    PROMO.EVT_DESC as EVENT_DESC,
    PROMO.OFFER_NBR,
    PROMO.DEAL_DESC AS DEAL_DESCRIPTION,
    PROMO.LOCATION_GRP_NM,
    PROMO.FISCAL_WEEK AS AD_WEEK,
    PROMO.WEEK_OF_YEAR AS WEEK_NUMBER,
    PROMO.ITEM_NBR AS WRS_Code,
    PROMO.ITEM_REMOVE_TMSP AS REMOVED_DATE,
    PROMO.UPC AS UPC,
    PROMO.RETAIL_ITEM_DESC AS ITEM_DESC,
    PROMO.MASTER_PACK AS PACK,
    PROMO.CATALOG_PRICE AS PRICE,
    PROMO.OI_ALLOW_AMT AS OI,
    PROMO.RPA AS RPA,
    PROMO.ALLOWANCE AS ALLOWANCE,
    PROMO.CATALOG_PRICE-PROMO.ALLOWANCE as NET_CASE,
    PROMO.SCAN_ALLOW_AMT AS SCAN,
    (PROMO.CATALOG_PRICE-PROMO.ALLOWANCE)/(PROMO.MASTER_PACK) as NET_UNIT_PRICE,
    IFF(PROMO.DTL_SUB_TYPE in (1,8),PROMO.TPR_AMT,0) as AD_SRP,
    IFF(PROMO.DTL_SUB_TYPE = 8,PROMO.TPR_MULTIPLE_CNT,1) as AD_MULTIPLE,
    CASE
      WHEN RIGHT(UPPER(PROMO.EVT_PG_NM),2)='FP' THEN 'FR'
      WHEN RIGHT(UPPER(PROMO.EVT_PG_NM),2)='BP' THEN 'BK'
      ELSE 'IN'
     END as PAGE,
     PROMO.EVT_PG_NM,
     CASE
        WHEN UPPER(PROMO.AD_POSITION_FRMT_NM) LIKE '%SUBFEATURE' then 'Sub'
        WHEN UPPER(PROMO.AD_POSITION_FRMT_NM) LIKE '%FEATURE' then 'Feat'
        ELSE 'Sub'
      END as AD_POS,
      CASE
        WHEN Trim(UPPER(PROMO.MERCH_DEPT_DESC)) = 'DAIRY' THEN 'D'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) = 'FROZEN' THEN 'F'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) like 'GROCERY%' THEN 'G'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) =  'MEAT' THEN 'M'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) =  'SEAFOOD' THEN 'S'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) = 'DELI' THEN 'DL'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) = 'BAKERY' THEN 'B'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) = 'PRODUCE' THEN 'P'
      ELSE 'HBC'
      END AS DEPT_CODE,
    PROMO.MERCH_DEPT_DESC,
    PROMO.ITEM_SIZE AS SIZE,
    PROMO.ITEM_SIZE_UOM AS UOM,
    PROMO.NON_PROMO_PRICE AS REG_SRP,
    IFF(UPPER(PROMO.PERFORMANCE_TYPE) like '%EXPO%','Y',NULL) AS FS,
   PROMO.DTL_SUB_TYPE,
   PROMO.PROMO_DESC as EVENT_NOTE,
   IFF(cast(PROMO.STOCK_FAC as Integer)!=cast(PROMO.FACILITY_ID as Integer), 'U',NULL) as WRS_FLG
   ,PROMO.SRC_PROMO_ID
   ,PROMO.STORE_NOTE
   ,ADB.AD_BOOKING_NBR
  FROM
     (SELECT DISTINCT
         P.UPC
         ,P.OFFER_NBR
         ,P.PROMO_DESC
         ,IFF(AC.AD_GRP is not null, AC.ALL_AD_GRP,P.AD_GRP) as AD_GRP
         ,E.EVT_ID
         ,E.START_DT
         ,E.END_DT
         ,P.DTL_SUB_TYPE
         ,P.TPR_AMT
         ,P.TPR_MULTIPLE_CNT
         ,IFF(DM.FACILITY_ID is not null,DM.FACILITY_ID,IFF(DM1.FACILITY_ID is not null, DM1.FACILITY_ID
                 ,IFF(DM2.FACILITY_ID is not null, DM2.FACILITY_ID,FC.HOME_BRANCH))) as FACILITY_ID
         ,IFF(AC.ALL_AD_GRP = '999999', 'ALL CUSTOMERS - 999999',P.LOCATION_GRP_NM) as LOCATION_GRP_NM
         ,P.LOCATION_GRP_ID
         ,AP.AD_POSITION_FRMT_NM
         ,E.EVT_NM
         ,E.EVT_DESC
         ,EP.EVT_PG_NM
         ,IFF(DM.FACILITY_ID is not null,DM.PACK_CNT,IFF(DM1.FACILITY_ID is not null, DM1.PACK_CNT
                 ,IFF(DM2.FACILITY_ID is not null, DM2.PACK_CNT,IFF(DM3.FACILITY_ID is not null, DM3.PACK_CNT,NULL)))) as MASTER_PACK
         ,IFF(DM.FACILITY_ID is not null,DM.DEAL_DESC,IFF(DM1.FACILITY_ID is not null, DM1.DEAL_DESC
                 ,IFF(DM2.FACILITY_ID is not null, DM2.DEAL_DESC,IFF(DM3.FACILITY_ID is not null, DM3.DEAL_DESC,NULL)))) as DEAL_DESC
         ,DD.FISCAL_WEEK
         ,DD.WEEK_OF_YEAR
         ,IFF(DM.FACILITY_ID is not null,DM.ITEM_NBR,IFF(DM1.FACILITY_ID is not null, DM1.ITEM_NBR
                 ,IFF(DM2.FACILITY_ID is not null, DM2.ITEM_NBR,IFF(DM3.FACILITY_ID is not null, 'DSD',NULL)))) as ITEM_NBR
         ,IFF(DM.FACILITY_ID is not null,DM.ITEM_REMOVE_TMSP,IFF(DM1.FACILITY_ID is not null, DM1.ITEM_REMOVE_TMSP
                 ,IFF(DM2.FACILITY_ID is not null, DM2.ITEM_REMOVE_TMSP,IFF(DM3.FACILITY_ID is not null, DM3.ITEM_REMOVE_TMSP,NULL)))) as ITEM_REMOVE_TMSP
         ,IFF(DM.FACILITY_ID is not null,DM.ITEM_DESCRIP,IFF(DM1.FACILITY_ID is not null, DM1.ITEM_DESCRIP
                 ,IFF(DM2.FACILITY_ID is not null, DM2.ITEM_DESCRIP,NULL))) as RETAIL_ITEM_DESC
         ,IFF(DM.FACILITY_ID is not null,DM.NON_PROMO_PRICE,IFF(DM1.FACILITY_ID is not null, DM1.NON_PROMO_PRICE
                 ,IFF(DM2.FACILITY_ID is not null, DM2.NON_PROMO_PRICE,IFF(DM3.FACILITY_ID is not null, DM3.NON_PROMO_PRICE,NULL)))) as NON_PROMO_PRICE
         ,IFF(DM.FACILITY_ID is not null,DM.ITEM_SIZE,IFF(DM1.FACILITY_ID is not null, DM1.ITEM_SIZE
                 ,IFF(DM2.FACILITY_ID is not null, DM2.ITEM_SIZE,NULL))) as ITEM_SIZE
         ,IFF(DM.FACILITY_ID is not null,DM.ITEM_SIZE_UOM,IFF(DM1.FACILITY_ID is not null, DM1.ITEM_SIZE_UOM
                 ,IFF(DM2.FACILITY_ID is not null, DM2.ITEM_SIZE_UOM,NULL))) as ITEM_SIZE_UOM
         ,IFF(DM.FACILITY_ID is not null,DM.PERFORMANCE_TYPE,IFF(DM1.FACILITY_ID is not null, DM1.PERFORMANCE_TYPE
                 ,IFF(DM2.FACILITY_ID is not null, DM2.PERFORMANCE_TYPE,IFF(DM3.FACILITY_ID is not null, DM3.PERFORMANCE_TYPE,NULL)))) as PERFORMANCE_TYPE
         ,IFF(DM.FACILITY_ID is not null,DM.MERCH_DEPT_DESC,IFF(DM1.FACILITY_ID is not null, DM1.MERCH_DEPT_DESC
                 ,IFF(DM2.FACILITY_ID is not null, DM2.MERCH_DEPT_DESC,NULL))) as MERCH_DEPT_DESC
         ,IFF(DM.FACILITY_ID is not null,DM.OI_ALLOW_AMT,IFF(DM1.FACILITY_ID is not null, DM1.OI_ALLOW_AMT
                 ,IFF(DM2.FACILITY_ID is not null, DM2.OI_ALLOW_AMT,IFF(DM3.FACILITY_ID is not null, DM3.OI_ALLOW_AMT,NULL)))) as OI_ALLOW_AMT
         ,IFF(DM.FACILITY_ID is not null,DM.RPA,IFF(DM1.FACILITY_ID is not null, DM1.RPA
                 ,IFF(DM2.FACILITY_ID is not null, DM2.RPA,IFF(DM3.FACILITY_ID is not null, DM3.RPA,NULL)))) as RPA
         ,IFF(DM.FACILITY_ID is not null,DM.ALLOWANCE,IFF(DM1.FACILITY_ID is not null, DM1.ALLOWANCE
                 ,IFF(DM2.FACILITY_ID is not null, DM2.ALLOWANCE,IFF(DM3.FACILITY_ID is not null, DM3.ALLOWANCE,NULL)))) as ALLOWANCE
         ,IFF(DM.FACILITY_ID is not null,DM.SCAN_ALLOW_AMT,IFF(DM1.FACILITY_ID is not null, DM1.SCAN_ALLOW_AMT
                 ,IFF(DM2.FACILITY_ID is not null, DM2.SCAN_ALLOW_AMT,IFF(DM3.FACILITY_ID is not null, DM3.SCAN_ALLOW_AMT,NULL)))) as SCAN_ALLOW_AMT
         ,IFF(DM.FACILITY_ID is not null,DM.CATALOG_PRICE,IFF(DM1.FACILITY_ID is not null, DM1.CATALOG_PRICE
                 ,IFF(DM2.FACILITY_ID is not null, DM2.CATALOG_PRICE,NULL))) as CATALOG_PRICE
         ,IFF(DM.FACILITY_ID is not null,DM.STOCK_FAC,IFF(DM1.FACILITY_ID is not null, DM1.STOCK_FAC
                 ,IFF(DM2.FACILITY_ID is not null, DM2.STOCK_FAC,NULL))) as STOCK_FAC
         ,P.SRC_PROMO_ID
         ,NT.LONG_COMMENTS_1 as STORE_NOTE
     FROM EDW.PROMOS.PERFORMANCE P
     INNER JOIN EDW.FD.FD_CUSTOMER_VW FC
           ON P.CUSTOMER_LOCATION_KEY= CAST(FC.CUSTOMER_NO as INTEGER)
              AND FC.MDM_CUST_STATUS_CD IN (1,5,7)
              and P.START_DT between FC.START_DT AND FC.END_DT
              and FC.HOME_BRANCH <> '001'
     LEFT OUTER JOIN EDW.PROMOS.PERFORMANCE NT
         ON P.SRC_PROMO_ID = NT.SRC_PROMO_ID
            and P.DTL_GRP_SRC_ID=NT.DTL_GRP_SRC_ID
            and P.CUSTOMER_LOCATION_KEY = NT.CUSTOMER_LOCATION_KEY
            and P.UPC=NT.UPC
            and NT.LONG_COMMENTS_1 is not null
      INNER JOIN (SELECT SRC_PROMO_ID,SRC_PERF_DTL_GRP_ID,SRC_PERF_DTL_ID,EVT_ID,EVT_PG_ID
                       ,SEGMNT_ID,AD_POSITION_NBR,AD_POSITION_FRMT_NM,PRICE_FRMT_NM
                    FROM EDW.PROMOS.EVENT_PAGE_AD_POSITION
                    WHERE CHANGE_FLG <> -1
                    UNION
                    SELECT SRC_PROMO_ID,SRC_PERF_DTL_GRP_ID, SRC_PERF_DTL_ID,EVT_ID,EVT_PG_ID,SEGMNT_ID,
                       AD_POSITION_NBR,AD_POSITION_FRMT_NM,PRICE_FRMT_NM
                    FROM EDW.PROMOS.PERFORMANCE_GRP
                 WHERE CHANGE_FLG <> -1) AP
           ON P.SRC_PROMO_ID=AP.SRC_PROMO_ID AND P.DTL_GRP_SRC_ID=AP.SRC_PERF_DTL_GRP_ID
              AND P.SRC_DTL_ID=AP.SRC_PERF_DTL_ID
        INNER JOIN EDW.PROMOS.EVENT E
           ON E.EVT_ID=AP.EVT_ID
        INNER JOIN EDW.PROMOS.MRKT_SEGMNT_STORE MST
           ON MST.SEGMNT_ID=AP.SEGMNT_ID AND MST.STORE_NBR=P.CUSTOMER_LOCATION_KEY
        INNER JOIN EDW.PROMOS.EVENT_PAGE EP
           ON EP.EVT_ID=ap.EVT_ID
              and EP.EVT_PG_ID=AP.EVT_PG_ID
        INNER JOIN EDW.MDM.DATE_DIM_VW DD
           ON DD.FULL_DATE=P.START_DT
       LEFT OUTER JOIN EDW.PROMOS.AD_GRP_ALL_CUST AC
           ON TRY_TO_NUMBER(P.AD_GRP)=AC.AD_GRP
      LEFT OUTER JOIN
        (SELECT
           DM.OFFER_NBR,
           DM.FACILITY_ID,
           DM.ITEM_NBR,
           DM.PRICE_TYPE_ID,
           DM.UPC_CONSUMER,
           DM.ITEM_REMOVE_TMSP,
           DM.PERFORMANCE_TYPE,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) ='OI', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) ='OI', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.OI_ALLOW_AMT is null,0,OD.OI_ALLOW_AMT)) as OI_ALLOW_AMT,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) <> 'SCAN', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) <> 'SCAN', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.ALLOW_AMT is null,0,OD.ALLOW_AMT)) as ALLOW_AMT,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'), SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'),MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.RPA is null,0,OD.RPA)) AS RPA,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'), SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'),MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.ALLOWANCE is null,0,OD.ALLOWANCE)) AS ALLOWANCE,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) ='SCAN', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) = 'SCAN', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.SCAN_ALLOW_AMT is null,0,OD.SCAN_ALLOW_AMT)) as SCAN_ALLOW_AMT,
           DM.NON_PROMO_PRICE,
           DM.PACK_CNT,
           FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           MIN(IFF(SF.SALES_PLAN_SELL is not null, SF.SALES_PLAN_SELL,SC.SALES_PLAN_SELL)) AS CATALOG_PRICE,
          FID.ITEM_SIZE,
           FID.ITEM_SIZE_UOM,
           DM.DEAL_DESC,FID.STOCK_FAC
         FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT DM
           INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
              ON DM.DM_MAIN_ID=MA.DM_MAIN_ID
           INNER JOIN EDW.FD.FD_ITEM_VW FID
              ON  LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0')=DM.FACILITY_ID
                AND FID.ITEM_NBR = DM.BICEPS_ITEM_NM
                and DM.PERFORMANCE_START_TMSP between FID.START_DT and FID.END_DT
           INNER JOIN EDL.CRM.T_WHSE_SELL_CURRENT SC
              ON DM.FACILITY_ID = LPAD(CAST(SC.FACILITYID AS STRING),3,'0')
                and DM.ITEM_NBR = SC.ITEM_NBR_HS
                and SC.SALES_PLAN = 2
           LEFT OUTER JOIN EDL.CRM.T_WHSE_SELL SF
              ON DM.FACILITY_ID = LPAD(CAST(SF.FACILITYID AS STRING),3,'0')
                 and DM.ITEM_NBR = SF.ITEM_NBR_HS
                 and SF.SALES_PLAN = 2
                 and SF.SELL_PRICE_EFF_DATE > SC.SELL_PRICE_EFF_DATE
                 and SF.SELL_PRICE_EFF_DATE <= MA.EVENT_TYPE_START_TMSP
           LEFT OUTER JOIN
              (SELECT
                 DM.FACILITY_ID,
                 DM.ITEM_NBR,
                 DM.OFFER_NBR,
                 MA.EVENT_TYPE_START_TMSP,
                 MA.EVENT_TYPE_END_TMSP,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) ='OI', MA.EVENT_TYPE_AMT,0)) as OI_ALLOW_AMT,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) <> 'SCAN', MA.EVENT_TYPE_AMT,0)) as ALLOW_AMT,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'),MA.EVENT_TYPE_AMT,0)) AS RPA,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'),MA.EVENT_TYPE_AMT,0)) AS ALLOWANCE,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) = 'SCAN', MA.EVENT_TYPE_AMT,0)) as SCAN_ALLOW_AMT
               FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT DM
                 INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
                    ON DM.DM_MAIN_ID=MA.DM_MAIN_ID
               WHERE
                  DM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
                  AND DM.EXPORT_ACTION <> 'D'
                  AND DM.ITEM_REMOVE_TMSP is NULL
                  AND DM.FACILITY_ID NOT IN ('DSD','001')
                  AND UPPER(MA.EVENT_TYPE_SHORT_DESC) not in ('AF')
                  AND MA.EVENT_TYPE_END_TMSP >= sysdate ()
               GROUP BY
                 DM.FACILITY_ID,
                 DM.ITEM_NBR,
                 DM.OFFER_NBR,
                 MA.EVENT_TYPE_START_TMSP,
                 MA.EVENT_TYPE_END_TMSP) OD
               ON DM.FACILITY_ID = OD.FACILITY_ID
                  and DM.ITEM_NBR = OD.ITEM_NBR
                  and DM.OFFER_NBR <> OD.OFFER_NBR
                  and DATE_TRUNC(Day,MA.EVENT_TYPE_START_TMSP) >= DATE_TRUNC(Day,OD.EVENT_TYPE_START_TMSP)
                  and DATE_TRUNC(Day,MA.EVENT_TYPE_END_TMSP) <= DATE_TRUNC(Day,OD.EVENT_TYPE_END_TMSP)

          LEFT OUTER JOIN (SELECT distinct
               MDM.FACILITY_ID,
               MDM.OFFER_NBR,
               MDM.ITEM_NBR,
               MA.EVENT_TYPE_SHORT_DESC,
               MA.EVENT_TYPE_AMT
             FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT MDM
               INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
                  ON MDM.DM_MAIN_ID=MA.DM_MAIN_ID
             WHERE
                MDM.PERFORMANCE_END_TMSP>SYSDATE()
                AND MDM.EXPORT_ACTION <> 'D'
                AND MDM.ITEM_REMOVE_TMSP IS NULL
                AND MDM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
                AND UPPER(MA.EVENT_TYPE_SHORT_DESC) NOT IN ('AF','DSD TW','DSD SM')
                AND MDM.FACILITY_ID NOT IN ('DSD','001') 
                AND SHIPPER_FLG IS NOT NULL
                AND SHIPPER_FLG <> 'N'    
             ) SHIP
             ON DM.FACILITY_ID = SHIP.FACILITY_ID
                and DM.ITEM_NBR = SHIP.ITEM_NBR
                and DM.OFFER_NBR = SHIP.OFFER_NBR
                and MA.EVENT_TYPE_SHORT_DESC = SHIP.EVENT_TYPE_SHORT_DESC

         WHERE
            DM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
            AND DM.EXPORT_ACTION <> 'D'
            AND DM.ITEM_REMOVE_TMSP is NULL
            AND DM.FACILITY_ID NOT IN ('DSD','001')
            AND UPPER(MA.EVENT_TYPE_SHORT_DESC) not in ('AF')
            AND MA.EVENT_TYPE_END_TMSP >= sysdate ()
         GROUP BY
           DM.OFFER_NBR,
           DM.FACILITY_ID,
           DM.ITEM_NBR,
           DM.PRICE_TYPE_ID,
           DM.UPC_CONSUMER,
           DM.ITEM_REMOVE_TMSP,
           DM.PERFORMANCE_TYPE,
           DM.NON_PROMO_PRICE,
           DM.PACK_CNT,
           FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           FID.ITEM_SIZE,
           FID.ITEM_SIZE_UOM,
           DM.DEAL_DESC,FID.STOCK_FAC) DM
             ON DM.OFFER_NBR=P.OFFER_NBR
                AND DM.UPC_CONSUMER= P.UPC  
                and DM.FACILITY_ID = FC.HOME_BRANCH
      LEFT OUTER JOIN
        (SELECT
           DM.OFFER_NBR,
           DM.FACILITY_ID,
           DM.ITEM_NBR,
           DM.PRICE_TYPE_ID,
           DM.UPC_CONSUMER,
           DM.ITEM_REMOVE_TMSP,
           DM.PERFORMANCE_TYPE,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) ='OI', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) ='OI', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.OI_ALLOW_AMT is null,0,OD.OI_ALLOW_AMT)) as OI_ALLOW_AMT,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) <> 'SCAN', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) <> 'SCAN', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.ALLOW_AMT is null,0,OD.ALLOW_AMT)) as ALLOW_AMT,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'), SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'),MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.RPA is null,0,OD.RPA)) AS RPA,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'), SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'),MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.ALLOWANCE is null,0,OD.ALLOWANCE)) AS ALLOWANCE,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) ='SCAN', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) = 'SCAN', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.SCAN_ALLOW_AMT is null,0,OD.SCAN_ALLOW_AMT)) as SCAN_ALLOW_AMT,
           DM.NON_PROMO_PRICE,
           DM.PACK_CNT,
           FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           MIN(IFF(SF.SALES_PLAN_SELL is not null, SF.SALES_PLAN_SELL,SC.SALES_PLAN_SELL)) AS CATALOG_PRICE,
          FID.ITEM_SIZE,
           FID.ITEM_SIZE_UOM,
           DM.DEAL_DESC,FID.STOCK_FAC
         FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT DM
           INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
              ON DM.DM_MAIN_ID=MA.DM_MAIN_ID
           INNER JOIN EDW.FD.FD_ITEM_VW FID
              ON  LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0')=DM.FACILITY_ID
                AND FID.ITEM_NBR = DM.BICEPS_ITEM_NM
                and DM.PERFORMANCE_START_TMSP between FID.START_DT and FID.END_DT
           INNER JOIN EDL.CRM.T_WHSE_SELL_CURRENT SC
              ON DM.FACILITY_ID = LPAD(CAST(SC.FACILITYID AS STRING),3,'0')
                and DM.ITEM_NBR = SC.ITEM_NBR_HS
                and SC.SALES_PLAN = 2
           LEFT OUTER JOIN EDL.CRM.T_WHSE_SELL SF
              ON DM.FACILITY_ID = LPAD(CAST(SF.FACILITYID AS STRING),3,'0')
                 and DM.ITEM_NBR = SF.ITEM_NBR_HS
                 and SF.SALES_PLAN = 2
                 and SF.SELL_PRICE_EFF_DATE > SC.SELL_PRICE_EFF_DATE
                 and SF.SELL_PRICE_EFF_DATE <= MA.EVENT_TYPE_START_TMSP
           LEFT OUTER JOIN
              (SELECT
                 DM.FACILITY_ID,
                 DM.ITEM_NBR,
                 DM.OFFER_NBR,
                 MA.EVENT_TYPE_START_TMSP,
                 MA.EVENT_TYPE_END_TMSP,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) ='OI', MA.EVENT_TYPE_AMT,0)) as OI_ALLOW_AMT,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) <> 'SCAN', MA.EVENT_TYPE_AMT,0)) as ALLOW_AMT,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'),MA.EVENT_TYPE_AMT,0)) AS RPA,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'),MA.EVENT_TYPE_AMT,0)) AS ALLOWANCE,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) = 'SCAN', MA.EVENT_TYPE_AMT,0)) as SCAN_ALLOW_AMT
               FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT DM
                 INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
                    ON DM.DM_MAIN_ID=MA.DM_MAIN_ID
               WHERE
                  DM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
                  AND DM.EXPORT_ACTION <> 'D'
                  AND DM.ITEM_REMOVE_TMSP is NULL
                  AND DM.FACILITY_ID NOT IN ('DSD','001')
                  AND UPPER(MA.EVENT_TYPE_SHORT_DESC) not in ('AF')
                  AND MA.EVENT_TYPE_END_TMSP >= sysdate ()
               GROUP BY
                 DM.FACILITY_ID,
                 DM.ITEM_NBR,
                 DM.OFFER_NBR,
                 MA.EVENT_TYPE_START_TMSP,
                 MA.EVENT_TYPE_END_TMSP) OD
               ON DM.FACILITY_ID = OD.FACILITY_ID
                  and DM.ITEM_NBR = OD.ITEM_NBR
                  and DM.OFFER_NBR <> OD.OFFER_NBR
                  and DATE_TRUNC(Day,MA.EVENT_TYPE_START_TMSP) >= DATE_TRUNC(Day,OD.EVENT_TYPE_START_TMSP)
                  and DATE_TRUNC(Day,MA.EVENT_TYPE_END_TMSP) <= DATE_TRUNC(Day,OD.EVENT_TYPE_END_TMSP)

            LEFT OUTER JOIN (SELECT distinct
               MDM.FACILITY_ID,
               MDM.OFFER_NBR,
               MDM.ITEM_NBR,
               MA.EVENT_TYPE_SHORT_DESC,
               MA.EVENT_TYPE_AMT
             FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT MDM
               INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
                  ON MDM.DM_MAIN_ID=MA.DM_MAIN_ID
             WHERE
                MDM.PERFORMANCE_END_TMSP>SYSDATE()
                AND MDM.EXPORT_ACTION <> 'D'
                AND MDM.ITEM_REMOVE_TMSP IS NULL
                AND MDM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
                AND UPPER(MA.EVENT_TYPE_SHORT_DESC) NOT IN ('AF','DSD TW','DSD SM')
                AND MDM.FACILITY_ID NOT IN ('DSD','001') 
                AND SHIPPER_FLG IS NOT NULL
                AND SHIPPER_FLG <> 'N'    
             ) SHIP
             ON DM.FACILITY_ID = SHIP.FACILITY_ID
                and DM.ITEM_NBR = SHIP.ITEM_NBR
                and DM.OFFER_NBR = SHIP.OFFER_NBR
                and MA.EVENT_TYPE_SHORT_DESC = SHIP.EVENT_TYPE_SHORT_DESC

         WHERE
            DM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
            AND DM.EXPORT_ACTION <> 'D'
            AND DM.ITEM_REMOVE_TMSP is NULL
            AND DM.FACILITY_ID NOT IN ('DSD','001')
            AND UPPER(MA.EVENT_TYPE_SHORT_DESC) not in ('AF')
            AND MA.EVENT_TYPE_END_TMSP >= sysdate ()
         GROUP BY
           DM.OFFER_NBR,
           DM.FACILITY_ID,
           DM.ITEM_NBR,
           DM.PRICE_TYPE_ID,
           DM.UPC_CONSUMER,
           DM.ITEM_REMOVE_TMSP,
           DM.PERFORMANCE_TYPE,
           DM.NON_PROMO_PRICE,
           DM.PACK_CNT,
           FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           FID.ITEM_SIZE,
           FID.ITEM_SIZE_UOM,
           DM.DEAL_DESC,FID.STOCK_FAC) DM1
             ON DM1.OFFER_NBR=P.OFFER_NBR
                AND DM1.UPC_CONSUMER= P.UPC  
                and DM1.FACILITY_ID = '054' 
                and FC.HOME_BRANCH not in ('015','058')
     LEFT OUTER JOIN
        (SELECT
           DM.OFFER_NBR,
           DM.FACILITY_ID,
           DM.ITEM_NBR,
           DM.PRICE_TYPE_ID,
           DM.UPC_CONSUMER,
           DM.ITEM_REMOVE_TMSP,
           DM.PERFORMANCE_TYPE,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) ='OI', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) ='OI', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.OI_ALLOW_AMT is null,0,OD.OI_ALLOW_AMT)) as OI_ALLOW_AMT,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) <> 'SCAN', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) <> 'SCAN', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.ALLOW_AMT is null,0,OD.ALLOW_AMT)) as ALLOW_AMT,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'), SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'),MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.RPA is null,0,OD.RPA)) AS RPA,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'), SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'),MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.ALLOWANCE is null,0,OD.ALLOWANCE)) AS ALLOWANCE,
           SUM(IFF(UPPER(SHIP.EVENT_TYPE_SHORT_DESC) ='SCAN', SHIP.EVENT_TYPE_AMT,IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) = 'SCAN', MA.EVENT_TYPE_AMT,0)))
                  + MIN(IFF(OD.SCAN_ALLOW_AMT is null,0,OD.SCAN_ALLOW_AMT)) as SCAN_ALLOW_AMT,
           DM.NON_PROMO_PRICE,
           DM.PACK_CNT,
           FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           MIN(IFF(SF.SALES_PLAN_SELL is not null, SF.SALES_PLAN_SELL,SC.SALES_PLAN_SELL)) AS CATALOG_PRICE,
          FID.ITEM_SIZE,
           FID.ITEM_SIZE_UOM,
           DM.DEAL_DESC,FID.STOCK_FAC
         FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT DM
           INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
              ON DM.DM_MAIN_ID=MA.DM_MAIN_ID
           INNER JOIN EDW.FD.FD_ITEM_VW FID
              ON  LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0')=DM.FACILITY_ID
                AND FID.ITEM_NBR = DM.BICEPS_ITEM_NM
                and DM.PERFORMANCE_START_TMSP between FID.START_DT and FID.END_DT
           INNER JOIN EDL.CRM.T_WHSE_SELL_CURRENT SC
              ON DM.FACILITY_ID = LPAD(CAST(SC.FACILITYID AS STRING),3,'0')
                and DM.ITEM_NBR = SC.ITEM_NBR_HS
                and SC.SALES_PLAN = 2
           LEFT OUTER JOIN EDL.CRM.T_WHSE_SELL SF
              ON DM.FACILITY_ID = LPAD(CAST(SF.FACILITYID AS STRING),3,'0')
                 and DM.ITEM_NBR = SF.ITEM_NBR_HS
                 and SF.SALES_PLAN = 2
                 and SF.SELL_PRICE_EFF_DATE > SC.SELL_PRICE_EFF_DATE
                 and SF.SELL_PRICE_EFF_DATE <= MA.EVENT_TYPE_START_TMSP
           LEFT OUTER JOIN
              (SELECT
                 DM.FACILITY_ID,
                 DM.ITEM_NBR,
                 DM.OFFER_NBR,
                 MA.EVENT_TYPE_START_TMSP,
                 MA.EVENT_TYPE_END_TMSP,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) ='OI', MA.EVENT_TYPE_AMT,0)) as OI_ALLOW_AMT,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) <> 'SCAN', MA.EVENT_TYPE_AMT,0)) as ALLOW_AMT,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'),MA.EVENT_TYPE_AMT,0)) AS RPA,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'),MA.EVENT_TYPE_AMT,0)) AS ALLOWANCE,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) = 'SCAN', MA.EVENT_TYPE_AMT,0)) as SCAN_ALLOW_AMT
               FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT DM
                 INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
                    ON DM.DM_MAIN_ID=MA.DM_MAIN_ID
               WHERE
                  DM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
                  AND DM.EXPORT_ACTION <> 'D'
                  AND DM.ITEM_REMOVE_TMSP is NULL
                  AND DM.FACILITY_ID NOT IN ('DSD','001')
                  AND UPPER(MA.EVENT_TYPE_SHORT_DESC) not in ('AF')
                  AND MA.EVENT_TYPE_END_TMSP >= sysdate ()
               GROUP BY
                 DM.FACILITY_ID,
                 DM.ITEM_NBR,
                 DM.OFFER_NBR,
                 MA.EVENT_TYPE_START_TMSP,
                 MA.EVENT_TYPE_END_TMSP) OD
               ON DM.FACILITY_ID = OD.FACILITY_ID
                  and DM.ITEM_NBR = OD.ITEM_NBR
                  and DM.OFFER_NBR <> OD.OFFER_NBR
                  and DATE_TRUNC(Day,MA.EVENT_TYPE_START_TMSP) >= DATE_TRUNC(Day,OD.EVENT_TYPE_START_TMSP)
                  and DATE_TRUNC(Day,MA.EVENT_TYPE_END_TMSP) <= DATE_TRUNC(Day,OD.EVENT_TYPE_END_TMSP)

          LEFT OUTER JOIN (SELECT distinct
               MDM.FACILITY_ID,
               MDM.OFFER_NBR,
               MDM.ITEM_NBR,
               MA.EVENT_TYPE_SHORT_DESC,
               MA.EVENT_TYPE_AMT
             FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT MDM
               INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
                  ON MDM.DM_MAIN_ID=MA.DM_MAIN_ID
             WHERE
                MDM.PERFORMANCE_END_TMSP>SYSDATE()
                AND MDM.EXPORT_ACTION <> 'D'
                AND MDM.ITEM_REMOVE_TMSP IS NULL
                AND MDM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
                AND UPPER(MA.EVENT_TYPE_SHORT_DESC) NOT IN ('AF','DSD TW','DSD SM')
                AND MDM.FACILITY_ID NOT IN ('DSD','001') 
                AND SHIPPER_FLG IS NOT NULL
                AND SHIPPER_FLG <> 'N'    
             ) SHIP
             ON DM.FACILITY_ID = SHIP.FACILITY_ID
                and DM.ITEM_NBR = SHIP.ITEM_NBR
                and DM.OFFER_NBR = SHIP.OFFER_NBR
                and MA.EVENT_TYPE_SHORT_DESC = SHIP.EVENT_TYPE_SHORT_DESC

         WHERE
            DM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
            AND DM.EXPORT_ACTION <> 'D'
            AND DM.ITEM_REMOVE_TMSP is NULL
            AND DM.FACILITY_ID NOT IN ('DSD','001')
            AND UPPER(MA.EVENT_TYPE_SHORT_DESC) not in ('AF')
            AND MA.EVENT_TYPE_END_TMSP >= sysdate ()
         GROUP BY
           DM.OFFER_NBR,
           DM.FACILITY_ID,
           DM.ITEM_NBR,
           DM.PRICE_TYPE_ID,
           DM.UPC_CONSUMER,
           DM.ITEM_REMOVE_TMSP,
           DM.PERFORMANCE_TYPE,
           DM.NON_PROMO_PRICE,
           DM.PACK_CNT,
           FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           FID.ITEM_SIZE,
           FID.ITEM_SIZE_UOM,
           DM.DEAL_DESC,FID.STOCK_FAC) DM2
       ON DM2.OFFER_NBR=P.OFFER_NBR
          AND DM2.UPC_CONSUMER= P.UPC  
          and DM2.FACILITY_ID = '003'
          and TRIM(UPPER(DM2.MERCH_DEPT_DESC)) in ('PRODUCE', 'FLORAL')
          and FC.HOME_BRANCH not in ('015','058')
     LEFT OUTER JOIN
        (SELECT
          DM.OFFER_NBR,
           DM.FACILITY_ID,
           DM.PRICE_TYPE_ID,
           DM.UPC_CONSUMER,
           DM.ITEM_REMOVE_TMSP,
           DM.PERFORMANCE_TYPE,
           SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) ='OI', MA.EVENT_TYPE_AMT,0))+ MIN(IFF(OD.OI_ALLOW_AMT is null,0,OD.OI_ALLOW_AMT)) as OI_ALLOW_AMT,
           SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) <> 'SCAN', MA.EVENT_TYPE_AMT,0))+ MIN(IFF(OD.ALLOW_AMT is null,0,OD.ALLOW_AMT)) as ALLOW_AMT,
           SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'),MA.EVENT_TYPE_AMT,0))+ MIN(IFF(OD.RPA is null,0,OD.RPA)) AS RPA,
           SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'),MA.EVENT_TYPE_AMT,0))+ MIN(IFF(OD.ALLOWANCE is null,0,OD.ALLOWANCE)) AS ALLOWANCE,
           SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) = 'SCAN', MA.EVENT_TYPE_AMT,0))+ MIN(IFF(OD.SCAN_ALLOW_AMT is null,0,OD.SCAN_ALLOW_AMT)) as SCAN_ALLOW_AMT,
           DM.NON_PROMO_PRICE,
           DM.PACK_CNT,
           DM.DEAL_DESC
         FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT DM
           INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
              ON DM.DM_MAIN_ID=MA.DM_MAIN_ID
           INNER JOIN EDW.FD.FD_ITEM_VW FID
              ON  LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0')=DM.FACILITY_ID
                 AND FID.ITEM_NBR = DM.BICEPS_ITEM_NM
                 and DM.PERFORMANCE_START_TMSP between FID.START_DT and FID.END_DT
           LEFT OUTER JOIN
              (SELECT
                 DM.FACILITY_ID,
                 DM.ITEM_NBR,
                 DM.OFFER_NBR,
                 MA.EVENT_TYPE_START_TMSP,
                 MA.EVENT_TYPE_END_TMSP,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) ='OI', MA.EVENT_TYPE_AMT,0)) as OI_ALLOW_AMT,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) <> 'SCAN', MA.EVENT_TYPE_AMT,0)) as ALLOW_AMT,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('PA','PAM'),MA.EVENT_TYPE_AMT,0)) AS RPA,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) in ('OI','PA','PAM'),MA.EVENT_TYPE_AMT,0)) AS ALLOWANCE,
                 SUM(IFF(UPPER(MA.EVENT_TYPE_SHORT_DESC) = 'SCAN', MA.EVENT_TYPE_AMT,0)) as SCAN_ALLOW_AMT
               FROM EDW.PROMOS.MAIN_DEAL_MANAGEMENT DM
                 INNER JOIN EDW.PROMOS.MAIN_ALLOWANCE MA
                    ON DM.DM_MAIN_ID=MA.DM_MAIN_ID
               WHERE
                  DM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
                  AND DM.EXPORT_ACTION<>'D'
                  AND DM.ITEM_REMOVE_TMSP is null
                  AND DM.FACILITY_ID = ('DSD')
                  AND UPPER(MA.EVENT_TYPE_SHORT_DESC) not in ('AF')
                  AND MA.EVENT_TYPE_END_TMSP >= sysdate ()
               GROUP BY
                 DM.FACILITY_ID,
                 DM.ITEM_NBR,
                 DM.OFFER_NBR,
                 MA.EVENT_TYPE_START_TMSP,
                 MA.EVENT_TYPE_END_TMSP) OD
               ON DM.FACILITY_ID = OD.FACILITY_ID
                  and DM.ITEM_NBR = OD.ITEM_NBR
                  and DM.OFFER_NBR <> OD.OFFER_NBR
                  and DATE_TRUNC(Day,MA.EVENT_TYPE_START_TMSP) >= DATE_TRUNC(Day,OD.EVENT_TYPE_START_TMSP)
                  and DATE_TRUNC(Day,MA.EVENT_TYPE_END_TMSP) <= DATE_TRUNC(Day,OD.EVENT_TYPE_END_TMSP)
         WHERE
            DM.DEAL_STATUS_CD IN ('ACCEPT','PROCESS')
            AND DM.EXPORT_ACTION<>'D'
            AND DM.ITEM_REMOVE_TMSP is null
            AND DM.FACILITY_ID = ('DSD')
            AND UPPER(MA.EVENT_TYPE_SHORT_DESC) not in ('AF')
            AND MA.EVENT_TYPE_END_TMSP >= sysdate ()
         GROUP BY
           DM.OFFER_NBR,
           DM.FACILITY_ID,
           DM.PRICE_TYPE_ID,
           DM.UPC_CONSUMER,
           DM.ITEM_REMOVE_TMSP,
           DM.PERFORMANCE_TYPE,
           DM.NON_PROMO_PRICE,
           DM.PACK_CNT,
          DM.DEAL_DESC
        ) DM3
             ON DM3.OFFER_NBR=P.OFFER_NBR
                AND DM3.UPC_CONSUMER= P.UPC  
     WHERE (P.PROD_CHANGE_FLG<>-1 AND P.LOCATION_CHANGE_FLG<>-1 AND P.CHANGE_FLG<>-1) AND P.DTL_TYPE IN (1,5)
      AND E.CHANGE_FLG <> -1
       AND MST.CHANGE_FLG <> -1
       AND EP.CHANGE_FLG <> -1
       AND P.START_DT>SYSDATE()
       AND P.OFFER_NBR is not null) PROMO
     LEFT OUTER JOIN EDW.PROMOS.AD_BOOKING_REF ADB
      ON PROMO.FACILITY_ID = ADB.FACILITY_ID
         and PROMO.EVT_ID = ADB.EVENT_ID
         and PROMO.AD_GRP = CAST(ADB.AD_GRP_NBR AS STRING)

  
UNION
  
  
SELECT DISTINCT
    PROMO.FACILITY_ID,
    PROMO.EVT_NM  as EVENT_NAME,
    PROMO.EVT_DESC as EVENT_DESC,
    PROMO.OFFER_NBR,
    NULL AS DEAL_DESCRIPTION,
    PROMO.LOCATION_GRP_NM,
    PROMO.FISCAL_WEEK AS AD_WEEK,
    PROMO.WEEK_OF_YEAR AS WEEK_NUMBER,
    PROMO.ITEM_NBR AS WRS_Code,
    NULL AS REMOVED_DATE,
    PROMO.UPC AS UPC,
    PROMO.RETAIL_ITEM_DESC AS ITEM_DESC,
    PROMO.PACK AS PACK,
    PROMO.CATALOG_PRICE AS PRICE,
    0 AS OI,
    0 AS RPA,
    0 AS ALLOWANCE,
    PROMO.CATALOG_PRICE as NET_CASE,
    0 AS SCAN,
    0 as NET_UNIT_PRICE,
    IFF(PROMO.DTL_SUB_TYPE in (1,8),PROMO.TPR_AMT,0) as AD_SRP,
    IFF(PROMO.DTL_SUB_TYPE = 8,PROMO.TPR_MULTIPLE_CNT,1) as AD_MULTIPLE,
    CASE
      WHEN RIGHT(UPPER(PROMO.EVT_PG_NM),2)='FP' THEN 'FR'
      WHEN RIGHT(UPPER(PROMO.EVT_PG_NM),2)='BP' THEN 'BK'
      ELSE 'IN'
     END as PAGE,
     PROMO.EVT_PG_NM,
     CASE
        WHEN UPPER(PROMO.AD_POSITION_FRMT_NM) LIKE '%SUBFEATURE' then 'Sub'
        WHEN UPPER(PROMO.AD_POSITION_FRMT_NM) LIKE '%FEATURE' then 'Feat'
        ELSE 'Sub'
      END as AD_POS,
      CASE
        WHEN Trim(UPPER(PROMO.MERCH_DEPT_DESC)) = 'DAIRY' THEN 'D'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) = 'FROZEN' THEN 'F'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) like 'GROCERY%' THEN 'G'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) =  'MEAT' THEN 'M'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) =  'SEAFOOD' THEN 'S'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) = 'DELI' THEN 'DL'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) = 'BAKERY' THEN 'B'
        WHEN TRIM(UPPER(PROMO.MERCH_DEPT_DESC)) = 'PRODUCE' THEN 'P'
      ELSE 'HBC'
    END AS DEPT_CODE,
    PROMO.MERCH_DEPT_DESC,
    PROMO.ITEM_SIZE AS SIZE,
    PROMO.ITEM_SIZE_UOM AS UOM,
    0 AS REG_SRP,
    NULL AS FS,
    PROMO.DTL_SUB_TYPE,
    PROMO.PROMO_DESC as EVENT_NOTE,
   IFF(cast(PROMO.STOCK_FAC as Integer)!=cast(PROMO.FACILITY_ID as Integer), 'U',NULL) as WRS_FLG
   ,PROMO.SRC_PROMO_ID
   ,PROMO.STORE_NOTE
   ,ADB.AD_BOOKING_NBR
  FROM
   (SELECT DISTINCT P.UPC
       ,P.OFFER_NBR
       ,P.PROMO_DESC
       ,IFF(AC.AD_GRP is not null, AC.ALL_AD_GRP,P.AD_GRP) as AD_GRP
       ,E.EVT_ID
       ,E.START_DT
       ,E.END_DT
       ,P.DTL_SUB_TYPE
       ,P.TPR_AMT
       ,P.TPR_MULTIPLE_CNT
       ,IFF(ND1.FACILITY_ID is not null,ND1.FACILITY_ID,IFF(ND2.FACILITY_ID is not null, '054'
               ,IFF(ND3.FACILITY_ID is not null, '003',FC.HOME_BRANCH))) as FACILITY_ID
       ,IFF(AC.ALL_AD_GRP = '999999', 'ALL CUSTOMERS - 999999',P.LOCATION_GRP_NM) as LOCATION_GRP_NM
       ,P.LOCATION_GRP_ID
       ,AP.AD_POSITION_FRMT_NM
       ,E.EVT_NM
       ,E.EVT_DESC
       ,EP.EVT_PG_NM
       ,DD.FISCAL_WEEK
       ,DD.WEEK_OF_YEAR
       ,IFF(ND1.FACILITY_ID is not null,ND1.ITEM_NBR_HS,IFF(ND2.FACILITY_ID is not null, ND2.ITEM_NBR_HS
               ,IFF(ND3.FACILITY_ID is not null, ND3.ITEM_NBR_HS,IFF(ND4.FACILITY_ID is null, 'DSD',NULL)))) as ITEM_NBR
       ,IFF(ND1.FACILITY_ID is not null,ND1.ITEM_DESCRIP,IFF(ND2.FACILITY_ID is not null, ND2.ITEM_DESCRIP
               ,IFF(ND3.FACILITY_ID is not null, ND3.ITEM_DESCRIP,IFF(ND4.FACILITY_ID is null, 'DSD',NULL)))) as RETAIL_ITEM_DESC
                   ,IFF(ND1.FACILITY_ID is not null,ND1.ARTULUL_SPCK_ALLCOEFF,IFF(ND2.FACILITY_ID is not null, ND2.ARTULUL_SPCK_ALLCOEFF
               ,IFF(ND3.FACILITY_ID is not null, ND3.ARTULUL_SPCK_ALLCOEFF,NULL))) as PACK 
       ,IFF(ND1.FACILITY_ID is not null,ND1.ITEM_SIZE,IFF(ND2.FACILITY_ID is not null, ND2.ITEM_SIZE
               ,IFF(ND3.FACILITY_ID is not null, ND3.ITEM_SIZE,NULL))) as ITEM_SIZE
       ,IFF(ND1.FACILITY_ID is not null,ND1.ITEM_SIZE_UOM,IFF(ND2.FACILITY_ID is not null, ND2.ITEM_SIZE_UOM
               ,IFF(ND3.FACILITY_ID is not null, ND3.ITEM_SIZE_UOM,NULL))) as ITEM_SIZE_UOM
       ,IFF(ND1.FACILITY_ID is not null,ND1.MERCH_DEPT_DESC,IFF(ND2.FACILITY_ID is not null, ND2.MERCH_DEPT_DESC
               ,IFF(ND3.FACILITY_ID is not null, ND3.MERCH_DEPT_DESC,IFF(ND4.FACILITY_ID is null, 'DSD',NULL)))) as MERCH_DEPT_DESC
       ,IFF(ND1.FACILITY_ID is not null,ND1.CATALOG_PRICE,IFF(ND2.FACILITY_ID is not null, ND2.CATALOG_PRICE
               ,IFF(ND3.CATALOG_PRICE is not null, ND3.CATALOG_PRICE,NULL))) as CATALOG_PRICE
       ,IFF(ND1.FACILITY_ID is not null,ND1.STOCK_FAC,IFF(ND2.FACILITY_ID is not null, ND2.STOCK_FAC
               ,IFF(ND3.FACILITY_ID is not null, ND3.STOCK_FAC,NULL))) as STOCK_FAC
       ,P.SRC_PROMO_ID
       ,NT.LONG_COMMENTS_1 as STORE_NOTE
   FROM EDW.PROMOS.PERFORMANCE P
   INNER JOIN EDW.FD.FD_CUSTOMER_VW FC
         ON P.CUSTOMER_LOCATION_KEY= CAST(FC.CUSTOMER_NO as INTEGER)
            AND FC.MDM_CUST_STATUS_CD IN (1,5,7)
            and P.START_DT between FC.START_DT AND FC.END_DT
            AND FC.HOME_BRANCH<>'001'
    LEFT OUTER JOIN EDW.PROMOS.PERFORMANCE NT
       ON P.SRC_PROMO_ID = NT.SRC_PROMO_ID
          and P.DTL_GRP_SRC_ID=NT.DTL_GRP_SRC_ID
          and P.CUSTOMER_LOCATION_KEY = NT.CUSTOMER_LOCATION_KEY
          and P.UPC=NT.UPC
          and NT.LONG_COMMENTS_1 is not null
    INNER JOIN (SELECT SRC_PROMO_ID,SRC_PERF_DTL_GRP_ID,SRC_PERF_DTL_ID,EVT_ID,EVT_PG_ID
                     ,SEGMNT_ID,AD_POSITION_NBR,AD_POSITION_FRMT_NM,PRICE_FRMT_NM
                  FROM EDW.PROMOS.EVENT_PAGE_AD_POSITION
                    WHERE CHANGE_FLG <> -1
                  UNION
                  SELECT SRC_PROMO_ID,SRC_PERF_DTL_GRP_ID, SRC_PERF_DTL_ID,EVT_ID,EVT_PG_ID,SEGMNT_ID,
                     AD_POSITION_NBR,AD_POSITION_FRMT_NM,PRICE_FRMT_NM
                  FROM EDW.PROMOS.PERFORMANCE_GRP
               WHERE CHANGE_FLG <> -1) AP
         ON P.SRC_PROMO_ID=AP.SRC_PROMO_ID AND P.DTL_GRP_SRC_ID=AP.SRC_PERF_DTL_GRP_ID
            AND P.SRC_DTL_ID=AP.SRC_PERF_DTL_ID
      INNER JOIN  EDW.PROMOS.EVENT E
         ON E.EVT_ID=AP.EVT_ID
      INNER JOIN EDW.PROMOS.MRKT_SEGMNT_STORE MST
         ON MST.SEGMNT_ID=AP.SEGMNT_ID AND MST.STORE_NBR=P.CUSTOMER_LOCATION_KEY
      INNER JOIN EDW.PROMOS.EVENT_PAGE EP
         ON EP.EVT_ID=ap.EVT_ID
            and EP.EVT_PG_ID=AP.EVT_PG_ID
      INNER JOIN EDW.MDM.DATE_DIM_VW DD
         ON DD.FULL_DATE=P.START_DT

      LEFT OUTER JOIN EDW.PROMOS.AD_GRP_ALL_CUST AC
         ON TRY_TO_NUMBER(P.AD_GRP)=AC.AD_GRP

    
     LEFT OUTER JOIN
        (SELECT distinct
           LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0') as FACILITY_ID,
           FID.ITEM_NBR_HS,
           FID.UPC_UNIT,
           FID.START_DT,
           FID.END_DT,
          GD.ARTULUL_SPCK_ALLCOEFF ,
           FID.AVAILABILITY_DATE,
           FID.BRAND,
           FID.MERCH_DEPT,
           FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           IFF(SF.SALES_PLAN_SELL is not null, SF.SALES_PLAN_SELL,SC.SALES_PLAN_SELL) AS CATALOG_PRICE,
           FID.MASTER_PACK,
           FID.PRIVATE_LABEL_KEY,
           FID.SHIP_UNIT_CD,
           FID.ITEM_SIZE,
           FID.ITEM_DEPT_OVERRIDE,
           FID.ITEM_SIZE_UOM,
           FID.STOCK_FAC,
           SF.SELL_PRICE_EFF_DATE
         FROM EDW.FD.FD_ITEM_VW FID
           INNER JOIN EDL.GOLD.NF_ITEM GD
                        ON LPAD(GD.ISI_DC_CODE,3,0)=LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0')
                        AND RIGHT(GD.ISI_ITEM_CODE,6)=FID.ITEM_NBR
           INNER JOIN EDL.CRM.T_WHSE_SELL_CURRENT SC
              ON FID.FACILITY_ID = CAST(SC.FACILITYID AS NUMBER)
                and FID.ITEM_NBR_HS = SC.ITEM_NBR_HS
                and SC.SALES_PLAN = 2
           LEFT OUTER JOIN EDL.CRM.T_WHSE_SELL SF
              ON FID.FACILITY_ID = CAST(SF.FACILITYID AS NUMBER)
                 and FID.ITEM_NBR_HS = SF.ITEM_NBR_HS
                 and SF.SALES_PLAN = 2
                 and SF.SELL_PRICE_EFF_DATE > SC.SELL_PRICE_EFF_DATE
         WHERE
            FID.FACILITY_ID <> 1) ND1
             ON CAST(ND1.UPC_UNIT AS NUMBER)= CAST(P.UPC AS NUMBER)   
                and LPAD(CAST(ND1.FACILITY_ID AS STRING),3,'0') = FC.HOME_BRANCH
                and ND1.SELL_PRICE_EFF_DATE <= P.START_DT
                and P.START_DT between ND1.START_DT and ND1.END_DT
      LEFT OUTER JOIN
        (SELECT distinct
           LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0') as FACILITY_ID,
           FID.ITEM_NBR_HS,
           FID.UPC_UNIT,
           FID.START_DT,
           FID.END_DT,
           GD.ARTULUL_SPCK_ALLCOEFF,
           FID.AVAILABILITY_DATE,
           FID.BRAND,
           FID.MERCH_DEPT,
           FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           IFF(SF.SALES_PLAN_SELL is not null, SF.SALES_PLAN_SELL,SC.SALES_PLAN_SELL) AS CATALOG_PRICE,
           FID.MASTER_PACK,
           FID.PRIVATE_LABEL_KEY,
           FID.SHIP_UNIT_CD,
           FID.ITEM_SIZE,
           FID.ITEM_DEPT_OVERRIDE,
           FID.ITEM_SIZE_UOM,
           FID.STOCK_FAC,
           SF.SELL_PRICE_EFF_DATE
         FROM EDW.FD.FD_ITEM_VW FID
           INNER JOIN EDL.GOLD.NF_ITEM GD
              ON LPAD(GD.ISI_DC_CODE,3,0)=LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0')
                 AND RIGHT(GD.ISI_ITEM_CODE,6)=FID.ITEM_NBR
           INNER JOIN EDL.CRM.T_WHSE_SELL_CURRENT SC
              ON FID.FACILITY_ID = CAST(SC.FACILITYID AS NUMBER)
                and FID.ITEM_NBR_HS = SC.ITEM_NBR_HS
                and SC.SALES_PLAN = 2
           LEFT OUTER JOIN EDL.CRM.T_WHSE_SELL SF
              ON FID.FACILITY_ID = CAST(SF.FACILITYID AS NUMBER)
                 and FID.ITEM_NBR_HS = SF.ITEM_NBR_HS
                 and SF.SALES_PLAN = 2
                 and SF.SELL_PRICE_EFF_DATE > SC.SELL_PRICE_EFF_DATE
          WHERE
            FACILITY_ID = 54) ND2
       ON CAST(ND2.UPC_UNIT AS NUMBER)= CAST(P.UPC AS NUMBER)   
          and ND2.SELL_PRICE_EFF_DATE <= P.START_DT
          and P.START_DT between ND2.START_DT and ND2.END_DT
          and FC.HOME_BRANCH not in ('015','058')

    LEFT OUTER JOIN 
        (SELECT distinct
           LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0') as FACILITY_ID,
           FID.ITEM_NBR_HS,
           FID.UPC_UNIT,
           FID.START_DT,
           FID.END_DT,
           GD.ARTULUL_SPCK_ALLCOEFF ,
           FID.AVAILABILITY_DATE,
           FID.BRAND,
           FID.MERCH_DEPT,
          FID.MERCH_DEPT_DESC,
           FID.ITEM_DESCRIP,
           IFF(SF.SALES_PLAN_SELL is not null, SF.SALES_PLAN_SELL,SC.SALES_PLAN_SELL) AS CATALOG_PRICE,
           FID.MASTER_PACK,
           FID.PRIVATE_LABEL_KEY,
           FID.SHIP_UNIT_CD,
           FID.ITEM_SIZE,
           FID.ITEM_DEPT_OVERRIDE,
           FID.ITEM_SIZE_UOM,
           FID.STOCK_FAC,
           SF.SELL_PRICE_EFF_DATE
         FROM EDW.FD.FD_ITEM_VW FID
           INNER JOIN EDL.GOLD.NF_ITEM GD
              ON LPAD(GD.ISI_DC_CODE,3,0)=LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0')
              AND RIGHT(GD.ISI_ITEM_CODE,6)=FID.ITEM_NBR
           INNER JOIN EDL.CRM.T_WHSE_SELL_CURRENT SC
              ON FID.FACILITY_ID = CAST(SC.FACILITYID AS NUMBER)
                and FID.ITEM_NBR_HS = SC.ITEM_NBR_HS
                and SC.SALES_PLAN = 2
           LEFT OUTER JOIN EDL.CRM.T_WHSE_SELL SF
              ON FID.FACILITY_ID = CAST(SF.FACILITYID AS NUMBER)
                 and FID.ITEM_NBR_HS = SF.ITEM_NBR_HS
                 and SF.SALES_PLAN = 2
                 and SF.SELL_PRICE_EFF_DATE > SC.SELL_PRICE_EFF_DATE
          WHERE
            FID.FACILITY_ID = 3) ND3
       ON CAST(ND3.UPC_UNIT AS NUMBER)= CAST(P.UPC AS NUMBER)   
          and ND3.SELL_PRICE_EFF_DATE <= P.START_DT
          and FC.HOME_BRANCH not in ('015','058')
          and P.START_DT between ND3.START_DT and ND3.END_DT
          and TRIM(UPPER(ND3.MERCH_DEPT_DESC)) in ('PRODUCE', 'FLORAL')
      LEFT OUTER JOIN 
        (SELECT distinct
           LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0') as FACILITY_ID,
           FID.ITEM_NBR_HS,
           FID.UPC_UNIT,
           FID.START_DT,
           FID.END_DT,
          GD.ARTULUL_SPCK_ALLCOEFF ,
           FID.AVAILABILITY_DATE,
           FID.BRAND,
           FID.MERCH_DEPT,
           FID.MERCH_DEPT_DESC,
          FID.ITEM_DESCRIP,
           IFF(SF.SALES_PLAN_SELL is not null, SF.SALES_PLAN_SELL,SC.SALES_PLAN_SELL) AS CATALOG_PRICE,
           FID.MASTER_PACK,
           FID.PRIVATE_LABEL_KEY,
           FID.SHIP_UNIT_CD,
           FID.ITEM_SIZE,
           FID.ITEM_DEPT_OVERRIDE,
           FID.ITEM_SIZE_UOM,
           FID.STOCK_FAC,
           SF.SELL_PRICE_EFF_DATE
         FROM EDW.FD.FD_ITEM_VW FID
           INNER JOIN EDL.GOLD.NF_ITEM GD
              ON LPAD(GD.ISI_DC_CODE,3,0)=LPAD(CAST(FID.FACILITY_ID AS STRING),3,'0')
              AND RIGHT(GD.ISI_ITEM_CODE,6)=FID.ITEM_NBR
           INNER JOIN EDL.CRM.T_WHSE_SELL_CURRENT SC
              ON FID.FACILITY_ID = CAST(SC.FACILITYID AS NUMBER)
                and FID.ITEM_NBR_HS = SC.ITEM_NBR_HS
                and SC.SALES_PLAN = 2
           LEFT OUTER JOIN EDL.CRM.T_WHSE_SELL SF
              ON FID.FACILITY_ID = CAST(SF.FACILITYID AS NUMBER)
                 and FID.ITEM_NBR_HS = SF.ITEM_NBR_HS
                 and SF.SALES_PLAN = 2
                 and SF.SELL_PRICE_EFF_DATE > SC.SELL_PRICE_EFF_DATE
         WHERE
           FID.FACILITY_ID <> '001') ND4
     ON CAST(ND4.UPC_UNIT AS NUMBER)= CAST(P.UPC AS NUMBER) 
        and ND4.SELL_PRICE_EFF_DATE <= P.START_DT
        and P.START_DT between ND4.START_DT and ND3.END_DT
  WHERE 
     (P.PROD_CHANGE_FLG<>-1 AND P.LOCATION_CHANGE_FLG<>-1 AND P.CHANGE_FLG<>-1) AND P.DTL_TYPE IN (1,5)
    AND E.CHANGE_FLG <> -1
      AND MST.CHANGE_FLG <> -1
      AND EP.CHANGE_FLG <> -1
     AND P.START_DT>SYSDATE()
     AND P.OFFER_NBR is null ) PROMO

   LEFT OUTER JOIN EDW.PROMOS.AD_BOOKING_REF ADB
      ON PROMO.FACILITY_ID = ADB.FACILITY_ID
         and PROMO.EVT_ID = ADB.EVENT_ID
         and PROMO.AD_GRP = CAST(ADB.AD_GRP_NBR AS STRING)

)PR);