Select FACILITYID , INVOICE_NBR , BILLING_DATE , CUSTOMER_NO_FULL , STORE_STATE, UPC_CASE, ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , FINAL_SELL_AMT, LBL_CASE_CHRGE, PRICE_ADJUSTMENT, LEAKAGE_AMT, STATE_EXCISE_TAX, COUNTY_EXCISE_TAX, CITY_EXCISE_TAX, OTHER_EXCISE_TAX_01, OTHER_EXCISE_TAX_02, OTHER_EXCISE_TAX_03
from CRMADMIN.T_WHSE_SALES_HISTORY_DTL
where FACILITYID = '054'
and ITEM_DEPT = '055'
and UPC_CASE = '00000004210001871'
and STORE_STATE in ('NE')
and BILLING_DATE between '2018-04-10' and current date
;

Select FACILITYID , INVOICE_NBR , BILLING_DATE , CUSTOMER_NO_FULL , STORE_STATE, UPC_CASE, ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , FINAL_SELL_AMT, LBL_CASE_CHRGE, PRICE_ADJUSTMENT, LEAKAGE_AMT, STATE_EXCISE_TAX, COUNTY_EXCISE_TAX, CITY_EXCISE_TAX, OTHER_EXCISE_TAX_01, OTHER_EXCISE_TAX_02, OTHER_EXCISE_TAX_03
from CRMADMIN.T_WHSE_SALES_HISTORY_DTL
where FACILITYID = '066'
and ITEM_DEPT = '055'
and UPC_CASE = '00000004210001871'
and STORE_STATE in ('NE')
and BILLING_DATE between '2018-04-10' and current date
; 

select FACILITYID, ITEM_NBR_HS, ITEM_DESCRIPTION, FINAL_SELL_AMT from CRMADMIN.T_WHSE_SALES_HISTORY_DTL where FACILITYID = '054' and INVOICE_NBR = 70290 ;

select FACILITYID, ITEM_NBR_HS, ITEM_DESCRIPTION, FINAL_SELL_AMT from CRMADMIN.T_WHSE_SALES_HISTORY_DTL where FACILITYID = '066' and INVOICE_NBR = 1693978 ;

select FACILITYID, ITEM_NBR_HS, ITEM_DESCRIPTION, FINAL_SELL_AMT from CRMADMIN.T_WHSE_SALES_HISTORY_DTL where FACILITYID = '058' and INVOICE_NBR = 2200842;

select INVOICE_NBR,  FACILITYID, ITEM_NBR_HS, ITEM_DESCRIPTION, FINAL_SELL_AMT from CRMADMIN.T_WHSE_SALES_HISTORY_DTL where FACILITYID = '058' and ITEM_DEPT = '055' and BILLING_DATE between '2018-04-08' and '2018-04-14' and TERRITORY_NO in (21, 27, 31) ;
-- INVOICE_NBR = 1693978 ;