SELECT FACILITYID, ITEM_DEPT, CUST_OVRRDE_RTL_DEPT, sum(QTY_SOLD)
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
where TERRITORY_NO in (21, 27, 31)
and FACILITYID in ('040', '008', '003', '005', '058')
and BILLING_DATE > '2017-10-01'
group by FACILITYID, ITEM_DEPT, CUST_OVRRDE_RTL_DEPT
;


select FACILITYID, ITEM_DEPT, SUPPLY_FLAG, RETAIL_DEPT,  count(*) item_count
from CRMADMIN.T_WHSE_ITEM
where PURCH_STATUS not in ('D', 'Z')
and FACILITYID in ('058') --'040', '008', '003', '005', 
and (ITEM_DEPT = '040' or RETAIL_DEPT = '40')
group by FACILITYID, ITEM_DEPT, SUPPLY_FLAG, RETAIL_DEPT
;


select FACILITYID, ITEM_DEPT, SUPPLY_FLAG,  count(*)
from CRMADMIN.T_WHSE_ITEM
where PURCH_STATUS not in ('D', 'Z')
group by FACILITYID, ITEM_DEPT, SUPPLY_FLAG
;



select FACILITYID, ITEM_NBR_HS,  ITEM_DESCRIP, UPC_UNIT, UPC_CASE, ITEM_DEPT, RETAIL_DEPT, SUPPLY_FLAG
from CRMADMIN.T_WHSE_ITEM
where PURCH_STATUS not in ('D', 'Z')
and FACILITYID in ('001') --('058', '003', '005', '008' , '040')
and (SUPPLY_FLAG = 'Y' or ITEM_DEPT = '040' or RETAIL_DEPT in ('40', '41', '42', '43', '44', '45', '46', '47', '48', '49'))
--group by FACILITYID, ITEM_DEPT, SUPPLY_FLAG
;