--Item Components
SELECT   oi.ORDERABLE_ITEM_KEY,
         oi.ORD_ITEM_CODE as COMP_ORD_ITEM_CODE,
         oi.SHIP_CASE_CNT as COMP_SHIP_CASE_CNT,
         oi.PRICE_WEIGHT_MSR as COMP_PRICE_WEIGHT_MSR,
         oi.PSEUDO_UPC_NBR as COMP_PSEUDO_UPC_NBR,
         RTRIM(ri.RETAIL_ITEM_DSC) as COMP_RETAIL_ITEM_DSC,
         ri.UNIT_UPC_CD as COMP_UNIT_UPC_CD,
         ri.PLU_CD as COMP_PLU_CD,
         ri.SIZE_MSR as COMP_SIZE_MSR,
         ri.SIZE_UOM_CD as COMP_SIZE_UOM_CD,
         ori.ITEM_PACK_QTY as COMP_ITEM_PACK_QTY,
         oip.COSTPLUS_APPLY_FLG as COMP_COSTPLUS_APPLY_FLG,
         oip.PRICE_AMT as COMP_PRICE_AMT,
         sc.COMMODITY_CODE as COMP_COMMODITY_CODE,
         RTRIM(ib.ITEM_BRAND_DESC) as COMP_ITEM_BRAND_DESC,
         suc.UNIT_COST_AMT as COMP_UNIT_COST_AMT
FROM     PRODDB2.ORDERABLE_ITEM oi,
         PRODDB2.ORD_RETAIL_ITEM ori,
         PRODDB2.RETAIL_ITEM ri,
         PRODDB2.ITEM_BRAND ib,
         PRODDB2.SPTN_COMMODITY sc,
         PRODDB2.STORE_UNIT_COST suc,
         PRODDB2.ORD_ITEM_PRICE oip
WHERE    oi.ORDERABLE_ITEM_KEY = ori.ORDERABLE_ITEM_KEY
AND      oi.ORDERABLE_ITEM_KEY = oip.ORDERABLE_ITEM_KEY
AND      ori.RETAIL_ITEM_KEY = ri.RETAIL_ITEM_KEY
AND      ri.ITEM_BRAND_KEY = ib.ITEM_BRAND_KEY
AND      oi.COMMODITY_KEY = sc.COMMODITY_KEY
AND      ori.MF_MASTER_FLG = 'N'
AND      oi.ITEM_COMPLETE_FLG = 'Y'
AND      ori.ORD_RTL_ITEM_KEY = suc.ORD_RTL_ITEM_KEY
AND      oip.ORD_ITEM_PRICE_KEY = suc.ORD_ITEM_PRICE_KEY
AND      oip.STAT_CODE = 'A'
AND      oip.PRICE_TYPE_CD IN ('01')
AND      ((DATE(oip.EFFECTIVE_DATE)<= CURRENT_DATE
        AND DATE(oip.EXPIRATION_DATE) > CURRENT_DATE)
     OR  (DATE(oip.EFFECTIVE_DATE)<= CURRENT_DATE
        AND oip.EXPIRATION_DATE is NULL)
     OR  (DATE(oip.EXPIRATION_DATE) > CURRENT_DATE))
ORDER BY oi.ORDERABLE_ITEM_KEY, COMP_UNIT_UPC_CD