SELECT   Distinct T_WHSE_USER.LEAD_USER LEAD_USER,
         T_WHSE_ITEM.BUYER_NBR BUYER_NBR,
         T_WHSE_DIV_XREF.SWAT_ID FACILITYID,
         T_WHSE_ITEM.ITEM_NBR ITEM_NBR,
         T_WHSE_ITEM.ITEM_NBR_HS ITEM_NBR_HS,
         T_WHSE_ITEM.ROOT_ITEM_NBR ROOT_ITEM_NBR,
         T_WHSE_ITEM.LV_ITEM_NBR LV_ITEM_NBR,
         T_WHSE_ITEM.LV_DESC LV_DESC,
         T_WHSE_ITEM.PURCH_STATUS PURCH_STATUS,
         T_WHSE_ITEM.BILLING_STATUS BILLING_STATUS,
         T_WHSE_ITEM.UPC_CASE UPC_CASE,
         T_WHSE_ITEM.UPC_UNIT UPC_UNIT,
         T_WHSE_DEAL.ADD_DATE ADD_DATE,
         T_WHSE_DEAL.DATE_DEAL_ARRIVE DATE_DEAL_ARRIVE,
         T_WHSE_DEAL.REMRK REMRK,
         T_WHSE_DEAL.REMRK_2 REMRK_2,
         T_WHSE_DEAL.REMRK_3 REMRK_3,
         T_WHSE_DEAL.PROMO_QTY PROMO_QTY,
         T_WHSE_DEPT.DEPT_CODE ITEM_DEPT,
         T_WHSE_DEPT.DEPT_DESCRIPTION DEPT_DESCRIPTION,
         T_WHSE_ITEM.PRODUCT_GROUP PRODUCT_GROUP,
         T_WHSE_ITEM.CASES_PER_WEEK FCST_CASES_PER_WEEK,
         T_WHSE_ITEM.INVENTORY_TOTAL INVENTORY_TOTAL,
         T_WHSE_ITEM.ON_ORDER_TOTAL ON_ORDER_TOTAL,
         T_WHSE_ITEM.RESERVE_COMMITTED RESERVE_COMMITTED,
         T_WHSE_ITEM.RESERVE_UNCOMMITTED RESERVE_UNCOMMITTED
FROM     (((CRMADMIN.T_WHSE_DEPT T_WHSE_DEPT 
         inner join CRMADMIN.T_WHSE_ITEM T_WHSE_ITEM on T_WHSE_DEPT.DEPT_CODE = T_WHSE_ITEM.ITEM_DEPT) 
         inner join ( select T_WHSE_DIV_XREF.SWAT_ID SWAT_ID from CRMADMIN.T_WHSE_DIV_XREF T_WHSE_DIV_XREF where T_WHSE_DIV_XREF.ENTERPRISE_KEY = 1) T_WHSE_DIV_XREF on T_WHSE_DIV_XREF.SWAT_ID = T_WHSE_ITEM.FACILITYID) 
         inner join CRMADMIN.T_WHSE_USER T_WHSE_USER on T_WHSE_ITEM.BUYER_NBR = T_WHSE_USER.BUYER_NBR) 
         LEFT OUTER JOIN CRMADMIN.T_BICEPS_DEAL_2017 T_WHSE_DEAL on T_WHSE_ITEM.FACILITYID = T_WHSE_DEAL.FACILITYID and T_WHSE_ITEM.ITEM_NBR_CD = T_WHSE_DEAL.ITEM_NBR
WHERE    T_WHSE_DEAL.DATE_DEAL_ARRIVE between '2017-01-01' and '2017-12-31'
AND      T_WHSE_DEAL.PROMO_QTY > '0'
AND      T_WHSE_DIV_XREF.SWAT_ID = '001'
AND      NOT T_WHSE_USER.BUYER_NBR is null FOR FETCH ONLY