--------------------------------------------------
-- Create View CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK
--------------------------------------------------
--drop view CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK;
CREATE VIEW CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK AS (  

SELECT   A.FACILITYID,
         A.ITEM_NBR_CD,
         SUBSTR(A.UPC_UNIT,2,16) AS UPC_UNIT,
         SUBSTR(A.UPC_CASE,2,16) AS UPC_CASE,
         A.ITEM_DESCRIP,
         A.PACK_CASE,
         A.ITEM_SIZE,
         A.ITEM_SIZE_UOM,
         SUM(CASE WHEN SHD.DATE_WEEK_END BETWEEN (CURRENT DATE - 364 DAYS) AND (CURRENT DATE - 1 DAYS) THEN SHD.TOT_EXT_PURE_SALES - MILITARY_TOT_EXT_PURE_SALES - CENTRALBILL_TOT_EXT_PURE_SALES ELSE 0 END) AS CY52_DOLLAR_MOVEMENT,
         SUM(CASE WHEN SHD.DATE_WEEK_END BETWEEN (CURRENT DATE - 364 DAYS) AND (CURRENT DATE - 1 DAYS) THEN SHD.TOT_SHIPPED - MILITARY_TOT_SHIPPED - CENTRALBILL_TOT_SHIPPED ELSE 0 END) AS CY52_CASE_MOVEMENT,
         SUM(CASE WHEN SHD.DATE_WEEK_END BETWEEN (CURRENT DATE - 728 DAYS) AND (CURRENT DATE - 365 DAYS) THEN SHD.TOT_EXT_PURE_SALES - MILITARY_TOT_EXT_PURE_SALES - CENTRALBILL_TOT_EXT_PURE_SALES ELSE 0 END) AS LY52_DOLLAR_MOVEMENT,
         SUM(CASE WHEN SHD.DATE_WEEK_END BETWEEN (CURRENT DATE - 728 DAYS) AND (CURRENT DATE - 365 DAYS) THEN SHD.TOT_SHIPPED - MILITARY_TOT_SHIPPED - CENTRALBILL_TOT_SHIPPED ELSE 0 END) AS LY52_CASE_MOVEMENT,
         A.CAT_HDG,
         A.ITEM_DEPT,
         A.PURCH_STATUS,
         A.BILLING_STATUS,
         A.BRAND,
         A.MANUFACTURER_NUMBER,
         A.SKU_CASE_HEIGHT,
         A.SKU_CASE_WIDTH,
         A.SKU_CASE_LENGTH,
         A.FIRST_RECEIVED_DATE,
         A.PRODUCT_GROUP,
         COALESCE(B.PROD_GROUP_DESC,'UNKNOWN') AS PROD_GROIUP_DESC,
         A.PRODUCT_SUB_GROUP,
         COALESCE(C.PROD_SUBGROUP_DESC, 'UNKNOWN') AS PROD_SUBGROUP_DESC,
         A.NA_TO_TAG,
         A.LIST_COST,
         A.CATALOG_PRICE,
         A.SUB_ITEM_NBR,
         A.MILITARY_ID,
         COALESCE(V.VENDOR_NAME,'UNKNOWN') AS VENDOR_NAME,
         A.VENDOR_NBR,
         DECIMAL((SUM(CASE WHEN SHD.DATE_WEEK_END BETWEEN (CURRENT DATE - 364 DAYS) AND (CURRENT DATE - 1 DAYS) THEN SHD.TOT_SHIPPED- MILITARY_TOT_SHIPPED- CENTRALBILL_TOT_SHIPPED ELSE 0 END) * A.PACK_CASE) / 52.0,31,4) AS CY52_AVG_WKLY_UNIT_MOVEMENT
FROM     CRMADMIN.T_WHSE_ITEM A 
         LEFT OUTER JOIN CRMADMIN.T_WHSE_PROD_GROUP B ON A.FACILITYID=B.FACILITY AND A.PRODUCT_GROUP=B.PROD_GROUP 
         LEFT OUTER JOIN CRMADMIN.T_WHSE_PROD_SUBGROUP C ON A.FACILITYID=C.FACILITY AND A.PRODUCT_GROUP=C.PROD_GROUP AND A.PRODUCT_SUB_GROUP=C.PROD_SUBGROUP 
         INNER JOIN CRMADMIN.T_WHSE_SALES_HST_SMRY_WKLY SHD ON A.FACILITYID=SHD.FACILITYID AND A.ITEM_NBR_HS=SHD.ITEM_NBR_HS 
         LEFT OUTER JOIN CRMADMIN.T_WHSE_VENDOR V ON A.FACILITYID=V.FACILITYID AND A.VENDOR_NBR=V.VENDOR_NBR 
         INNER JOIN CRMADMIN.T_DATE D ON SHD.DATE_WEEK_END=D.DATE_KEY
WHERE    D.DATE_KEY BETWEEN (CURRENT DATE - 728 DAYS) AND (CURRENT DATE - 1 DAYS)
GROUP BY A.FACILITYID, A.ITEM_NBR_CD, A.UPC_UNIT, A.UPC_CASE, A.ITEM_DESCRIP, 
         A.PACK_CASE, A.ITEM_SIZE, A.ITEM_SIZE_UOM, A.CAT_HDG, A.ITEM_DEPT, 
         A.PURCH_STATUS, A.BILLING_STATUS, A.BRAND, A.MANUFACTURER_NUMBER, 
         A.SKU_CASE_HEIGHT, A.SKU_CASE_WIDTH, A.SKU_CASE_LENGTH, 
         A.FIRST_RECEIVED_DATE, A.PRODUCT_GROUP, 
         COALESCE(B.PROD_GROUP_DESC,'UNKNOWN'), A.PRODUCT_SUB_GROUP, 
         COALESCE(C.PROD_SUBGROUP_DESC, 'UNKNOWN'), A.NA_TO_TAG, A.LIST_COST, 
         A.CATALOG_PRICE, A.SUB_ITEM_NBR, A.MILITARY_ID, 
         COALESCE(V.VENDOR_NAME,'UNKNOWN'), A.VENDOR_NBR


);




--------------------------------------------------
-- Grant Authorities for CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK
--------------------------------------------------
grant select,update,insert,delete on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user CRMEXPLN;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB102019;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB102139;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB102145;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB102518;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB102925;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB103310;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB103337;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB103416;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB103570;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB103665;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB103707;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB103712;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB103724;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB105018;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB105703;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB106125;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB106139;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB106453;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB108245;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB111676;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB139408;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB139625;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB142088;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB142672;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB143866;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB144227;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB144274;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB144365;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB145955;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB146729;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB148781;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB148925;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB151462;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB151483;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB152530;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB153050;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB153345;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB157558;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB159999;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user DB2INST1 with grant option;
grant select,update,insert,delete on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user ETL;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user ETLX;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user MDM;
grant select on CRMADMIN.V_WHSE_ITEM_SALES_HISTORY_SUM_WK to user WEB;