Select DHI_ITEM_FACILITY, DHI_ITEM_NUMBER, DHI_ITEM_DESCRIPTION, DHI_ITEM_DEPARTMENT, DHI_MASTER_PACK, DHI_STORE_PACK, DHI_RETAIL_PACK, DHI_ITEM_SIZE, DHI_ITEM_SIZE_UNIT_MEASURE, DHI_VENDOR_TIE, DHI_VENDOR_TIER, DHI_WHSE_TIE, DHI_WHSE_TIER, DINITM_WEIGHT, DINITM_CUBE, DINCST_MEAT_CLASS, DINCST_NET_WEIGHT, DHI_ITEM_ADDED_DATE, DHI_INVENTORY_TOTAL

from DATAWHSE.MF_ITEM_MASTER 

where  DINCST_NET_WEIGHT = ? and DHI_ITEM_DEPARTMENT in ('70', '73') and DHI_STATUS not in ('D') 
  and DHI_ITEM_FACILITY in ('01', '02', '03', '05', '08','09', '40')-- and substr(DHI_ITEM_ADDED_DATE, 5,2) = 12
  and DHI_MILITARY_IND not in ('M')