SELECT   OFFER,
         FACILITYID,
         ITEM_NBR_HS,
         ALLOW_DATE_EFF,
         ALLOW_DATE_EXP,
         ALLOW_AMT,
         ALLOW_STATUS
FROM     CRMADMIN.T_WHSE_ALLOWANCES
WHERE    ITEM_NBR_HS = '0286823'
AND      FACILITYID = '058'
AND      ALLOW_TYPE = 'VENDRPA';

SELECT   FACILITYID,
         INVOICE_NBR,
         ITEM_NBR_HS,
         ITEM_DESCRIPTION,
         BILLING_DATE,
         VEND_RPA_AMT_EXT
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    BILLING_DATE between '2015-01-03' and '2015-01-31'
AND      ITEM_NBR_HS = '0286823'
AND      FACILITYID = '058'
AND      VEND_RPA_AMT_EXT <> 0;


SELECT   *
FROM     CRMADMIN.T_WHSE_ALLOWANCES
WHERE    ITEM_NBR_HS = '4452041'
AND      FACILITYID = '003'
;

SELECT   FACILITYID,
         INVOICE_NBR,
         ITEM_NBR_HS,
         ITEM_DESCRIPTION,
         BILLING_DATE, sum(QTY_SOLD - QTY_SCRATCHED) QTY_SHIPPED,
         sum(VEND_RPA_AMT_EXT) EXT_VEND_RPA_AMT, sum(VEND_RPA_ADMINFEE_EXT) EXT_VEND_RPA_ADMINFEE
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    BILLING_DATE between '2015-01-04' and '2015-01-31'
AND      ITEM_NBR_HS = '4452041'
AND      FACILITYID = '040'
AND      VEND_RPA_AMT_EXT <> 0
group by FACILITYID,
         INVOICE_NBR,
         ITEM_NBR_HS,
         ITEM_DESCRIPTION,
         BILLING_DATE;


SELECT   OFFER,
         FACILITYID,
         ITEM_NBR_HS,
         ALLOW_DATE_EFF,
         ALLOW_DATE_EXP,
         ALLOW_AMT,
         ALLOW_STATUS
FROM     CRMADMIN.T_WHSE_ALLOWANCES
WHERE    ITEM_NBR_HS = '0207012'
AND      FACILITYID = '061'
AND      ALLOW_TYPE = 'VENDRPA';

SELECT   FACILITYID,
         INVOICE_NBR,
         ITEM_NBR_HS,
         ITEM_DESCRIPTION,
         BILLING_DATE,
         VEND_RPA_AMT_EXT
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    BILLING_DATE between '2015-01-03' and '2015-01-31'
AND      ITEM_NBR_HS = '0206679'
AND      FACILITYID = '061'
AND      VEND_RPA_AMT_EXT <> 0;