--need to correct contracts for bad item numbers
--need to fix the admin fee calc


--P&G as the vendor

SELECT   FACILITYID , CUSTOMER_NO_FULL , UPC_CASE , UPC_UNIT , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT,ad_allow_amt 
FROM     CRMADMIN.V_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '058'
--AND      ITEM_NBR = '639781'
AND      ITEM_NBR = '639443'
AND      BILLING_DATE between '2014-06-14' and '2014-07-04'
;

--A vendor with no admin fee (select from admin fee list provided by Dave Mackenzie)

SELECT   FACILITYID , CUSTOMER_NO_FULL , UPC_CASE , UPC_UNIT , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT,ad_allow_amt 
FROM     CRMADMIN.V_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '008'
AND      ITEM_NBR_HS = '0902130'
AND      BILLING_DATE between '2014-06-15' and '2014-07-05'
;

--Heartland region (for any commodity or any DC)
SELECT   FACILITYID , CUSTOMER_NO_FULL , UPC_CASE , UPC_UNIT , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT 
FROM     CRMADMIN.V_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '008'
AND      ITEM_NBR_HS = '0111484'
AND      BILLING_DATE between '2014-06-15' and '2014-07-05'
;

--South region (for any commodity or any DC)

SELECT   FACILITYID , FACILITYID_SHIP, INVOICE_NBR, INVOICE_COUNTER, BILLING_DATE, ITEM_NBR, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT, ad_allow_amt 
FROM     CRMADMIN.V_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '015'
AND      ITEM_NBR = '076604'
AND      BILLING_DATE between '2014-06-14' and '2014-07-04'
;

--5  Great Lakes region (select any commodity in Lima or Westville) 

--why the E's?
--contract fixes
SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT, ad_allow_amt, SPECIAL_COST_CDE_TYPE, INVOICE_COUNTER 
FROM     CRMADMIN.V_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '058'
AND      ITEM_NBR = '183939'
AND      BILLING_DATE between '2014-06-14' and '2014-07-04'
;

--6  Items previously sourced from GMS (DC 71)
--can't find this item?
SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT 
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '061'
AND      ITEM_NBR_HS like '0115908'
AND      BILLING_DATE between '2014-06-14' and '2014-07-04'
;

--8  Grocery item

--can't find this item?

SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT 
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '061'
AND      ITEM_NBR_HS = '0347426'
AND      BILLING_DATE between '2014-06-14' and '2014-07-04'
;


--9  Dairy item  PASSED
--can't find this item?

SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT 
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '008'
AND      ITEM_NBR = '592396'
AND      BILLING_DATE between '2014-06-15' and '2014-07-05'
;


--10 Frozen item  PASSED
--Dave to check on flagged as 'R'

SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT , ad_allow_amt, SPECIAL_COST_CDE_TYPE 
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '059'
AND      ITEM_NBR = '111328'
AND      BILLING_DATE between '2014-06-14' and '2014-07-04'
;

--11  HBC item  PASSED
--only on outed record
SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT  , ad_allow_amt, SPECIAL_COST_CDE_TYPE 
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '054'
AND      ITEM_NBR_HS = '7547961'
AND      BILLING_DATE between '2014-06-15' and '2014-07-05'
;


--12 Processed meat item  PASSED

SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT, AD_ALLOW_AMT
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '008'
AND      ITEM_NBR_HS = '8434540'
AND      BILLING_DATE between '2014-06-15' and '2014-07-05'
;


--13 Bakery item  PASSED
-- has overlapping contracts but only one reflected on billing

SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT, AD_ALLOW_AMT
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '008'
AND      ITEM_NBR = '015644'
AND      BILLING_DATE between '2014-06-15' and '2014-07-05'
;


--20 Frozen item
-- N's should be tagged as R's 
-- multiple overlapping contracts, technically billing correctly but contracts need to be cleaned up

SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT, AD_ALLOW_AMT
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID = '008'
AND      ITEM_NBR = '013590'
AND      BILLING_DATE between '2014-06-01' and '2014-07-29'
;


SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT, AD_ALLOW_AMT
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL
WHERE    FACILITYID in ('005')
AND      ITEM_NBR_HS in ('4109690')
AND      BILLING_DATE between '2014-07-06' and '2014-08-09'
;



SELECT  dtl.FACILITYID, dtl.FACILITYID_SHIP, dtl.BILLING_DATE, dtl.ITEM_DEPT_HS, dtl.ORDER_TYPE, dtl.CUSTOMER_NO_FULL, c.NAME, dtl.ITEM_NBR_HS, dtl.ITEM_DESCRIPTION, dtl.QTY_SOLD, dtl.QTY_SUBBED, dtl.QTY_SCRATCHED, dtl.VEND_RPA, dtl.VEND_RPA_AMT_EXT, dtl.VEND_RPA_ADMINFEE_RATE, dtl.VEND_RPA_ADMINFEE_EXT, dtl.AD_ALLOW_AMT, dtl.REFLECT_ALLOW_AMT, ecpt.RECORD_DESCRIP
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL dtl inner join CRMADMIN.T_WHSE_CUST c on dtl.FACILITYID = c.FACILITYID and dtl.CUSTOMER_NO_FULL = c.CUSTOMER_NO_FULL
 left join ETLADMIN.T_RPA_EXCEPTIONS ecpt
  on dtl.FACILITYID = ecpt.FACILITYID
   and dtl.CUSTOMER_NO_FULL = ecpt.CUSTOMER_NO_FULL
WHERE    dtl.FACILITYID in ('040')
AND      dtl.ITEM_NBR_HS in ('0170449',
'0166223',
'0177402',
'0171769',
'0170928',
'0198788',
'0163428',
'0170860',
'0170951',
'8330649',
'8331076',
'0171066')
AND      dtl.BILLING_DATE between '2014-07-13' and '2014-08-02'
;

--swat
SELECT   FACILITYID , FACILITYID_SHIP, BILLING_DATE, ITEM_DEPT_HS, ORDER_TYPE, CUSTOMER_NO_FULL , ITEM_NBR_HS , ITEM_DESCRIPTION , STORE_PACK , SIZE , QTY_SOLD, QTY_SUBBED, QTY_SCRATCHED , VEND_RPA, VEND_RPA_AMT_EXT, VEND_RPA_ADMINFEE_RATE, VEND_RPA_ADMINFEE_EXT, AD_ALLOW_AMT
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL 
WHERE    FACILITYID in ('058')
AND      ITEM_NBR in ('622829')
AND      BILLING_DATE between '2014-07-19' and '2014-08-08'
;

SELECT  dtl.FACILITYID, dtl.FACILITYID_SHIP, dtl.BILLING_DATE, dtl.ITEM_DEPT_HS, dtl.ORDER_TYPE, dtl.CUSTOMER_NO_FULL, c.NAME, dtl.ITEM_NBR_HS, dtl.ITEM_DESCRIPTION, dtl.QTY_SOLD, dtl.QTY_SUBBED, dtl.QTY_SCRATCHED, dtl.VEND_RPA, dtl.VEND_RPA_AMT_EXT, dtl.VEND_RPA_ADMINFEE_RATE, dtl.VEND_RPA_ADMINFEE_EXT, dtl.QTY_SOLD * dtl.AD_ALLOW_AMT CUST_RPA, dtl.QTY_SOLD * dtl.REFLECT_ALLOW_AMT TOTAL_DEALS, ecpt.RECORD_DESCRIP
FROM     CRMADMIN.T_WHSE_SALES_HISTORY_DTL dtl inner join CRMADMIN.T_WHSE_CUST c on dtl.FACILITYID = c.FACILITYID and dtl.CUSTOMER_NO_FULL = c.CUSTOMER_NO_FULL
 left join ETLADMIN.T_RPA_EXCEPTIONS ecpt
  on dtl.FACILITYID = ecpt.FACILITYID
   and dtl.CUSTOMER_NO_FULL = ecpt.CUSTOMER_NO_FULL
WHERE    dtl.FACILITYID in ('015')
AND      dtl.ITEM_NBR in ('169656')
AND      dtl.BILLING_DATE between '2014-08-23' and '2014-09-06'
;
